import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {Pool} from 'pg';
import {migrate} from '../src/migrate.mjs';
import {PostgresStore} from '../src/postgres-store.mjs';
import {catalogCommandRegistry} from '../src/catalog-commands.mjs';
import {customerCommandRegistry} from '../src/customer-commands.mjs';
import {supplierCommandRegistry} from '../src/supplier-commands.mjs';
import {outletCommandRegistry} from '../src/outlet-commands.mjs';
import {roomCommandRegistry} from '../src/room-commands.mjs';
import {hospitalityCommandRegistry} from '../src/hospitality-commands.mjs';
import {financeAssetCommandRegistry} from '../src/finance-asset-commands.mjs';
import {applyImport,getImportBatch,planImport,stageImport} from '../src/csv-import.mjs';
import {createApiServer} from '../src/server.mjs';

const databaseUrl=process.env.TEST_DATABASE_URL;

test('PostgreSQL API CSV importer stages, dry-runs and applies domain commands with durable external IDs',{skip:!databaseUrl,timeout:120_000},async t=>{
 const adminPool=new Pool({connectionString:databaseUrl,max:2});
 const schema=`csv_import_${randomUUID().replaceAll('-','')}`;
 await adminPool.query(`CREATE SCHEMA "${schema}"`);
 const pool=new Pool({connectionString:databaseUrl,max:12,options:`-c search_path=${schema},public`});
 t.after(async()=>{await pool.end();await adminPool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);await adminPool.end()});
 await migrate(pool);
 const store=new PostgresStore(pool),businessId=randomUUID(),staffId=randomUUID(),deviceId=randomUUID();
 const actor={businessId,staffId,deviceId,permissions:['*']};
 const registry=new Map([...catalogCommandRegistry,...customerCommandRegistry,...supplierCommandRegistry,...outletCommandRegistry,...roomCommandRegistry,...hospitalityCommandRegistry,...financeAssetCommandRegistry]);
 await pool.query('INSERT INTO businesses(id,name) VALUES($1,$2)',[businessId,'Disposable CSV Import Test']);
 const api=createApiServer({store,registry,authenticate:async()=>actor,origin:undefined});await new Promise(resolve=>api.listen(0,'127.0.0.1',resolve));
 const apiOrigin=`http://127.0.0.1:${api.address().port}`;
 const request=async(path,init={})=>{const response=await fetch(`${apiOrigin}${path}`,{...init,headers:{'content-type':'application/json',...(init.headers||{})}});return {status:response.status,body:await response.json()}};
 t.after(async()=>new Promise(resolve=>api.close(resolve)));
 const templates=await request('/v1/import/templates');assert.equal(templates.status,200);assert.equal(templates.body.templates.length,14);

 const stockBatchId=randomUUID();
 const stockRows=Array.from({length:84},(_,index)=>`stock-${index+1},Stock item ${index+1},SKU-${String(index+1).padStart(3,'0')},each,0,`);
 const stockCsv=`external_id,name,code,base_unit,reorder_level,barcode\n${stockRows.join('\n')}\n`;
 const stagedStock=await stageImport(pool,actor,{id:stockBatchId,templateKey:'stockItems',fileName:'stock-items.csv',csvText:stockCsv});
 assert.equal(stagedStock.batch.validCount,84);
 const stockPlan=await planImport({store,registry,actor,batchId:stockBatchId});
 assert.equal(stockPlan.plan.status,'READY');
 assert.deepEqual(stockPlan.plan.summary,{total:84,create:84,noChange:0,blocked:0,conflict:0,applied:0,failed:0});
 const stockSteps=(await pool.query('SELECT steps FROM api_import_plans WHERE business_id=$1 AND id=$2',[businessId,stockPlan.plan.id])).rows[0].steps;
 assert.equal(stockSteps[0].command.name,'stockItem.save');
 assert.equal(Object.hasOwn(stockSteps[0].command.payload.data,'sealedContainerSize'),false);
 assert.deepEqual(Object.keys(stockSteps[0].command.payload.data).sort(),['baseUnit','code','name','reorderLevel']);
 assert.equal((await pool.query('SELECT count(*)::int AS count FROM stock_items WHERE business_id=$1',[businessId])).rows[0].count,0,'stock-item dry-run rolls back domain writes');

 const productBatchId=randomUUID();
 const product=await stageImport(pool,actor,{id:productBatchId,templateKey:'products',fileName:'products.csv',csvText:'external_id,name,code,price\nproduct-standard,Orange Soda,OR-1,1.25\n'});
 assert.equal(product.batch.validCount,1);
 const productPlan=await planImport({store,registry,actor,batchId:productBatchId});
 assert.equal(productPlan.plan.status,'READY','standard product import omits absent portion volume instead of sending null');
 assert.equal(productPlan.plan.summary.blocked,0);
 const productSteps=(await pool.query('SELECT steps FROM api_import_plans WHERE business_id=$1 AND id=$2',[businessId,productPlan.plan.id])).rows[0].steps;
 assert.deepEqual(Object.keys(productSteps[0].command.payload.data).sort(),['code','name','priceMinor']);
 assert.equal(Object.hasOwn(productSteps[0].command.payload.data,'portionVolume'),false);
 assert.equal((await pool.query('SELECT count(*)::int AS count FROM products WHERE business_id=$1',[businessId])).rows[0].count,0,'product dry-run rolls back domain writes');

 const roomTypeBatchId=randomUUID();
 const roomType=await stageImport(pool,actor,{id:roomTypeBatchId,templateKey:'roomTypes',fileName:'room-types.csv',csvText:'external_id,name,code,max_guests\nroom-standard,Standard,,\n'});
 assert.equal(roomType.batch.validCount,1);
 const roomTypePlan=await planImport({store,registry,actor,batchId:roomTypeBatchId});
 assert.equal(roomTypePlan.plan.status,'READY','room-type import delegates optional defaults to the domain command');
 const roomTypeSteps=(await pool.query('SELECT steps FROM api_import_plans WHERE business_id=$1 AND id=$2',[businessId,roomTypePlan.plan.id])).rows[0].steps;
 assert.deepEqual(Object.keys(roomTypeSteps[0].command.payload.data),['name']);
 assert.equal((await pool.query('SELECT count(*)::int AS count FROM business_room_types WHERE business_id=$1',[businessId])).rows[0].count,0,'room-type dry-run rolls back domain writes');

 const locationBatchId=randomUUID();
 const location=await request('/v1/import/batches',{method:'POST',body:JSON.stringify({id:locationBatchId,templateKey:'stockLocations',fileName:'locations.csv',csvText:'external_id,name,code,type\nloc-main,Main Store,STORE-1,STORE\n'})});
 assert.equal(location.status,201);assert.equal(location.body.batch.status,'STAGED');assert.equal(location.body.batch.validCount,1);
 const locationPlan=await request(`/v1/import/batches/${locationBatchId}/plan`,{method:'POST',body:'{}'});
 assert.equal(locationPlan.status,200);assert.equal(locationPlan.body.plan.status,'READY');assert.equal(locationPlan.body.plan.steps[0].status,'PLANNED');
 assert.equal((await pool.query('SELECT count(*)::int AS count FROM stock_locations WHERE business_id=$1',[businessId])).rows[0].count,0,'dry-run rolls back domain writes');
 const appliedLocation=await request(`/v1/import/plans/${locationPlan.body.plan.id}/apply`,{method:'POST',body:'{}'});
 assert.equal(appliedLocation.status,200);assert.equal(appliedLocation.body.plan.status,'APPLIED');assert.equal(appliedLocation.body.plan.summary.applied,1);
 assert.equal((await pool.query('SELECT count(*)::int AS count FROM stock_locations WHERE business_id=$1',[businessId])).rows[0].count,1);
 assert.equal((await pool.query('SELECT count(*)::int AS count FROM api_commands WHERE business_id=$1 AND status=\'CONFIRMED\'',[businessId])).rows[0].count,1);
 assert.equal((await pool.query('SELECT count(*)::int AS count FROM business_audit_events WHERE business_id=$1',[businessId])).rows[0].count,1);
 assert.equal((await pool.query('SELECT count(*)::int AS count FROM api_import_external_ids WHERE business_id=$1 AND template_key=\'stockLocations\' AND external_id_key=\'loc-main\'',[businessId])).rows[0].count,1);
 const persistedBatch=await request(`/v1/import/batches/${locationBatchId}`);
 assert.equal(persistedBatch.body.batch.status,'APPLIED');assert.equal(persistedBatch.body.batch.rows.length,0);assert.equal(persistedBatch.body.plan.steps[0].status,'APPLIED');

 const outletBatchId=randomUUID();
 const outlet=await stageImport(pool,actor,{id:outletBatchId,templateKey:'outlets',fileName:'outlets.csv',csvText:'external_id,name,default_stock_location_external_id\noutlet-main,Main Outlet,loc-main\n'});
 const outletPlan=await planImport({store,registry,actor,batchId:outletBatchId});
 assert.equal(outletPlan.plan.status,'READY');
 const appliedOutlet=await applyImport({store,registry,actor,planId:outletPlan.plan.id});
 assert.equal(appliedOutlet.plan.status,'APPLIED');
 assert.equal((await pool.query('SELECT count(*)::int AS count FROM business_outlets WHERE business_id=$1',[businessId])).rows[0].count,1);
 assert.equal(outlet.batch.validCount,1);

 const simpleTemplate=templates.body.templates.find(item=>item.key==='sellableItems');assert.ok(simpleTemplate);
 const simpleValues={name:'House spirit',code:'SIMPLE-SPIRIT',stock_mode:'SPIRIT',price:'150',tax_class_id:'A_16',service_area:'BAR',outlet_names:'Main Outlet',stock_location_name:'Main Store',base_unit:'ml',units_per_package:'12',quantity_per_unit:'750',purchase_price:'24000',opening_packages:'1',reorder_level:'0',container_size:'750',portion_size:'45',selling_mode:'SERVING_AND_BOTTLE',whole_container_price:'1800'};
 const simpleCsv=`${simpleTemplate.headers.join(',')}\n${simpleTemplate.headers.map(header=>simpleValues[header]||'').join(',')}\n`;
 const simpleBatchId=randomUUID(),simpleBatch=await stageImport(pool,actor,{id:simpleBatchId,templateKey:'sellableItems',fileName:'simple-products.csv',csvText:simpleCsv});
 assert.equal(simpleBatch.batch.validCount,1);
 const simplePlan=await planImport({store,registry,actor,batchId:simpleBatchId});assert.equal(simplePlan.plan.status,'READY');
 const simpleSteps=(await pool.query('SELECT steps FROM api_import_plans WHERE business_id=$1 AND id=$2',[businessId,simplePlan.plan.id])).rows[0].steps;
 assert.equal(simpleSteps[0].operation,'catalog.createWithOpeningStock');assert.equal(simpleSteps[0].targetCollection,'products');
 assert.equal((await pool.query('SELECT count(*)::int AS count FROM products WHERE business_id=$1 AND code=$2',[businessId,'SIMPLE-SPIRIT'])).rows[0].count,0,'the reviewed simple import has not written domain records');
 const simpleApply=await applyImport({store,registry,actor,planId:simplePlan.plan.id});assert.equal(simpleApply.plan.status,'APPLIED');assert.equal(simpleApply.plan.summary.applied,1);
 const linked=(await pool.query(`SELECT p.stock_item_id AS "stockItemId",p.inventory_type AS "inventoryType",s.sealed_container_size AS "containerSize",b.quantity FROM products p JOIN stock_items s ON s.business_id=p.business_id AND s.id=p.stock_item_id JOIN inventory_location_balances b ON b.business_id=s.business_id AND b.stock_item_id=s.id WHERE p.business_id=$1 AND p.code='SIMPLE-SPIRIT'`,[businessId])).rows[0];
 assert.equal(linked.inventoryType,'SPIRIT');assert.equal(Number(linked.containerSize),750);assert.equal(Number(linked.quantity),9000);assert.ok(linked.stockItemId);
});
