import React from 'react';
import type { ManualMpesaInput } from '../../types/runtime';
import { businessDateTimeInput, businessDateTimeToUtc } from '../../utils/businessTime';

export const ManualMpesaFields = ({ value, onChange, timeZone = 'Africa/Nairobi' }: { value: ManualMpesaInput; onChange: (value: ManualMpesaInput) => void; timeZone?: string }) => {
  const field = 'block w-full bg-slate-950 border border-slate-700 rounded p-2 text-white mt-1';
  const localDate = businessDateTimeInput(value.receivedAt, timeZone);
  return <fieldset className="space-y-3 text-xs"><legend className="font-bold mb-2">Business M-Pesa receipt</legend><label className="block">Transaction code<input required autoComplete="off" className={field} value={value.code} onChange={e => onChange({ ...value, code: e.target.value.toUpperCase() })} /></label><label className="block">Receiving till / paybill account<input required className={field} value={value.account} onChange={e => onChange({ ...value, account: e.target.value })} /></label><label className="block">Amount on receipt (KES)<input required type="number" min="0.01" step="0.01" className={field} value={value.receivedAmount} onChange={e => onChange({ ...value, receivedAmount: Number(e.target.value) })} /></label><label className="block">Receipt time<input required type="datetime-local" data-business-timezone={timeZone} className={field} value={localDate} onChange={e => { try { onChange({ ...value, receivedAt: e.target.value ? businessDateTimeToUtc(e.target.value, timeZone) : '' }); } catch { onChange({ ...value, receivedAt: '' }); } }} /></label><label className="flex gap-2"><input type="checkbox" checked={value.confirmed} onChange={e => onChange({ ...value, confirmed: e.target.checked })} />I checked the business receipt and confirmed the code and amount.</label></fieldset>;
};
