import React,{useMemo,useState} from 'react';
import {definePurchasePackage,costPerCanonicalUnit,canonicalizeMeasurement,type MeasurementMode} from '../../utils/inventoryUnits';
import {Dialog} from '../../design-system/controls';
import type {BusinessRecord,WebSession} from './session';

type Command=(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<unknown>;
const input='mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white';
const button='rounded-lg border border-slate-700 px-3 py-2 text-sm disabled:opacity-40';
const primary='rounded-lg bg-amber-400 px-3 py-2 font-bold text-slate-950 disabled:opacity-40';
const cash=(value:number)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES'}).format(value||0);
const fields=(records:BusinessRecord[],collection:string)=>records.filter(record=>record.collection===collection&&!record.archived);

export function SmartItemDialog({records,session,disabled,command,onClose}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:Command;onClose:()=>void}){
 const locations=fields(records,'stockLocations');
 const outlets=fields(records,'outlets');
 const [step,setStep]=useState(0);const [stockOnly,setStockOnly]=useState(false);const [name,setName]=useState('');const [code,setCode]=useState('');const [codeEdited,setCodeEdited]=useState(false);
 const [price,setPrice]=useState(0);const [routeTo,setRouteTo]=useState('BAR');const [category,setCategory]=useState('GENERAL');const [locationId,setLocationId]=useState('');
 const [purchaseName,setPurchaseName]=useState('Case');const [unitsPerPackage,setUnitsPerPackage]=useState(24);const [contents,setContents]=useState(1);const [unit,setUnit]=useState('piece');const [packageCost,setPackageCost]=useState(0);const [openingPackages,setOpeningPackages]=useState(0);const [saleQuantity,setSaleQuantity]=useState(1);const [barcode,setBarcode]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const mode:MeasurementMode=unit==='g'||unit==='kg'?'WEIGHT':unit==='ml'||unit==='l'?'VOLUME':'COUNT';
 const baseUnit=mode==='WEIGHT'?'g':mode==='VOLUME'?'ml':'piece';
 const calculation=useMemo(()=>{try{const pkg=definePurchasePackage({id:'preview',name:purchaseName||'Package',unitsPerPackage,contentsPerSaleUnit:contents,unit,mode,barcode});const unitCost=costPerCanonicalUnit(Math.round(packageCost*100),pkg.baseQuantity,baseUnit);return {pkg,unitCost,opening:pkg.baseQuantity*openingPackages,sale:canonicalizeMeasurement(saleQuantity,unit,mode).quantity}}catch{return null}},[purchaseName,unitsPerPackage,contents,unit,mode,barcode,packageCost,openingPackages,saleQuantity,baseUnit]);
 const sellable=async()=>{
  if(!session.permissions.includes('*')&&!session.permissions.includes('catalog.manage'))throw new Error('This role cannot create sellable catalog items.');
  if(!outlets.length)throw new Error('Add a service area before creating a sellable item.');
  const product={id:'',name:name.trim(),code:code.trim(),price:Number(price),category:category.trim()||'GENERAL',inventoryType:mode==='WEIGHT'?'WEIGHT_INGREDIENT':mode==='VOLUME'?'DRINK':'RETAIL',routeTo,stockItemId:'',outletIds:outlets.map(outlet=>outlet.id),taxClassId:'A_STANDARD',favorite:false,barcode:barcode.trim(),portionVolume:calculation!.sale,portions:[{id:'each',name:mode==='VOLUME'?'One serving':'Each',volume:calculation!.sale,price:Number(price)}],recipeIngredients:[]};
  return product;
 };
 const save=async()=>{setError('');if(busy)return;
  if(!session.permissions.includes('*')&&!session.permissions.includes('inventory.adjust')){setError('This role cannot create a stock master. Ask an Admin to grant inventory adjustment access.');return}
  if(!name.trim()||!code.trim()||!locationId||!calculation||!Number.isFinite(price)||price<0||unitsPerPackage<1||!Number.isInteger(unitsPerPackage)||contents<=0||openingPackages<0||!Number.isInteger(openingPackages)||saleQuantity<=0||packageCost<0){setError('Complete the required item, package, price, and storage details with valid quantities.');return}
  setBusy(true);try{
   const stockItem={name:name.trim(),code:code.trim(),barcode:barcode.trim(),baseUnit,scanUnitQuantity:calculation.pkg.baseQuantity,purchasePackages:[calculation.pkg],averageUnitCost:calculation.unitCost/100,reorderLevel:0};
   await command('catalog.createWithOpeningStock','stockItems',crypto.randomUUID(),{...(stockOnly?{}:{product:await sellable()}),stockItem,locationId,startingQuantity:calculation.opening});
   onClose();
  }catch(cause){setError(cause instanceof Error?cause.message:'The item was not saved. Review the details and try again.')}finally{setBusy(false)}
 };
 const next=()=>{setError('');if(step===0&&(!name.trim()||!code.trim())){setError('Enter an item name and code.');return}if(step===1&&!stockOnly&&(!Number.isFinite(price)||price<0)){setError('Enter a valid selling price.');return}if(step===2&&(!locationId||!calculation)){setError('Choose a storage place and enter a valid package conversion.');return}setStep(value=>Math.min(3,value+1))};
 return <Dialog title={`Smart item setup · ${['Identity','Selling','Package & stock','Review'][step]}`} onClose={busy?()=>undefined:onClose}>
  <div className="max-h-[min(70vh,620px)] space-y-4 overflow-y-auto pr-1">
   {step===0&&<div className="space-y-3"><label className="block text-sm">What are you setting up?<select className={input} value={stockOnly?'STOCK':'SELLABLE'} onChange={event=>setStockOnly(event.target.value==='STOCK')}><option value="SELLABLE">Sellable item with linked stock</option><option value="STOCK">Stock-only ingredient or supply</option></select></label><label className="block text-sm">Item name<input autoFocus className={input} value={name} onChange={event=>{const value=event.target.value;setName(value);if(!codeEdited&&!code){const slug=value.normalize('NFKD').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').toUpperCase().slice(0,18);if(slug)setCode(`${slug}-${crypto.randomUUID().slice(0,4).toUpperCase()}`)}}}/></label><label className="block text-sm">Item code<input className={input} value={code} onChange={event=>{setCode(event.target.value.toUpperCase());setCodeEdited(true)}}/></label><label className="block text-sm">Barcode (optional)<input className={input} value={barcode} onChange={event=>setBarcode(event.target.value.trim())}/></label></div>}
   {step===1&&!stockOnly&&<div className="space-y-3"><label className="block text-sm">Selling price (KES)<input className={input} type="number" min="0" step="0.01" value={price} onChange={event=>setPrice(Number(event.target.value))}/></label><label className="block text-sm">Category<input className={input} value={category} onChange={event=>setCategory(event.target.value)}/></label><label className="block text-sm">Preparation station<select className={input} value={routeTo} onChange={event=>setRouteTo(event.target.value)}><option>BAR</option><option>KITCHEN</option><option>SERVICE</option></select></label></div>}
   {step===1&&stockOnly&&<p className="rounded-lg border border-slate-700 p-3 text-sm text-slate-300">This item will be created as stock only and will not appear at the point of sale.</p>}
   {step===2&&<div className="space-y-3"><label className="block text-sm">Purchase package name<input className={input} value={purchaseName} onChange={event=>setPurchaseName(event.target.value)}/></label><label className="block text-sm">Number of units per package<input className={input} type="number" min="1" step="1" value={unitsPerPackage} onChange={event=>setUnitsPerPackage(Number(event.target.value))}/></label><div className="grid grid-cols-2 gap-2"><label className="block text-sm">Stock quantity in one unit<input className={input} type="number" min="0.000001" step="any" value={contents} onChange={event=>setContents(Number(event.target.value))}/></label><label className="block text-sm">Measurement unit<select className={input} value={unit} onChange={event=>setUnit(event.target.value)}>{['piece','g','kg','ml','l'].map(value=><option key={value}>{value}</option>)}</select></label></div><label className="block text-sm">Purchase price per {purchaseName||'package'} (KES)<input className={input} type="number" min="0" step="0.01" value={packageCost} onChange={event=>setPackageCost(Number(event.target.value))}/></label><label className="block text-sm">Opening packages on hand<input className={input} type="number" min="0" step="1" value={openingPackages} onChange={event=>setOpeningPackages(Number(event.target.value))}/></label><label className="block text-sm">Storage place<select className={input} value={locationId} onChange={event=>setLocationId(event.target.value)}><option value="">Choose storage place</option>{locations.map(location=><option key={location.id} value={location.id}>{String(location.data.name||location.id)}</option>)}</select></label>{!stockOnly&&<label className="block text-sm">Stock quantity used for each sale<input className={input} type="number" min="0.000001" step="any" value={saleQuantity} onChange={event=>setSaleQuantity(Number(event.target.value))}/></label>}{calculation&&<div className="rounded-lg bg-slate-950 p-3 text-sm">One {purchaseName||'package'} = {calculation.pkg.baseQuantity.toLocaleString()} {baseUnit} · opening stock {calculation.opening.toLocaleString()} {baseUnit} · cost {cash(calculation.unitCost/100)} per {baseUnit}</div>}</div>}
   {step===3&&<div className="space-y-2 rounded-lg border border-amber-500/30 bg-amber-500/5 p-4 text-sm"><h3 className="font-bold">Review before saving</h3><p>{name} · {code}</p><p>{stockOnly?'Stock-only':'Sellable at '+cash(price)} · {routeTo}</p><p>{calculation?`${purchaseName}: ${calculation.pkg.baseQuantity} ${baseUnit} per package; ${openingPackages} packages opened as ${calculation.opening} ${baseUnit}.`:'Package details are incomplete.'}</p><p className="text-xs text-slate-400">The server creates the catalog record, stock master, link, and optional opening movement atomically. A rejection leaves all of them unchanged.</p></div>}
   {error&&<p role="alert" className="rounded-lg border border-rose-800 p-3 text-sm text-rose-200">{error}</p>}
  </div>
  <div className="mt-4 flex justify-between gap-2 border-t border-slate-800 pt-3"><button type="button" className={button} disabled={busy||step===0} onClick={()=>setStep(value=>Math.max(0,value-1))}>Back</button>{step<3?<button type="button" className={primary} disabled={disabled||busy} onClick={next}>Continue</button>:<button type="button" className={primary} disabled={disabled||busy||!calculation}>{busy?'Saving item…':'Save item and opening stock'}</button>}{step===3&&<button type="button" className={primary} disabled={disabled||busy||!calculation} onClick={()=>void save()}>{busy?'Saving item…':'Save item and opening stock'}</button>}</div>
 </Dialog>;
}
