import {operatorError} from './operatorError';
import {parseMoneyToMinor,parsePercentToBasisPoints} from '../../utils/fiscal';
import {WebOutletSettings} from './WebOutletSettings';
import React,{useRef,useState} from 'react';
import {allowed,type BusinessRecord,type WebSession} from './session';
import {isCommandConfirmed,type CommandOutcome} from '../../types/transactions';
import {prepareDocumentLogoPng,prepareMpesaTillQr} from '../../receipts/branding';

type Field={key:string;label:string;kind?:'number'|'checkbox'|'textarea'|'select';choices?:string[];required?:boolean};
type Editor={kind:'BUSINESS'|'TILL'|'ACCOUNT';collection:string;id:string;version:number;values:Record<string,string|boolean>};
type Command=(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<CommandOutcome>;
const input='mt-1 block w-full rounded border border-slate-700 bg-slate-950 p-2';
const button='rounded border border-slate-600 px-3 py-2 disabled:opacity-40';
const percent=(value:unknown)=>typeof value==='number'?String(value/100):'';
const minor=(value:string|boolean)=>parseMoneyToMinor(value);

export function WebApiSettings({records,session,disabled,command}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:Command}){
 const [editor,setEditor]=useState<Editor|null>(null),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState(false);
 const inFlight=useRef(false);
 const business=records.find(row=>row.collection==='businessSettings'&&row.id===session.businessId);
 const till=records.find(row=>row.collection==='tillPolicy'&&row.id===session.businessId);
 const accounts=records.filter(row=>row.collection==='paymentAccounts');
 const open=(kind:Editor['kind'],record?:BusinessRecord)=>{
  const d=record?.data||{};let values:Editor['values'];
  if(kind==='BUSINESS')values={businessName:String(d.businessName||''),address:String(d.address||''),contact:String(d.contact||''),taxPin:String(d.taxPin||''),footer:String(d.footer||''),vatRatePct:percent(d.vatRateBasisPoints),levyRatePct:percent(d.levyRateBasisPoints),logoPngDataUrl:String(d.logoPngDataUrl||''),paymentQrPngDataUrl:String(d.paymentQrPngDataUrl||''),paymentQrEnabled:d.paymentQrEnabled===true};
  else if(kind==='TILL')values={scope:String(d.scope||'SINGLE_BUSINESS'),varianceThreshold:typeof d.varianceThresholdMinor==='number'?String(d.varianceThresholdMinor/100):'0'};
  else values={name:String(d.name||''),code:String(d.code||''),method:String(d.method||'CASH'),referenceRequired:d.referenceRequired===true,archived:record?.archived===true,mpesaMode:String(d.mpesaMode||'TILL'),mpesaNumber:String(d.mpesaNumber||''),mpesaAccountReference:String(d.mpesaAccountReference||'')};
  setEditor({kind,collection:kind==='BUSINESS'?'businessSettings':kind==='TILL'?'tillPolicy':'paymentAccounts',id:kind==='ACCOUNT'?record?.id||crypto.randomUUID():session.businessId,version:record?.version??0,values});setReason('');setMessage('');setPending(false);
 };
 const fields:Field[]=editor?.kind==='BUSINESS'?[{key:'businessName',label:'Business name',required:true},{key:'address',label:'Address',kind:'textarea'},{key:'contact',label:'Contact'},{key:'taxPin',label:'Tax PIN'},{key:'vatRatePct',label:'VAT rate (%)',kind:'number',required:true},{key:'levyRatePct',label:'Levy rate (%)',kind:'number',required:true},{key:'footer',label:'Receipt footer',kind:'textarea'}]:editor?.kind==='TILL'?[{key:'scope',label:'Till scope',kind:'select',choices:['SINGLE_BUSINESS','OUTLET','OPERATOR_DEVICE']},{key:'varianceThreshold',label:'Variance review threshold (KES)',kind:'number',required:true}]:[{key:'name',label:'Payment account name',required:true},{key:'code',label:'Account code',required:true},{key:'method',label:'Tender method',kind:'select',choices:['CASH','MPESA','CARD','BANK']},{key:'referenceRequired',label:'Require an external payment reference',kind:'checkbox'},{key:'archived',label:'Archive this payment account',kind:'checkbox'},...(editor?.values.method==='MPESA'?[{key:'mpesaMode',label:'M-Pesa destination',kind:'select' as const,choices:['TILL','PAYBILL']},{key:'mpesaNumber',label:'Till / paybill number',required:true},...(editor.values.mpesaMode==='PAYBILL'?[{key:'mpesaAccountReference',label:'Paybill account reference',required:true}]:[])]:[])];
 const submit=async(event:React.FormEvent)=>{
  event.preventDefault();if(!editor||inFlight.current||pending||disabled)return;inFlight.current=true;setBusy(true);setMessage('');
  try{
   const v=editor.values;let operation:string,payload:Record<string,unknown>;
   if(editor.kind==='BUSINESS'){operation='business.settings.save';const vat=parsePercentToBasisPoints(v.vatRatePct),levy=parsePercentToBasisPoints(v.levyRatePct);if(vat>10000||levy>10000)throw new Error('Tax rates must be between 0% and 100%.');if(v.paymentQrEnabled===true&&!v.paymentQrPngDataUrl)throw new Error('Upload a payment QR image before enabling it.');payload={data:{businessName:v.businessName,address:v.address,contact:v.contact,taxPin:v.taxPin,footer:v.footer,vatRateBasisPoints:vat,levyRateBasisPoints:levy,logoPngDataUrl:v.logoPngDataUrl||null,paymentQrPngDataUrl:v.paymentQrPngDataUrl||null,paymentQrEnabled:v.paymentQrEnabled===true}};}
   else if(editor.kind==='TILL'){operation='till.policy.save';payload={scope:v.scope,varianceThresholdMinor:minor(v.varianceThreshold)};}
   else{operation='paymentAccount.save';payload={id:editor.id,data:{name:v.name,code:v.code,method:v.method,currency:'KES',referenceRequired:v.referenceRequired,archived:v.archived,...(v.method==='MPESA'?{mpesaMode:v.mpesaMode,mpesaNumber:v.mpesaNumber,...(v.mpesaMode==='PAYBILL'?{mpesaAccountReference:v.mpesaAccountReference}:{})}:{})}};}
   const outcome=await command(operation,editor.collection,editor.id,{...payload,reason:reason.trim(),expectedVersions:[{collection:editor.collection,id:editor.id,version:editor.version}]});
   if(isCommandConfirmed(outcome)){setEditor(null);setMessage('Settings saved and confirmed.');}
   else{if(outcome.kind==='PENDING'||outcome.kind==='OUTCOME_UNKNOWN')setPending(true);setMessage('message' in outcome?outcome.message:'The original action is saved. Check Activity before submitting another configuration change.');}
  }catch(error){setMessage(operatorError(error))}finally{inFlight.current=false;setBusy(false)}
 };
 return <section className="space-y-6">
  <header className="space-y-1"><h2 className="text-xl font-bold">Business and payment settings</h2><p className="max-w-3xl text-sm leading-6 text-slate-400">Set property rules, outlets, receipt details, till controls, and payment accounts. Each section saves independently and confirms its result.</p></header>
  <ApiHospitalitySettings records={records} session={session} disabled={disabled||busy||pending} command={command}/>
  <WebOutletSettings records={records} disabled={disabled||busy||pending} command={command}/>
  <section className="space-y-4 rounded-xl border border-slate-700 bg-slate-950/40 p-4 sm:p-5">
   <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">Business controls</h3><p className="mt-1 max-w-3xl text-sm leading-6 text-slate-400">Tax changes affect new documents. Till policy changes require all tills to be closed and reviewed.</p></div><div className="flex flex-wrap gap-2">{allowed(session,'business.tax.configure')&&<button disabled={disabled||busy||pending} className={button} onClick={()=>open('BUSINESS',business)}>Business identity and tax</button>}<button disabled={disabled||busy||pending} className={button} onClick={()=>open('TILL',till)}>Till policy</button><button disabled={disabled||busy||pending} className="rounded bg-amber-400 px-4 py-2 font-bold text-slate-950 disabled:opacity-40" onClick={()=>open('ACCOUNT')}>Add payment account</button></div></div>
<div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{accounts.map(row=><button key={row.id} disabled={disabled||busy||pending} className={`${button} flex min-h-12 items-center justify-between gap-3 text-left`} onClick={()=>open('ACCOUNT',row)}><span className="min-w-0"><span className="block truncate font-semibold">{String(row.data.name)}</span><span className="mt-0.5 block text-xs text-slate-400">{String(row.data.method)}{row.archived ? ' - Archived' : ''}</span></span><span className="text-xs text-slate-400">Open</span></button>)}</div>
  </section>
  {editor&&<form aria-label="Edit business settings" onSubmit={event=>void submit(event)} className="space-y-4 rounded-xl border border-slate-700 bg-slate-900/80 p-4 sm:p-5">
   <h3 className="font-bold">{editor.kind==='BUSINESS'?'Receipt identity and tax rates':editor.kind==='TILL'?'Till scope and variance policy':'Payment account'}</h3>
   {fields.map(field=><label key={field.key} className="block text-sm">{field.kind==='checkbox'?<><input type="checkbox" disabled={busy||pending} checked={editor.values[field.key]===true} onChange={event=>setEditor({...editor,values:{...editor.values,[field.key]:event.target.checked}})}/> {field.label}</>:<>{field.label}{field.kind==='select'?<select className={input} disabled={busy||pending||field.key==='method'&&editor.version>0} value={String(editor.values[field.key]??'')} onChange={event=>setEditor({...editor,values:{...editor.values,[field.key]:event.target.value}})}>{field.choices?.map(choice=><option key={choice}>{choice}</option>)}</select>:field.kind==='textarea'?<textarea className={input} disabled={busy||pending} value={String(editor.values[field.key]??'')} onChange={event=>setEditor({...editor,values:{...editor.values,[field.key]:event.target.value}})}/>:<input className={input} disabled={busy||pending} required={field.required} type={field.kind==='number'?'number':'text'} min={field.kind==='number'?0:undefined} step={field.kind==='number'?'0.01':undefined} value={String(editor.values[field.key]??'')} onChange={event=>setEditor({...editor,values:{...editor.values,[field.key]:event.target.value}})}/>}</>}</label>)}
   {editor.kind==='BUSINESS'&&<section className="space-y-3 rounded border border-slate-700 p-3" aria-label="Receipt images">
    <h4 className="font-semibold">Receipt logo and M-Pesa QR</h4>
    <label className="block text-sm">Business logo (PNG, JPEG, or WebP)
     <input className={input} type="file" accept="image/png,image/jpeg,image/webp" disabled={busy||pending} onChange={event=>{const file=event.currentTarget.files?.[0];event.currentTarget.value='';if(!file)return;void prepareDocumentLogoPng(file).then(dataUrl=>setEditor(current=>current?{...current,values:{...current.values,logoPngDataUrl:dataUrl}}:current)).catch(error=>setMessage(operatorError(error)));}}/>
    </label>
    {typeof editor.values.logoPngDataUrl==='string'&&editor.values.logoPngDataUrl&&<div className="flex items-center gap-3"><img src={editor.values.logoPngDataUrl} alt="Business logo preview" className="max-h-20 max-w-48 bg-white object-contain"/><button type="button" className={button} disabled={busy||pending} onClick={()=>setEditor({...editor,values:{...editor.values,logoPngDataUrl:''}})}>Remove logo</button></div>}
    <label className="block text-sm">Uploaded M-Pesa Till QR (square, clear image)
     <input className={input} type="file" accept="image/png,image/jpeg,image/webp" disabled={busy||pending} onChange={event=>{const file=event.currentTarget.files?.[0];event.currentTarget.value='';if(!file)return;void prepareMpesaTillQr(file).then(prepared=>setEditor(current=>current?{...current,values:{...current.values,paymentQrPngDataUrl:prepared.dataUrl,paymentQrEnabled:true}}:current)).catch(error=>setMessage(operatorError(error)));}}/>
    </label>
    {typeof editor.values.paymentQrPngDataUrl==='string'&&editor.values.paymentQrPngDataUrl&&<div className="flex items-center gap-3"><img src={editor.values.paymentQrPngDataUrl} alt="M-Pesa payment QR preview" className="h-28 w-28 bg-white object-contain"/><button type="button" className={button} disabled={busy||pending} onClick={()=>setEditor({...editor,values:{...editor.values,paymentQrPngDataUrl:'',paymentQrEnabled:false}})}>Remove payment QR</button></div>}
    <label className="block text-sm"><input type="checkbox" disabled={busy||pending||!editor.values.paymentQrPngDataUrl} checked={editor.values.paymentQrEnabled===true} onChange={event=>setEditor({...editor,values:{...editor.values,paymentQrEnabled:event.target.checked}})}/> Show this QR on sales receipts</label>
    <p className="text-xs text-slate-400">The uploaded QR is a payment convenience only. It does not confirm that M-Pesa payment was received; staff must verify and record payment.</p>
   </section>}
   <label className="block text-sm">Change reason<textarea className={input} required minLength={3} maxLength={500} disabled={busy||pending} value={reason} onChange={event=>setReason(event.target.value)}/></label>
   <button disabled={disabled||busy||pending||reason.trim().length<3} className="rounded bg-amber-400 px-4 py-2 font-bold text-slate-950 disabled:opacity-40">Save settings</button><button type="button" disabled={busy} className={`${button} ml-2`} onClick={()=>setEditor(null)}>Close</button>
  </form>}
  {message&&<p role="status" className="text-sm text-amber-200">{message}</p>}
 </section>;
}

function ApiHospitalitySettings({records,session,disabled,command}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:Command}){
 const existing=records.find(row=>row.collection==='hospitalitySettings'&&row.id===session.businessId);const roomTypes=records.filter(row=>row.collection==='roomTypes'&&!row.archived),rates=records.filter(row=>row.collection==='ratePlans'&&!row.archived);const services=records.filter(row=>row.collection==='hotelServices'&&!row.archived);
 const [timeZone,setTimeZone]=useState(String(existing?.data.timeZone||session.propertyContext?.timeZone||'Africa/Nairobi')),[checkout,setCheckout]=useState(String(existing?.data.nightlyCheckoutTime||session.propertyContext?.nightlyCheckoutTime||'10:00')),[cutoff,setCutoff]=useState(String(existing?.data.dayStayCutoffTime||session.propertyContext?.dayStayCutoffTime||'18:00')),[roomTypeId,setRoomTypeId]=useState(String(existing?.data.roomStayRoomTypeId||roomTypes[0]?.id||'')),[ratePlanId,setRatePlanId]=useState(String(existing?.data.roomStayRatePlanId||''));
 const [serviceCode,setServiceCode]=useState(''),[serviceName,setServiceName]=useState(''),[servicePrice,setServicePrice]=useState(''),[serviceTax,setServiceTax]=useState('0'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const nightlyRates=rates.filter(row=>row.data.mode==='NIGHTLY'&&row.data.roomTypeId===roomTypeId);
 const savePolicy=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setMessage('');try{const outcome=await command('hospitality.settings.save','hospitalitySettings',session.businessId,{timeZone,nightlyCheckoutTime:checkout,dayStayCutoffTime:cutoff,roomStayRoomTypeId:roomTypeId||null,roomStayRatePlanId:ratePlanId||null,expectedVersions:[{collection:'hospitalitySettings',id:session.businessId,version:existing?.version||0}]});setMessage(outcome.kind==='CONFIRMED'?'Property hospitality policy saved and confirmed.':('message'in outcome?outcome.message:'Property policy was not confirmed. Review Activity before retrying.'))}catch(error){setMessage(operatorError(error))}finally{setBusy(false)}};
 const saveService=async(event:React.FormEvent)=>{event.preventDefault();const price=parseMoneyToMinor(servicePrice),tax=parsePercentToBasisPoints(serviceTax),id=crypto.randomUUID();setBusy(true);setMessage('');try{const outcome=await command('hotelService.save','hotelServices',id,{id,data:{code:serviceCode,name:serviceName,priceMinor:price,taxBasisPoints:tax},expectedVersions:[{collection:'hotelServices',id,version:0}]});if(outcome.kind==='CONFIRMED'){setServiceCode('');setServiceName('');setServicePrice('');setServiceTax('0')}setMessage(outcome.kind==='CONFIRMED'?'Hotel service saved and confirmed.':('message'in outcome?outcome.message:'Hotel service was not confirmed. Review Activity.'))}catch(error){setMessage(operatorError(error))}finally{setBusy(false)}};
  return <section className="grid items-stretch gap-4 xl:grid-cols-2">
   <form className="flex min-w-0 flex-col gap-4 rounded-xl border border-slate-700 bg-slate-950/50 p-4 sm:p-5" onSubmit={event=>void savePolicy(event)}>
    <div><h3 className="font-semibold">Property stay policy</h3><p className="mt-1 text-sm leading-6 text-slate-400">Set the property time zone and standard room times. These rules are checked when a reservation is created.</p></div>
    <label className="block text-sm">IANA time zone<input required className={input} value={timeZone} disabled={disabled||busy} onChange={event=>setTimeZone(event.target.value)}/></label>
    <div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm">Nightly checkout<input required type="time" className={input} value={checkout} disabled={disabled||busy} onChange={event=>setCheckout(event.target.value)}/></label><label className="block text-sm">Day-stay cutoff<input required type="time" className={input} value={cutoff} disabled={disabled||busy} onChange={event=>setCutoff(event.target.value)}/></label></div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm">Default room type<select className={input} value={roomTypeId} disabled={disabled||busy} onChange={event=>{setRoomTypeId(event.target.value);setRatePlanId('')}}><option value="">No default</option>{roomTypes.map(row=><option key={row.id} value={row.id}>{String(row.data.name)}</option>)}</select></label><label className="block text-sm">Default nightly rate<select className={input} value={ratePlanId} disabled={disabled||busy||!roomTypeId} onChange={event=>setRatePlanId(event.target.value)}><option value="">No default</option>{nightlyRates.map(row=><option key={row.id} value={row.id}>{String(row.data.name)}  -  {String(row.data.priceMinor)}</option>)}</select></label></div>
    <button disabled={disabled||busy||checkout>=cutoff||Boolean(roomTypeId)!==Boolean(ratePlanId)} className={`${button} mt-auto self-start`}>Save property stay policy</button>
   </form>
   <form className="flex min-w-0 flex-col gap-4 rounded-xl border border-slate-700 bg-slate-950/50 p-4 sm:p-5" onSubmit={event=>void saveService(event)}>
    <div><h3 className="font-semibold">Guest services</h3><p className="mt-1 text-sm leading-6 text-slate-400">Add billable extras that can be posted to a guest account.</p></div>
    <div className="max-h-28 overflow-auto rounded-lg border border-slate-700 bg-slate-900/60 p-3 text-sm text-slate-300">{services.map(row=><div key={row.id} className="flex flex-wrap justify-between gap-x-3 border-b border-slate-700 py-2 last:border-b-0"><span>{String(row.data.name)}</span><span>{String(row.data.priceMinor)} KES  -  {String(row.data.taxBasisPoints)} bps</span></div>)}{services.length===0&&<p className="text-slate-400">No guest services configured yet.</p>}</div>
    <div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm">Service code<input required className={input} value={serviceCode} disabled={disabled||busy} onChange={event=>setServiceCode(event.target.value)}/></label><label className="block text-sm">Service name<input required className={input} value={serviceName} disabled={disabled||busy} onChange={event=>setServiceName(event.target.value)}/></label><label className="block text-sm">Price (KES)<input required type="number" min="0" step="0.01" className={input} value={servicePrice} disabled={disabled||busy} onChange={event=>setServicePrice(event.target.value)}/></label><label className="block text-sm">Tax (%)<input required type="number" min="0" max="100" step="0.01" className={input} value={serviceTax} disabled={disabled||busy} onChange={event=>setServiceTax(event.target.value)}/></label></div>
    <button disabled={disabled||busy||!allowed(session,'business.configure')} className={`${button} mt-auto self-start`}>Add guest service</button>
   </form>
   {message&&<p role="status" className="text-sm text-amber-200 xl:col-span-2">{message}</p>}
  </section>;
}
