import React,{useEffect,useRef,useState} from 'react';
import {allowed,type BusinessRecord,type WebSession} from './session';
import type {QueuedCommand} from './BusinessStore';
import {isCommandConfirmed,type CommandOutcome} from '../../types/transactions';
type Command=(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<CommandOutcome>;
const obj=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'?value as Record<string,unknown>:{};
const next:Record<string,string>={FIRED:'PREPARING',PREPARING:'READY',READY:'SERVED'};
export function WebApiPreparationPanel({records,session,queue,disabled,command}:{records:BusinessRecord[];session:WebSession;queue:QueuedCommand[];disabled:boolean;command:Command}){
 const [station,setStation]=useState('KITCHEN'),[showServed,setShowServed]=useState(false),[busy,setBusy]=useState(false),[pendingId,setPendingId]=useState(''),[message,setMessage]=useState('');
 const inFlight=useRef(false);
 useEffect(()=>{if(!pendingId)return;const entry=queue.find(row=>row.id===pendingId);if(!entry||['PENDING_SYNC','OUTCOME_UNKNOWN'].includes(entry.state))return;setPendingId('');setMessage(entry.state==='SYNCHRONIZED'?'Original preparation action confirmed after recovery.':entry.result?.error?.message||'Preparation did not confirm. Review current status before trying again.');},[queue,pendingId]);
 if(!allowed(session,'kds.view')&&!allowed(session,'kds.update'))return null;
 const lines=records.filter(row=>row.collection==='orders'&&!row.archived&&row.data.state!=='VOIDED').flatMap(order=>(Array.isArray(order.data.items)?order.data.items:[]).map(obj).filter(line=>line.state==='FIRED'&&line.routeTo===station&&(showServed||line.preparationStatus!=='SERVED')).map(line=>({order,line})));
 const advance=async(order:BusinessRecord,line:Record<string,unknown>)=>{
  const status=next[String(line.preparationStatus)];if(!status||disabled||inFlight.current||pendingId)return;inFlight.current=true;setBusy(true);setMessage('');
  try{const outcome=await command('order.kds','orders',order.id,{orderId:order.id,itemId:line.id,station,status,expectedVersions:[{collection:'orders',id:order.id,version:order.version}]});if(isCommandConfirmed(outcome))setMessage('Preparation status confirmed.');else{if(outcome.kind==='PENDING'||outcome.kind==='OUTCOME_UNKNOWN')setPendingId(outcome.commandId);setMessage('message' in outcome?outcome.message:'Checking the original preparation action. Do not repeat it.');}}catch(error){setMessage(error instanceof Error?error.message:String(error))}finally{inFlight.current=false;setBusy(false)}
 };
 return <section className="space-y-3 rounded-xl border border-slate-700 p-3"><h3 className="font-bold">Preparation pass</h3><div className="flex flex-wrap gap-3"><label>Station<select className="ml-2 rounded bg-slate-950 p-2" value={station} onChange={event=>setStation(event.target.value)}>{['KITCHEN','BAR','ROOMS'].map(value=><option key={value}>{value}</option>)}</select></label><label className="flex items-center gap-2"><input type="checkbox" checked={showServed} onChange={event=>setShowServed(event.target.checked)}/>Include served</label></div><p className="text-xs text-slate-400">Fired lines only. Held drafts stay in the order. Payment completion does not mark food or drinks served. Recovery includes open orders and unfinished preparation; served history is limited to recent closed orders.</p><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{lines.map(({order,line})=><article key={`${order.id}:${String(line.id)}`} className="space-y-2 rounded border border-slate-700 bg-slate-950 p-3"><h4 className="font-bold">{String(order.data.name)} - {String(line.name)}</h4><p>{String(line.quantity)} - {String(line.courseName||'No course')}</p>{Boolean(line.notes)&&<p className="whitespace-pre-wrap">{String(line.notes)}</p>}{Array.isArray(line.modifierSnapshots)&&line.modifierSnapshots.map(obj).map(modifier=><p key={String(modifier.id)}>{String(modifier.name)}</p>)}<p>Status: {String(line.preparationStatus||'Unknown')}</p>{next[String(line.preparationStatus)]&&allowed(session,'kds.update')&&<button type="button" className="min-h-11 rounded bg-amber-400 px-3 py-2 font-bold text-slate-950 disabled:opacity-40" disabled={disabled||busy||Boolean(pendingId)} onClick={()=>void advance(order,line)}>Mark {next[String(line.preparationStatus)]}</button>}</article>)}</div>{!lines.length&&<p>No loaded fired items at this station.</p>}{message&&<p role="status">{message}</p>}</section>;
}
