import {operatorError} from './operatorError';
import React,{useEffect,useRef,useState} from 'react';
import {allowed,type BusinessRecord,type WebSession} from './session';
import type {QueuedCommand} from './BusinessStore';
import type {CommandOutcome} from '../../types/transactions';
import type {createServOSApiClient} from './apiClient';
import {parseMoneyToMinor} from '../../utils/fiscal';

type Form={customerId:string;version:number;limit:string;terms:string;status:'ACTIVE'|'HOLD'|'CLOSED';notes:string};
const input='mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2';
const button='rounded border border-slate-600 px-3 py-2 disabled:opacity-40';
const money=(value:unknown)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES'}).format(Number(value||0)/100);

export function WebApiCreditAccounts({records,queue,session,disabled,command,client}:{records:BusinessRecord[];queue:QueuedCommand[];session:WebSession;disabled:boolean;command:(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<CommandOutcome>;client:ReturnType<typeof createServOSApiClient>}){
 const [form,setForm]=useState<Form|null>(null),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[pendingId,setPendingId]=useState(''),[statementCustomer,setStatementCustomer]=useState('');
 const [statementRows,setStatementRows]=useState<BusinessRecord[]>([]),[statementCursor,setStatementCursor]=useState<string|null>(null),[statementHasMore,setStatementHasMore]=useState(false),[statementLoading,setStatementLoading]=useState(false),[statementError,setStatementError]=useState('');
 const [reconcileCustomer,setReconcileCustomer]=useState(''),[reconcileId,setReconcileId]=useState(''),[statementBalance,setStatementBalance]=useState(''),[statementReference,setStatementReference]=useState(''),[reconcileNotes,setReconcileNotes]=useState(''),[resolveDiscrepancy,setResolveDiscrepancy]=useState(''),[resolutionOutcome,setResolutionOutcome]=useState('STATEMENT_ERROR'),[resolutionNote,setResolutionNote]=useState('');
 const [settlementCustomer,setSettlementCustomer]=useState(''),[settlementAmount,setSettlementAmount]=useState(''),[settlementAccount,setSettlementAccount]=useState(''),[settlementReference,setSettlementReference]=useState(''),[settlementReceivedAt,setSettlementReceivedAt]=useState(()=>new Date().toISOString().slice(0,16)),[settlementTill,setSettlementTill]=useState(''),[settlementConfirmed,setSettlementConfirmed]=useState(false),[settlementReason,setSettlementReason]=useState('');
 const [writeOffCustomer,setWriteOffCustomer]=useState(''),[writeOffAmount,setWriteOffAmount]=useState(''),[writeOffReason,setWriteOffReason]=useState(''),[writeOffConfirmed,setWriteOffConfirmed]=useState(false),[writeOffApprovalToken,setWriteOffApprovalToken]=useState('');
 const [reverseEntryId,setReverseEntryId]=useState(''),[reverseReason,setReverseReason]=useState(''),[reverseTill,setReverseTill]=useState(''),[reverseConfirmed,setReverseConfirmed]=useState(false),[reverseExternalReference,setReverseExternalReference]=useState(''),[reverseApprovalToken,setReverseApprovalToken]=useState('');
 const inFlight=useRef(false),statementRequest=useRef(0),manage=allowed(session,'credit.manage');
 const customers=records.filter(row=>row.collection==='customers'&&!row.archived).sort((a,b)=>String(a.data.name).localeCompare(String(b.data.name)));
 const accounts=records.filter(row=>row.collection==='customerCreditAccounts'&&!row.archived);
 const paymentAccounts=records.filter(row=>row.collection==='paymentAccounts'&&!row.archived&&row.data.currency==='KES'&&['CASH','MPESA','CARD'].includes(String(row.data.method)));
 const openTills=records.filter(row=>row.collection==='tillSessions'&&!row.archived&&row.data.status==='OPEN');
 const entries=statementRows;
 const reconciliations=records.filter(row=>row.collection==='customerCreditReconciliations'),discrepancies=records.filter(row=>row.collection==='customerCreditDiscrepancies');
 const unresolved=queue.some(row=>['customerCredit.configure','credit.settle','credit.writeOff','credit.reverse','credit.reconcile','credit.discrepancy.resolve'].includes(row.command.operation)&&['PENDING_SYNC','OUTCOME_UNKNOWN'].includes(row.state));
 const blocked=disabled||busy||unresolved||Boolean(pendingId);
 const loadStatement=async(customerId:string,cursor?:string,append=false)=>{const request=++statementRequest.current;setStatementLoading(true);setStatementError('');try{const page=await client.customerCreditStatement(customerId,cursor,100);if(request!==statementRequest.current)return;const next=page.items as BusinessRecord[];setStatementRows(previous=>append?[...previous.filter(row=>!next.some(item=>item.id===row.id)),...next]:next);setStatementCustomer(customerId);setStatementCursor(page.nextCursor);setStatementHasMore(page.hasMore)}catch(error){if(request===statementRequest.current)setStatementError(error instanceof Error?error.message:'Credit statement could not be loaded.')}finally{if(request===statementRequest.current)setStatementLoading(false)}};
 const openStatement=(customerId:string)=>{if(statementCustomer===customerId){statementRequest.current++;setStatementCustomer('');setStatementRows([]);setStatementCursor(null);setStatementHasMore(false);setStatementError('');setStatementLoading(false);return}setStatementRows([]);setStatementCursor(null);setStatementHasMore(false);void loadStatement(customerId)};
 useEffect(()=>{if(!pendingId)return;const row=queue.find(entry=>entry.id===pendingId);if(!row||!['SYNCHRONIZED','REJECTED','CONFLICT'].includes(row.state))return;setPendingId('');setForm(null);setSettlementCustomer('');setWriteOffCustomer('');setReverseEntryId('');setReconcileCustomer('');setResolveDiscrepancy('');setMessage(row.state==='SYNCHRONIZED'?(row.command.operation==='credit.settle'?'Customer settlement and payment acknowledgement confirmed.':row.command.operation==='credit.writeOff'?'Customer receivable write-off confirmed.':row.command.operation==='credit.reverse'?'Customer credit reversal and notice confirmed.':row.command.operation==='credit.reconcile'?'Customer credit statement reconciliation recorded.':row.command.operation==='credit.discrepancy.resolve'?'Customer credit discrepancy resolution recorded.':'Credit account terms saved and confirmed.'):row.result?.error?.message||'The original account change needs review. Refresh before trying again.');},[queue,pendingId]);
 const open=(customer:BusinessRecord)=>{const account=accounts.find(row=>row.id===customer.id);setForm({customerId:customer.id,version:account?.version??0,limit:account?(Number(account.data.limitMinor)/100).toFixed(2):'0.00',terms:String(account?.data.termsDays??30),status:account?.data.status==='HOLD'?'HOLD':account?.data.status==='CLOSED'?'CLOSED':'ACTIVE',notes:String(account?.data.notes||'')});setReason('');setMessage('')};
 const save=async(event:React.FormEvent)=>{event.preventDefault();if(!form||!manage||blocked||inFlight.current)return;inFlight.current=true;setBusy(true);setMessage('');try{
  const limitMinor=parseMoneyToMinor(form.limit),termsDays=Number(form.terms);if(!Number.isSafeInteger(termsDays)||termsDays<0||termsDays>365)throw new Error('Credit terms must be a whole number from 0 to 365 days.');if(reason.trim().length<3)throw new Error('Enter a change reason of at least 3 characters.');
  const outcome=await command('customerCredit.configure','customerCreditAccounts',form.customerId,{id:form.customerId,customerId:form.customerId,limitMinor,termsDays,status:form.status,notes:form.notes,reason:reason.trim(),expectedVersions:[{collection:'customerCreditAccounts',id:form.customerId,version:form.version}]});
  if(outcome.kind==='CONFIRMED'){setForm(null);setMessage('Credit account terms saved and confirmed.');}
  else{if(outcome.kind==='PENDING'||outcome.kind==='OUTCOME_UNKNOWN')setPendingId(outcome.commandId);setMessage('message' in outcome?outcome.message:'Recover the original account change in Activity before retrying.');}
 }catch(error){setMessage(operatorError(error));}finally{inFlight.current=false;setBusy(false)}};
 const writeOff=async(event:React.FormEvent)=>{event.preventDefault();if(!writeOffCustomer||blocked||inFlight.current||!allowed(session,'credit.write_off')&&!writeOffApprovalToken.trim())return;inFlight.current=true;setBusy(true);setMessage('');try{
  const account=accounts.find(row=>row.id===writeOffCustomer);if(!account)throw new Error('Refresh the customer account before writing off receivables.');
  const amountMinor=parseMoneyToMinor(writeOffAmount);if(amountMinor<=0||amountMinor>Number(account.data.balanceMinor))throw new Error('Enter a positive amount no greater than the current outstanding balance.');
  if(writeOffReason.trim().length<3)throw new Error('Enter a write-off reason of at least 3 characters.');if(!writeOffConfirmed)throw new Error('Confirm this write-off is an accounts-receivable adjustment, not a cash payment.');
  const payload={id:crypto.randomUUID(),customerId:writeOffCustomer,amountMinor,reason:writeOffReason.trim(),...(writeOffApprovalToken.trim()?{approvalToken:writeOffApprovalToken.trim()}:{}),expectedVersions:[{collection:'customerCreditAccounts',id:account.id,version:account.version}]};
  const outcome=await command('credit.writeOff','customerCreditEntries',payload.id,payload);
  if(outcome.kind==='CONFIRMED'){setWriteOffCustomer('');if(statementCustomer===writeOffCustomer)void loadStatement(writeOffCustomer);setMessage('Receivable write-off and notice recorded. No cash was paid.');}
  else{if(outcome.kind==='PENDING'||outcome.kind==='OUTCOME_UNKNOWN')setPendingId(outcome.commandId);setMessage('message' in outcome?outcome.message:'Recover the original write-off command in Activity before retrying.');}
 }catch(error){setMessage(operatorError(error));}finally{inFlight.current=false;setBusy(false)}};
 const reverse=async(event:React.FormEvent)=>{event.preventDefault();if(!reverseEntryId||blocked||inFlight.current||!allowed(session,'credit.write_off')&&!reverseApprovalToken.trim())return;inFlight.current=true;setBusy(true);setMessage('');try{
  const source=records.find(row=>row.collection==='customerCreditEntries'&&row.id===reverseEntryId),account=source&&accounts.find(row=>row.id===source.data.customerId);if(!source||!account)throw new Error('Refresh the customer statement and account before reversing this entry.');
  if(reverseReason.trim().length<3)throw new Error('Enter a reversal reason of at least 3 characters.');
  const expectedVersions:Record<string,unknown>[]= [{collection:'customerCreditEntries',id:source.id,version:source.version},{collection:'customerCreditAccounts',id:account.id,version:account.version}];
  const payload:Record<string,unknown>={id:crypto.randomUUID(),customerId:account.id,entryId:source.id,reason:reverseReason.trim(),expectedVersions};
  if(reverseApprovalToken.trim())payload.approvalToken=reverseApprovalToken.trim();
  if(source.data.kind==='CHARGE'){
   const order=records.find(row=>row.collection==='orders'&&row.id===source.data.orderId);if(!order)throw new Error('The charged order is not loaded. Reopen the account statement before reversing this charge.');
   expectedVersions.push({collection:'orders',id:order.id,version:order.version});
  }else if(source.data.kind==='SETTLEMENT'&&source.data.paymentMethod==='CASH'){
   const till=openTills.find(row=>row.id===reverseTill);if(!till)throw new Error('Choose an open till paying out the cash refund.');
   if(!reverseConfirmed)throw new Error('Confirm that the cash refund was physically paid.');
   payload.tillSessionId=till.id;payload.cashReturnedConfirmed=true;expectedVersions.push({collection:'tillSessions',id:till.id,version:till.version});
  }else if(source.data.kind==='SETTLEMENT'){
   if(!reverseConfirmed||!reverseExternalReference.trim())throw new Error('Confirm the external refund manually and enter its return reference.');
   payload.manuallyConfirmed=true;payload.externalReference=reverseExternalReference.trim();
  }
  const outcome=await command('credit.reverse','customerCreditEntries',String(payload.id),payload);
  if(outcome.kind==='CONFIRMED'){setReverseEntryId('');if(statementCustomer===String(source.data.customerId))void loadStatement(statementCustomer);setMessage('Credit entry reversal and immutable notice recorded. Verify any external refund delivery independently.');}
  else{if(outcome.kind==='PENDING'||outcome.kind==='OUTCOME_UNKNOWN')setPendingId(outcome.commandId);setMessage('message' in outcome?outcome.message:'Recover the original reversal command in Activity before retrying.');}
 }catch(error){setMessage(operatorError(error));}finally{inFlight.current=false;setBusy(false)}};
 const settle=async(event:React.FormEvent)=>{event.preventDefault();if(!settlementCustomer||blocked||inFlight.current||!allowed(session,'credit.settle'))return;inFlight.current=true;setBusy(true);setMessage('');try{
  const account=accounts.find(row=>row.id===settlementCustomer),tender=paymentAccounts.find(row=>row.id===settlementAccount);if(!account||!tender)throw new Error('Refresh and choose the current customer account and payment account.');
  const amountMinor=parseMoneyToMinor(settlementAmount);if(amountMinor<=0||amountMinor>Number(account.data.balanceMinor))throw new Error('Enter a positive amount no greater than the current customer balance.');
  if(settlementReason.trim().length>500)throw new Error('Settlement notes must be 500 characters or fewer.');
  const expectedVersions:Record<string,unknown>[]= [{collection:'customerCreditAccounts',id:account.id,version:account.version},{collection:'paymentAccounts',id:tender.id,version:tender.version}];
  const payload:Record<string,unknown>={id:crypto.randomUUID(),customerId:settlementCustomer,accountId:tender.id,amountMinor,reason:settlementReason.trim(),expectedVersions};
  if(tender.data.method==='CASH'){
   const till=openTills.find(row=>row.id===settlementTill);if(!till)throw new Error('Choose an open till receiving the exact cash amount.');
   if(!settlementConfirmed)throw new Error('Confirm that the exact cash amount was physically received.');
   payload.tillSessionId=till.id;payload.cashReceivedConfirmed=true;expectedVersions.push({collection:'tillSessions',id:till.id,version:till.version});
  }else{
   if(!settlementConfirmed)throw new Error('Confirm that you manually verified the external funds were received.');
   if(!settlementReference.trim())throw new Error('Enter the card approval or M-Pesa transaction reference.');
   if(tender.data.method==='MPESA'&&!allowed(session,'mpesa.record'))throw new Error('Your API staff account cannot record M-Pesa receipts.');
   const receivedAt=new Date(settlementReceivedAt);if(!Number.isFinite(receivedAt.getTime()))throw new Error('Enter the actual external receipt time.');
   payload.manuallyConfirmed=true;payload.reference=settlementReference.trim();payload.receivedAmountMinor=amountMinor;payload.receivedAt=receivedAt.toISOString();
  }
  const outcome=await command('credit.settle','customerCreditEntries',String(payload.id),payload);
  if(outcome.kind==='CONFIRMED'){setSettlementCustomer('');if(statementCustomer===settlementCustomer)void loadStatement(settlementCustomer);setMessage('Customer settlement recorded. Payment acknowledgement is available in the document queue. The transfer itself was not initiated by ServOS.');}
  else{if(outcome.kind==='PENDING'||outcome.kind==='OUTCOME_UNKNOWN')setPendingId(outcome.commandId);setMessage('message' in outcome?outcome.message:'Recover the original settlement command in Activity before retrying.');}
 }catch(error){setMessage(operatorError(error));}finally{inFlight.current=false;setBusy(false)}};
 const reconcileStatement=async(event:React.FormEvent)=>{event.preventDefault();if(!reconcileCustomer||!reconcileId||blocked||inFlight.current||!allowed(session,'credit.reconcile'))return;inFlight.current=true;setBusy(true);setMessage('');try{
  const account=accounts.find(row=>row.id===reconcileCustomer);if(!account)throw new Error('Refresh the customer account before reconciling its statement.');
  const amountMinor=parseMoneyToMinor(statementBalance);if(amountMinor<0)throw new Error('Statement balance cannot be negative.');if(!statementReference.trim())throw new Error('Enter the statement or review reference.');if(reconcileNotes.trim().length<3)throw new Error('Enter reconciliation notes of at least 3 characters.');
  const expectedVersions=[{collection:'customerCreditReconciliations',id:reconcileId,version:0},{collection:'customerCreditAccounts',id:account.id,version:account.version}];
  const outcome=await command('credit.reconcile','customerCreditReconciliations',reconcileId,{id:reconcileId,customerId:account.id,statementBalanceMinor:amountMinor,statementReference:statementReference.trim(),notes:reconcileNotes.trim(),expectedVersions});
  if(outcome.kind==='CONFIRMED'){setReconcileCustomer('');setMessage('Statement comparison recorded. Any variance is an exception; the customer ledger was not changed.');}
  else{if(outcome.kind==='PENDING'||outcome.kind==='OUTCOME_UNKNOWN')setPendingId(outcome.commandId);setMessage('message' in outcome?outcome.message:'Recover the original reconciliation command in Activity before submitting another.');}
 }catch(error){setMessage(operatorError(error));}finally{inFlight.current=false;setBusy(false)}};
 const resolveCreditDiscrepancy=async(event:React.FormEvent)=>{event.preventDefault();if(!resolveDiscrepancy||blocked||inFlight.current||!allowed(session,'credit.reconcile'))return;inFlight.current=true;setBusy(true);setMessage('');try{
  const discrepancy=discrepancies.find(row=>row.id===resolveDiscrepancy);if(!discrepancy||discrepancy.data.status!=='OPEN')throw new Error('Refresh the open discrepancy before resolving it.');if(resolutionNote.trim().length<3)throw new Error('Enter a resolution note of at least 3 characters.');
  const outcome=await command('credit.discrepancy.resolve','customerCreditDiscrepancies',discrepancy.id,{id:discrepancy.id,discrepancyId:discrepancy.id,outcome:resolutionOutcome,resolution:resolutionNote.trim(),expectedVersions:[{collection:'customerCreditDiscrepancies',id:discrepancy.id,version:discrepancy.version}]});
  if(outcome.kind==='CONFIRMED'){setResolveDiscrepancy('');setResolutionNote('');setMessage('Discrepancy resolution evidence recorded. No ledger amount was changed.');}
  else{if(outcome.kind==='PENDING'||outcome.kind==='OUTCOME_UNKNOWN')setPendingId(outcome.commandId);setMessage('message' in outcome?outcome.message:'Recover the original discrepancy-resolution command in Activity before retrying.');}
 }catch(error){setMessage(operatorError(error));}finally{inFlight.current=false;setBusy(false)}};
 return <section className="space-y-4" aria-label="API customer credit accounts">
  <h2 className="text-xl font-bold">Customer credit accounts</h2>
  <p className="text-sm text-slate-400">Configure named-account limits, review statements and record manually confirmed customer settlements. ServOS does not initiate bank, card or M-Pesa transfers.</p>
  {unresolved&&<p role="status">Recover the original customer-credit command in Activity before making another change.</p>}
  {!customers.length&&<p className="text-sm text-slate-400">Add a named customer in Master Data before configuring credit terms.</p>}
  <div className="grid gap-3 md:grid-cols-2">{customers.map(customer=>{const account=accounts.find(row=>row.id===customer.id),aging=account?.data.aging as Record<string,unknown>|undefined;return <article key={customer.id} className="space-y-2 rounded-xl border border-slate-700 p-4">
   <div className="flex items-start justify-between gap-3"><h3 className="font-bold">{String(customer.data.name)}</h3><span className="text-xs text-slate-400">{account?String(account.data.status):'No credit terms'}</span></div>
   <p className="text-sm text-slate-400">{account?`${money(account.data.limitMinor)} limit · ${Number(account.data.termsDays)} day terms · ${money(account.data.balanceMinor)} outstanding`:'Credit not configured'}</p>
   {account&&aging&&<p className="text-xs text-slate-400">Current {money(aging.currentMinor)} · 1–30 days {money(aging.days1To30Minor)} · 31–60 {money(aging.days31To60Minor)} · 61–90 {money(aging.days61To90Minor)} · over 90 {money(aging.over90DaysMinor)}{aging.reconciled!==true&&<span className="ml-2 font-semibold text-amber-300">Aging needs reconciliation</span>}</p>}
   <div className="flex flex-wrap gap-2">{account&&<button className={button} onClick={()=>openStatement(customer.id)}>{statementCustomer===customer.id?'Hide statement':'View statement'}</button>}{account&&allowed(session,'credit.reconcile')&&<button disabled={blocked} className={button} onClick={()=>{setReconcileCustomer(customer.id);setReconcileId(crypto.randomUUID());setStatementBalance((Number(account.data.balanceMinor)/100).toFixed(2));setStatementReference('');setReconcileNotes('');setMessage('')}}>Reconcile statement</button>}{manage&&<button disabled={blocked} className={button} onClick={()=>open(customer)}>{account?'Review terms':'Configure account'}</button>}{account&&allowed(session,'credit.settle')&&Number(account.data.balanceMinor)>0&&<button disabled={blocked} className={button} onClick={()=>{setSettlementCustomer(customer.id);setSettlementAmount((Number(account.data.balanceMinor)/100).toFixed(2));setSettlementAccount('');setSettlementConfirmed(false);setSettlementReason('');setMessage('')}}>Receive payment</button>}{account&&(allowed(session,'credit.write_off')||manage)&&Number(account.data.balanceMinor)>0&&<button disabled={blocked} className={button} onClick={()=>{setWriteOffCustomer(customer.id);setWriteOffAmount((Number(account.data.balanceMinor)/100).toFixed(2));setWriteOffReason('');setWriteOffConfirmed(false);setWriteOffApprovalToken('');setMessage('')}}>Review write-off</button>}</div>
  </article>})}</div>
  {reconcileCustomer&&<form role="dialog" aria-label="Reconcile customer credit statement" onSubmit={event=>void reconcileStatement(event)} className="space-y-3 rounded-xl border border-amber-700 p-4"><h3 className="font-semibold">Reconcile {String(customers.find(row=>row.id===reconcileCustomer)?.data.name||'customer')} statement</h3><p className="text-sm text-slate-300">Current API ledger balance: {money(accounts.find(row=>row.id===reconcileCustomer)?.data.balanceMinor)}. Recording a comparison never changes the ledger; a difference opens an exception.</p><label className="block text-sm">Statement balance (KES)<input required type="number" min="0" step="0.01" disabled={blocked} className={input} value={statementBalance} onChange={event=>setStatementBalance(event.target.value)}/></label><label className="block text-sm">Statement / review reference<input required maxLength={160} disabled={blocked} className={input} value={statementReference} onChange={event=>setStatementReference(event.target.value)}/></label><label className="block text-sm">Reconciliation notes<textarea required minLength={3} maxLength={500} disabled={blocked} className={input} value={reconcileNotes} onChange={event=>setReconcileNotes(event.target.value)}/></label><button disabled={blocked||!statementReference.trim()||reconcileNotes.trim().length<3} className="rounded bg-amber-400 px-4 py-2 font-bold text-slate-950 disabled:opacity-40">Record comparison</button><button type="button" disabled={busy} className={`${button} ml-2`} onClick={()=>setReconcileCustomer('')}>Cancel</button></form>}
  {discrepancies.some(row=>row.data.status==='OPEN')&&<section className="space-y-2 rounded-xl border border-amber-800/60 p-4"><h3 className="font-semibold">Open credit discrepancies</h3>{discrepancies.filter(row=>row.data.status==='OPEN').map(row=><article key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded border border-slate-700 p-3"><div><b>{String(customers.find(customer=>customer.id===row.data.customerId)?.data.name||row.data.customerId)}</b><p className="text-sm text-amber-200">Statement variance {money(row.data.varianceMinor)} · {String(row.data.statementReference||'')}</p></div>{allowed(session,'credit.reconcile')&&<button disabled={blocked} className={button} onClick={()=>{setResolveDiscrepancy(row.id);setResolutionOutcome('STATEMENT_ERROR');setResolutionNote('')}}>Review resolution</button>}</article>)}</section>}
  {reconciliations.length>0&&<details className="rounded-xl border border-slate-700 p-4"><summary className="cursor-pointer font-semibold">Statement reconciliation history ({reconciliations.length})</summary><div className="mt-3 space-y-2">{reconciliations.slice().sort((a,b)=>String(b.data.reconciledAt).localeCompare(String(a.data.reconciledAt))).map(row=><p key={row.id} className="text-sm">{String(customers.find(customer=>customer.id===row.data.customerId)?.data.name||row.data.customerId)} · {String(row.data.status)} · ledger {money(row.data.ledgerBalanceMinor)} / statement {money(row.data.statementBalanceMinor)} · {String(row.data.statementReference)}</p>)}</div></details>}
  {resolveDiscrepancy&&<form role="dialog" aria-label="Resolve customer credit discrepancy" onSubmit={event=>void resolveCreditDiscrepancy(event)} className="space-y-3 rounded-xl border border-amber-700 p-4"><h3 className="font-semibold">Resolve statement discrepancy</h3><p className="text-sm text-slate-300">This appends the review outcome. It does not post a payment, charge, or ledger correction.</p><label className="block text-sm">Resolution outcome<select disabled={blocked} className={input} value={resolutionOutcome} onChange={event=>setResolutionOutcome(event.target.value)}><option value="STATEMENT_ERROR">Statement error</option><option value="MISSING_PAYMENT">Missing payment</option><option value="MISSING_CHARGE">Missing charge</option><option value="ACCEPTED_VARIANCE" disabled={!allowed(session,'credit.manage')&&!allowed(session,'credit.write_off')}>Accepted variance (manager)</option><option value="WRITE_OFF_REQUIRED" disabled={!allowed(session,'credit.manage')&&!allowed(session,'credit.write_off')}>Write-off required (manager)</option></select></label><label className="block text-sm">Resolution notes<textarea required minLength={3} maxLength={500} disabled={blocked} className={input} value={resolutionNote} onChange={event=>setResolutionNote(event.target.value)}/></label><button disabled={blocked||resolutionNote.trim().length<3} className="rounded bg-amber-400 px-4 py-2 font-bold text-slate-950 disabled:opacity-40">Record resolution</button><button type="button" disabled={busy} className={`${button} ml-2`} onClick={()=>setResolveDiscrepancy('')}>Cancel</button></form>}
  {statementCustomer&&<section className="space-y-2 rounded-xl border border-slate-700 p-4">
   <h3 className="font-semibold">{String(customers.find(row=>row.id===statementCustomer)?.data.name||'Customer')} credit statement</h3>
   <div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-slate-400">Read-only statement, loaded from the API in stable pages. Ledger balances are calculated against the same statement snapshot.</p><button type="button" disabled={statementLoading} className={button} onClick={()=>void loadStatement(statementCustomer)}>Refresh latest</button></div>
   {statementError&&<p role="alert" className="text-sm text-rose-300">{statementError}</p>}
   <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="p-2">Date</th><th className="p-2">Type</th><th className="p-2">Reference</th><th className="p-2 text-right">Change</th><th className="p-2 text-right">Balance</th></tr></thead><tbody>{entries.map(row=><tr key={row.id} className="border-t border-slate-800"><td className="p-2">{new Date(String(row.data.occurredAt)).toLocaleString()}</td><td className="p-2">{String(row.data.kind)}</td><td className="p-2">{String(row.data.reference||row.data.orderId||'—')}</td><td className="p-2 text-right">{Number(row.data.balanceDeltaMinor)>0?'+':''}{money(row.data.balanceDeltaMinor)}</td><td className="p-2 text-right">{money(row.data.balanceAfterMinor)}</td></tr>)}</tbody></table></div>
   {!entries.length&&!statementLoading&&<p className="text-sm text-slate-400">No credit ledger entries.</p>}
   {statementLoading&&<p role="status" className="text-sm text-slate-400">Loading statement entries…</p>}
   {statementHasMore&&<button type="button" disabled={statementLoading||!statementCursor} className={button} onClick={()=>{if(statementCursor)void loadStatement(statementCustomer,statementCursor,true)}}>Load older entries</button>}
  {(allowed(session,'credit.write_off')||allowed(session,'credit.manage'))&&<div className="flex flex-wrap gap-2">{entries.filter(row=>['CHARGE','SETTLEMENT','WRITE_OFF'].includes(String(row.data.kind))&&!entries.some(reversal=>reversal.data.reversesEntryId===row.id)).map(row=><button key={row.id} type="button" disabled={blocked} className={button} onClick={()=>{setReverseEntryId(row.id);setReverseReason('');setReverseTill('');setReverseConfirmed(false);setReverseExternalReference('');setReverseApprovalToken('');setMessage('')}}>Reverse {String(row.data.kind).toLowerCase()} · {money(row.data.amountMinor)}</button>)}</div>}
  </section>}
  {reverseEntryId&&<form role="dialog" aria-label="Review customer credit reversal" onSubmit={event=>void reverse(event)} className="space-y-3 rounded-xl border border-red-800 p-4">
   {(()=>{const source=entries.find(row=>row.id===reverseEntryId);return <><h3 className="font-semibold">Reverse {String(source?.data.kind||'credit entry')} for {String(customers.find(row=>row.id===source?.data.customerId)?.data.name||'customer')}</h3><p className="text-sm">Original amount: <b>{money(source?.data.amountMinor)}</b></p><p className="text-sm text-amber-200">The original journal will be exactly reversed. Settlement refunds require evidence of returned funds; ServOS does not initiate external transfers.</p>{!allowed(session,'credit.write_off')&&<label className="block text-sm">Single-use manager approval token<input required autoComplete="off" disabled={blocked} className={input} value={reverseApprovalToken} onChange={event=>setReverseApprovalToken(event.target.value)}/></label>}{source?.data.kind==='SETTLEMENT'&&source.data.paymentMethod==='CASH'?<><label className="block text-sm">Paying open till<select required disabled={blocked} className={input} value={reverseTill} onChange={event=>setReverseTill(event.target.value)}><option value="">Choose open till</option>{openTills.map(row=><option key={row.id} value={row.id}>{String(row.data.id)} · {String(row.data.operatorId)}</option>)}</select></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" disabled={blocked} checked={reverseConfirmed} onChange={event=>setReverseConfirmed(event.target.checked)}/>I physically returned this exact cash amount to the customer.</label></>:source?.data.kind==='SETTLEMENT'?<><label className="block text-sm">External refund reference<input required maxLength={160} disabled={blocked} className={input} value={reverseExternalReference} onChange={event=>setReverseExternalReference(event.target.value)}/></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" disabled={blocked} checked={reverseConfirmed} onChange={event=>setReverseConfirmed(event.target.checked)}/>I manually verified that the external refund was returned.</label></>:null}<label className="block text-sm">Reversal reason<textarea required minLength={3} maxLength={500} disabled={blocked} className={input} value={reverseReason} onChange={event=>setReverseReason(event.target.value)}/></label><button disabled={blocked||reverseReason.trim().length<3||(source?.data.kind==='SETTLEMENT'&&!reverseConfirmed)||!allowed(session,'credit.write_off')&&!reverseApprovalToken.trim()} className="rounded bg-red-700 px-4 py-2 font-bold text-white disabled:opacity-40">Record exact reversal</button><button type="button" disabled={busy} className={`${button} ml-2`} onClick={()=>{setReverseApprovalToken('');setReverseEntryId('')}}>Cancel</button></>})()}
  </form>}
  {settlementCustomer&&<form role="dialog" aria-label="Review customer credit settlement" onSubmit={event=>void settle(event)} className="space-y-3 rounded-xl border border-amber-700 p-4">
   <h3 className="font-semibold">Record payment for {String(customers.find(row=>row.id===settlementCustomer)?.data.name||'customer')}</h3>
   <p className="text-sm text-slate-300">Outstanding balance: {money(accounts.find(row=>row.id===settlementCustomer)?.data.balanceMinor)}. Confirm money already received before recording it.</p>
   <label className="block text-sm">Amount received (KES)<input required inputMode="decimal" type="number" min="0.01" step="0.01" disabled={blocked} className={input} value={settlementAmount} onChange={event=>setSettlementAmount(event.target.value)}/></label>
   <label className="block text-sm">Payment account<select required disabled={blocked} className={input} value={settlementAccount} onChange={event=>{setSettlementAccount(event.target.value);setSettlementConfirmed(false)}}><option value="">Choose account</option>{paymentAccounts.map(row=><option key={row.id} value={row.id}>{String(row.data.name)} · {String(row.data.method)}</option>)}</select></label>
   {paymentAccounts.find(row=>row.id===settlementAccount)?.data.method==='CASH'?<>
    <label className="block text-sm">Receiving open till<select required disabled={blocked} className={input} value={settlementTill} onChange={event=>setSettlementTill(event.target.value)}><option value="">Choose open till</option>{openTills.map(row=><option key={row.id} value={row.id}>{String(row.data.id)} · {String(row.data.operatorId)}</option>)}</select></label>
    <label className="flex items-start gap-2 text-sm"><input type="checkbox" disabled={blocked} checked={settlementConfirmed} onChange={event=>setSettlementConfirmed(event.target.checked)}/>I counted and physically received this exact cash amount.</label>
   </>:settlementAccount&&<>
    <label className="block text-sm">External approval / M-Pesa reference<input required maxLength={160} disabled={blocked} className={input} value={settlementReference} onChange={event=>setSettlementReference(event.target.value)}/></label>
    <label className="block text-sm">Actual receipt time<input required type="datetime-local" disabled={blocked} className={input} value={settlementReceivedAt} onChange={event=>setSettlementReceivedAt(event.target.value)}/></label>
    <label className="flex items-start gap-2 text-sm"><input type="checkbox" disabled={blocked} checked={settlementConfirmed} onChange={event=>setSettlementConfirmed(event.target.checked)}/>I manually checked the business account/card approval and confirmed these funds were received.</label>
   </>}
   <label className="block text-sm">Settlement note (optional)<textarea maxLength={500} disabled={blocked} className={input} value={settlementReason} onChange={event=>setSettlementReason(event.target.value)}/></label>
   <button disabled={blocked||!settlementAccount||!settlementConfirmed} className="rounded bg-amber-400 px-4 py-2 font-bold text-slate-950 disabled:opacity-40">Record confirmed settlement</button><button type="button" disabled={busy} className={`${button} ml-2`} onClick={()=>setSettlementCustomer('')}>Cancel</button>
  </form>}
  {writeOffCustomer&&<form role="dialog" aria-label="Review customer credit write-off" onSubmit={event=>void writeOff(event)} className="space-y-3 rounded-xl border border-red-800 p-4">
   <h3 className="font-semibold">Write off {String(customers.find(row=>row.id===writeOffCustomer)?.data.name||'customer')} receivable</h3>
   <p className="text-sm text-amber-200">This reduces accounts receivable and posts bad-debt expense. It does not record or issue money to the customer.</p>
   <label className="block text-sm">Amount (KES)<input required inputMode="decimal" type="number" min="0.01" step="0.01" disabled={blocked} className={input} value={writeOffAmount} onChange={event=>setWriteOffAmount(event.target.value)}/></label>
   <label className="block text-sm">Write-off reason<textarea required minLength={3} maxLength={500} disabled={blocked} className={input} value={writeOffReason} onChange={event=>setWriteOffReason(event.target.value)}/></label>
   {!allowed(session,'credit.write_off')&&<label className="block text-sm">Single-use manager approval token<input required autoComplete="off" disabled={blocked} className={input} value={writeOffApprovalToken} onChange={event=>setWriteOffApprovalToken(event.target.value)}/></label>}
   <label className="flex items-start gap-2 text-sm"><input type="checkbox" disabled={blocked} checked={writeOffConfirmed} onChange={event=>setWriteOffConfirmed(event.target.checked)}/>I reviewed the bad-debt adjustment and confirm no cash refund or payment is being recorded.</label>
   <button disabled={blocked||!writeOffConfirmed||writeOffReason.trim().length<3||!allowed(session,'credit.write_off')&&!writeOffApprovalToken.trim()} className="rounded bg-red-700 px-4 py-2 font-bold text-white disabled:opacity-40">Confirm write-off</button><button type="button" disabled={busy} className={`${button} ml-2`} onClick={()=>{setWriteOffApprovalToken('');setWriteOffCustomer('')}}>Cancel</button>
  </form>}
  {form&&<form role="dialog" aria-label="Customer credit terms" onSubmit={event=>void save(event)} className="space-y-3 rounded-xl border border-slate-700 p-4">
   <h3 className="font-semibold">{form.version?'Review credit terms':'Configure named customer credit'}</h3>
   <label className="block text-sm">Credit limit (KES)<input required inputMode="decimal" type="number" min="0" step="0.01" disabled={blocked} className={input} value={form.limit} onChange={event=>setForm({...form,limit:event.target.value})}/></label>
   <div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm">Payment terms (days)<input required type="number" min="0" max="365" step="1" disabled={blocked} className={input} value={form.terms} onChange={event=>setForm({...form,terms:event.target.value})}/></label><label className="block text-sm">Account status<select disabled={blocked} className={input} value={form.status} onChange={event=>setForm({...form,status:event.target.value as Form['status']})}><option value="ACTIVE">Active</option><option value="HOLD">Hold new charges</option><option value="CLOSED">Closed</option></select></label></div>
   {form.status==='CLOSED'&&<p className="text-xs text-amber-200">Closing is allowed only when the API ledger balance is zero.</p>}
   <label className="block text-sm">Notes<textarea maxLength={1000} disabled={blocked} className={input} value={form.notes} onChange={event=>setForm({...form,notes:event.target.value})}/></label>
   <label className="block text-sm">Change reason<textarea required minLength={3} maxLength={500} disabled={blocked} className={input} value={reason} onChange={event=>setReason(event.target.value)}/></label>
   <button disabled={blocked||reason.trim().length<3} className="rounded bg-amber-400 px-4 py-2 font-bold text-slate-950 disabled:opacity-40">Save terms</button><button type="button" disabled={busy} className={`${button} ml-2`} onClick={()=>setForm(null)}>Close</button>
  </form>}
  {message&&<p role="status" className="text-sm text-amber-200">{message}</p>}
 </section>;
}
