import React,{useCallback,useEffect,useState} from 'react';
import type {createServOSApiClient,ApiStaffSession} from './apiClient';
import {WebActionDialog} from './WebActionDialog';

type ApiClient=ReturnType<typeof createServOSApiClient>;
const button='rounded-lg border border-slate-600 px-3 py-2 text-sm font-semibold text-slate-200 hover:bg-slate-800 disabled:opacity-40';
const time=(value:string)=>new Date(value).toLocaleString();

export function WebApiSessions({client,currentSessionId,onClose}:{client:ApiClient;currentSessionId:string;onClose:()=>void}){
 const [sessions,setSessions]=useState<ApiStaffSession[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [revokeTarget,setRevokeTarget]=useState<ApiStaffSession|null>(null);
 const refresh=useCallback(async()=>{setLoading(true);setError('');try{const result=await client.staffSessions();setSessions(result.sessions)}catch(e){setError(e instanceof Error?e.message:'Sign-in sessions could not be loaded.')}finally{setLoading(false)}},[client]);
 useEffect(()=>{void refresh()},[refresh]);
 const revoke=async(session:ApiStaffSession)=>{if(session.current||session.revokedAt||session.expired||busy)return;setError('');setNotice('');setRevokeTarget(session)};
 const confirmRevoke=async()=>{if(!revokeTarget)return;setBusy(revokeTarget.sessionId);setError('');setNotice('');try{await client.revokeStaffSession(revokeTarget.sessionId);setNotice('Session revoked.');await refresh()}catch(e){const message=e instanceof Error?e.message:'The session could not be revoked.';setError(message);throw e instanceof Error?e:new Error(message)}finally{setBusy('')}};
 return revokeTarget?<WebActionDialog title="Revoke sign-in session?" description="The selected browser will need to sign in again. Confirm before revoking its access." fields={[]} confirmLabel="Revoke session" danger onClose={()=>setRevokeTarget(null)} onConfirm={confirmRevoke}/>:<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-3" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><section role="dialog" aria-modal="true" aria-labelledby="api-session-title" className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-2xl border border-slate-700 bg-slate-950 p-5 text-slate-100 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><h2 id="api-session-title" className="text-lg font-bold">Your sign-in sessions</h2><p className="mt-1 text-sm text-slate-400">Review access for this staff account. Revoking a session signs that browser out.</p></div><button type="button" className={button} onClick={onClose}>Close</button></div>{error&&<p role="alert" className="mt-4 rounded-lg border border-rose-800 p-3 text-sm text-rose-200">{error}</p>}{notice&&<p role="status" className="mt-4 rounded-lg border border-emerald-800 p-3 text-sm text-emerald-200">{notice}</p>}{loading?<p className="py-6 text-sm text-slate-400">Loading sessions…</p>:<div className="mt-4 space-y-2">{sessions.map(session=>{const current=session.sessionId===currentSessionId||session.current;const state=session.revokedAt?'Revoked':session.expired?'Expired':session.deviceRevoked?'Device revoked':current?'This session':'Active';return <article key={session.sessionId} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-800 p-3"><div className="min-w-0"><p className="font-semibold">{current?'This browser':session.deviceId?`Device ${session.deviceId}`:'Unenrolled sign-in'} · {state}</p><p className="mt-1 text-xs text-slate-400">Signed in {time(session.createdAt)} · expires {time(session.expiresAt)}</p>{session.revokedAt&&<p className="text-xs text-slate-500">Revoked {time(session.revokedAt)}</p>}</div>{!current&&!session.revokedAt&&!session.expired&&<button type="button" className={button} disabled={!!busy} onClick={()=>void revoke(session)}>{busy===session.sessionId?'Revoking…':'Revoke session'}</button>}</article>})}{!sessions.length&&<p className="py-5 text-sm text-slate-400">No sign-in sessions are available.</p>}</div>}<div className="mt-5 flex justify-end"><button type="button" className={button} disabled={loading} onClick={()=>void refresh()}>Refresh</button></div></section></div>;
}
