import {WebDocumentQueue} from './WebDocumentQueue';
import type {ApiAuthenticatedDeviceSession} from './apiAuth';
import React,{useEffect,useRef,useState} from 'react';
import {allowed,type BusinessRecord,type WebSession} from './session';
import type {QueuedCommand} from './BusinessStore';
import type {CommandOutcome} from '../../types/transactions';
import {parseMoneyToMinor} from '../../utils/fiscal';
const input='mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2';
const button='rounded border border-slate-600 px-3 py-2 disabled:opacity-40';
type Review={id:string;payable:BusinessRecord;accounts:BusinessRecord[]};
export function WebApiSupplierPayments({records,session,queue,disabled,command,apiAuth,readRecords}:{apiAuth:ApiAuthenticatedDeviceSession;readRecords:()=>Promise<BusinessRecord[]>;records:BusinessRecord[];session:WebSession;queue:QueuedCommand[];disabled:boolean;command:(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<CommandOutcome>}){
 const [review,setReview]=useState<Review|null>(null),[accountId,setAccountId]=useState(''),[amount,setAmount]=useState(''),[reference,setReference]=useState(''),[paidAt,setPaidAt]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[pettyCash,setPettyCash]=useState(false),[busy,setBusy]=useState(false),[pending,setPending]=useState(''),[message,setMessage]=useState('');const inFlight=useRef(false);const [documentId,setDocumentId]=useState('');
 const unresolved=queue.some(row=>(row.command.operation.startsWith('procurement.')||row.command.operation.startsWith('supplierPayable.')||row.command.operation.startsWith('supplierReturn.'))&&['PENDING_SYNC','OUTCOME_UNKNOWN'].includes(row.state)),blocked=disabled||busy||unresolved||Boolean(pending),canPay=allowed(session,'procurement.pay');
 const account=review?.accounts.find(row=>row.id===accountId);
 useEffect(()=>{if(!pending)return;const entry=queue.find(row=>row.id===pending);if(!entry||!['SYNCHRONIZED','REJECTED','CONFLICT'].includes(entry.state))return;setPending('');setReview(null);setMessage(entry.state==='SYNCHRONIZED'?'Original supplier payment confirmed.':entry.result?.error?.message||'Review the latest payable before another payment.');},[queue,pending]);
 const open=(payable:BusinessRecord)=>{setReview({id:crypto.randomUUID(),payable,accounts:records.filter(row=>row.collection==='paymentAccounts'&&!row.archived&&['CASH','BANK','MPESA'].includes(String(row.data.method)))});setAccountId('');setAmount('');setReference('');setPaidAt('');setReason('');setConfirmed(false);setPettyCash(false);setMessage('');};
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!review||!account||blocked||inFlight.current||!canPay||!confirmed)return;inFlight.current=true;setBusy(true);setMessage('');try{
  const amountMinor=parseMoneyToMinor(amount),when=new Date(paidAt);if(amountMinor<=0||amountMinor>Number(review.payable.data.outstandingMinor))throw new Error('Enter a positive amount within the reviewed outstanding balance.');if(!paidAt||!Number.isFinite(when.getTime())||when.getTime()>Date.now())throw new Error('Enter the actual payment time, not a future time.');if(account.data.method==='CASH'&&!pettyCash)throw new Error('Confirm cash was paid from petty cash outside the POS till.');
  const outcome=await command('supplierPayable.pay','supplierPayments',review.id,{id:review.id,payableId:review.payable.id,accountId:account.id,amountMinor,reference:reference.trim(),paidAt:when.toISOString(),reason:reason.trim(),confirmed:true,cashOutsidePosTill:pettyCash,expectedVersions:[{collection:'supplierPayments',id:review.id,version:0},{collection:'supplierPayables',id:review.payable.id,version:review.payable.version},{collection:'paymentAccounts',id:account.id,version:account.version}]});
  if(outcome.kind==='CONFIRMED'){setReview(null);setMessage('Manually confirmed supplier payment recorded.');}else{if(outcome.kind==='PENDING'||outcome.kind==='OUTCOME_UNKNOWN')setPending(outcome.commandId);setMessage('message' in outcome?outcome.message:'Recover the original supplier payment in Activity.');}
 }catch(error){setMessage(error instanceof Error?error.message:'Cannot record supplier payment.');}finally{inFlight.current=false;setBusy(false);}};
 return <section className="space-y-4" aria-label="Supplier settlement"><h2 className="text-xl font-bold">Record supplier payment</h2><p>Record money already paid. This action does not initiate a bank transfer or M-Pesa payment.</p>{unresolved&&<p role="status">Recover the original procurement action in Activity before recording another payment.</p>}
 {canPay&&records.filter(row=>row.collection==='supplierPayables'&&['MATCHED_UNPAID','PARTIALLY_PAID'].includes(String(row.data.status))).map(row=><button key={row.id} className={button} disabled={blocked} onClick={()=>open(row)}>Record payment for {String(row.data.invoiceNumber)} - KES {(Number(row.data.outstandingMinor)/100).toFixed(2)} outstanding</button>)}
 {review&&<form aria-label="Review supplier payment" onSubmit={event=>void submit(event)} className="space-y-3 rounded border border-slate-700 p-4"><h3 className="font-bold">Invoice {String(review.payable.data.invoiceNumber)}</h3><p>Reviewed outstanding: KES {(Number(review.payable.data.outstandingMinor)/100).toFixed(2)}</p><fieldset disabled={blocked} className="space-y-3"><label className="block">Payment account<select required className={input} value={accountId} onChange={event=>{setAccountId(event.target.value);setPettyCash(false);setConfirmed(false);}}><option value="">Choose account</option>{review.accounts.map(row=><option key={row.id} value={row.id}>{String(row.data.name)} - {String(row.data.method)}</option>)}</select></label>
 <label className="block">Amount paid (KES)<input required inputMode="decimal" className={input} value={amount} onChange={event=>setAmount(event.target.value)}/></label><label className="block">Payment reference<input required maxLength={100} className={input} value={reference} onChange={event=>setReference(event.target.value)}/></label><label className="block">Actual payment time (local time)<input required type="datetime-local" className={input} value={paidAt} onChange={event=>setPaidAt(event.target.value)}/></label><label className="block">Reason<textarea required minLength={3} maxLength={500} className={input} value={reason} onChange={event=>setReason(event.target.value)}/></label>
 {account?.data.method==='CASH'&&<label className="block"><input type="checkbox" checked={pettyCash} onChange={event=>setPettyCash(event.target.checked)}/> This payment used petty cash outside the POS till. Any till withdrawal is a separate reviewed cash movement.</label>}
 <label className="block"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/> I verified the supplier was actually paid this amount through this account, at the stated time and reference.</label><button className={button} disabled={!confirmed||!account||(account.data.method==='CASH'&&!pettyCash)}>Record reviewed payment</button></fieldset><button type="button" className={button} disabled={busy||Boolean(pending)} onClick={()=>setReview(null)}>Close</button></form>}
 {message&&<p role="status">{message}</p>}<h3 className="font-bold">Recorded supplier payments</h3>{records.filter(row=>row.collection==='supplierPayments').map(row=><article key={row.id} className="rounded border border-slate-700 p-3"><p>{String(row.data.method)} - KES {(Number(row.data.amountMinor)/100).toFixed(2)} - {String(row.data.reference)}</p><p>Paid: {String(row.data.paidAt)} - {String(row.data.origin)}</p>{typeof row.data.documentId==='string'&&<button className={button} disabled={busy} onClick={()=>setDocumentId(String(row.data.documentId))}>Payment voucher and printing</button>}</article>)}
 {documentId&&<WebDocumentQueue key={documentId} records={records.filter(row=>row.collection==='businessDocuments'&&row.id===documentId||row.collection==='printJobs'&&row.data.documentId===documentId)} actorId={session.actorId} deviceId={apiAuth.identity.deviceId} disabled={disabled||busy||Boolean(review)} command={command} readRecords={readRecords} queue={queue} apiAuth={apiAuth}/>}
 </section>;
}
