import React,{useEffect,useMemo,useState} from 'react';
import type {BusinessRecord,Rpc,WebSession} from './session';
import {allowed} from './session';

type CommandFn=(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<unknown>;
const field='w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white outline-none focus:border-amber-400';
const button='rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm font-semibold hover:bg-slate-800 disabled:opacity-40';
const primary='rounded-lg bg-amber-400 px-3 py-2 text-sm font-bold text-slate-950 hover:bg-amber-300 disabled:opacity-40';
const data=(record?:BusinessRecord)=>record?.data as Record<string,any>|undefined;
const active=(records:BusinessRecord[],collection:string)=>records.filter(record=>record.collection===collection&&!record.archived);
const money=(minor:unknown)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES'}).format(Number(minor||0)/100);
const importFields:Record<string,Array<{field:string;aliases:string[]}>>={
 products:[{field:'name',aliases:['name','product','product name','item name','menu item']},{field:'code',aliases:['code','sku','product code','item code']},{field:'price',aliases:['price','selling price','unit price','price kes']},{field:'category',aliases:['category','type','product category']},{field:'barcode',aliases:['barcode','ean','upc']}],
 stockItems:[{field:'name',aliases:['name','item','stock item','ingredient']},{field:'code',aliases:['code','sku','stock code']},{field:'baseUnit',aliases:['base unit','unit','uom','measure']},{field:'reorderLevel',aliases:['reorder level','minimum stock','par level']},{field:'barcode',aliases:['barcode','ean','upc']}],
 customers:[{field:'name',aliases:['name','guest','customer','full name','guest name']},{field:'phone',aliases:['phone','mobile','telephone','contact number']},{field:'email',aliases:['email','email address']}],
 suppliers:[{field:'name',aliases:['name','supplier','supplier name','vendor']},{field:'code',aliases:['code','supplier code','vendor code']},{field:'phone',aliases:['phone','mobile','telephone']},{field:'email',aliases:['email','email address']}]
};
const parseCsvHeader=(text:string)=>{const first=text.replace(/^\uFEFF/,'').split(/\r?\n/,1)[0]||'';const delimiter=first.includes(',')?',':'\t';const values:string[]=[];let value='',quoted=false;for(let i=0;i<first.length;i++){const char=first[i];if(char==='"'&&quoted&&first[i+1]==='"'){value+='"';i++}else if(char==='"')quoted=!quoted;else if(char===delimiter&&!quoted){values.push(value.trim());value=''}else value+=char}values.push(value.trim());return values.filter(Boolean)};
const suggestImportFields=(headers:string[],template:string)=>{const normalize=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();const fields=importFields[template]||[];const used=new Set<number>();return headers.map(header=>{const key=normalize(header);const index=fields.findIndex(item=>!used.has(fields.indexOf(item))&&item.aliases.some(alias=>normalize(alias)===key));if(index>=0)used.add(index);return {header,field:index>=0?fields[index].field:null}})};

export function WebAdministrationView({records,session,disabled,command,rpc}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:CommandFn;rpc:Rpc}){
 const [section,setSection]=useState<'IMPORT'|'REPORTS'|'SETTINGS'|'HEALTH'|'AUTH'>('IMPORT');
 const [file,setFile]=useState<File|null>(null);const [template,setTemplate]=useState('products');const [importHeaders,setImportHeaders]=useState<string[]>([]);const [notice,setNotice]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const [email,setEmail]=useState('');const [authAction,setAuthAction]=useState<'invite'|'reset'>('invite');const [reportCollection,setReportCollection]=useState('orders');
  const employees=active(records,'employees');const products=active(records,'products');const orders=active(records,'orders');const settings=active(records,'organization')[0];const property=active(records,'property')[0];const roomTypes=active(records,'roomTypes');const rates=active(records,'ratePlans').filter(record=>record.data.mode==='NIGHTLY');
  const [roomStay,setRoomStay]=useState({roomTypeId:String(property?.data.roomStayRoomTypeId||roomTypes[0]?.id||''),ratePlanId:String(property?.data.roomStayRatePlanId||rates[0]?.id||''),nightlyCheckoutTime:String(property?.data.nightlyCheckoutTime||'10:00'),dayStayCutoffTime:String(property?.data.dayStayCutoffTime||'18:00')});
 const reportRows=useMemo(()=>active(records,reportCollection),[records,reportCollection]);
 useEffect(()=>{let current=true;if(!file){setImportHeaders([]);return}void file.slice(0,64*1024).text().then(text=>{if(current)setImportHeaders(parseCsvHeader(text))}).catch(()=>{if(current)setImportHeaders([])});return()=>{current=false}},[file]);
 const importSuggestions=useMemo(()=>suggestImportFields(importHeaders,template),[importHeaders,template]);
 const download=(name:string,content:string,type='text/csv;charset=utf-8')=>{const url=URL.createObjectURL(new Blob([content],{type}));const anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const run=async(operation:string,payload:Record<string,unknown>,collection='adminOperations',id:string=crypto.randomUUID())=>{setBusy(true);setError('');setNotice('');try{await command(operation,collection,id,payload);setNotice('Request committed through the business command queue.')}catch(cause){setError(String(cause))}finally{setBusy(false)}};
 const stageImport=async()=>{if(!file)return;await run('admin.import.stage',{fileName:file.name,templateKey:template,csvText:await file.text()});setFile(null)};
 const invite=async()=>{if(!email.trim())return;setBusy(true);setError('');setNotice('');try{const result=await rpc('functions/v1/servos-auth-lifecycle',{action:authAction,email:email.trim(),redirectTo:`${window.location.origin}${window.location.pathname}`});setNotice(String(result?.message||'Auth request accepted.'))}catch(cause){setError(String(cause))}finally{setBusy(false)}};
 const exportReport=()=>{const keys=new Set<string>();for(const row of reportRows)Object.keys(row.data).forEach(key=>keys.add(key));const columns=['id',...Array.from(keys)];const quote=(value:unknown)=>`"${String(typeof value==='object'?JSON.stringify(value):value??'').replaceAll('"','""')}"`;download(`${reportCollection}-${new Date().toISOString().slice(0,10)}.csv`,[columns.join(','),...reportRows.map(row=>columns.map(column=>quote(column==='id'?row.id:row.data[column])).join(','))].join('\n'))};
 return <section className="space-y-5" aria-label="Administration and business management">
  <header><h2 className="text-xl font-bold">Administration and business management</h2><p className="mt-1 text-sm text-slate-400">Imports, reports, settings and account lifecycle actions remain server-authorized. No browser action writes directly to Supabase tables.</p></header>
  {error&&<p role="alert" className="rounded-lg border border-rose-800 bg-rose-950 p-3 text-sm">{error}</p>}{notice&&<p role="status" className="rounded-lg border border-emerald-800 bg-emerald-950 p-3 text-sm">{notice}</p>}
  <div className="flex flex-wrap gap-2">{(['IMPORT','REPORTS','SETTINGS','HEALTH','AUTH'] as const).map(value=><button key={value} className={section===value?primary:button} onClick={()=>setSection(value)}>{value==='IMPORT'?'Import Center':value==='REPORTS'?'Reports':value==='SETTINGS'?'Business settings':value==='HEALTH'?'Health and readiness':'Auth lifecycle'}</button>)}</div>
  {section==='IMPORT'&&<Panel title="Controlled Import Center"><p className="text-sm text-slate-400">Stage a file first. The server validates, hashes and dry-runs it before an authorized operator applies it.</p><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Template<select className={field} value={template} onChange={event=>setTemplate(event.target.value)}><option value="products">Products and menu</option><option value="stockItems">Stock items</option><option value="customers">Guests</option><option value="suppliers">Suppliers</option></select></label><label className="text-sm">CSV file<input className={field} type="file" accept=".csv,.tsv,text/csv" onChange={event=>setFile(event.target.files?.[0]||null)}/></label></div>{importSuggestions.length>0&&<div className="rounded-lg border border-slate-700 p-3"><h4 className="font-semibold">Suggested column matches</h4><p className="text-xs text-slate-400">Suggestions are based on the header row only. Review the server dry run; no mapping or business records are changed here.</p><div className="mt-2 grid gap-1 sm:grid-cols-2">{importSuggestions.map(item=><div key={item.header} className="flex justify-between gap-3 rounded bg-slate-950 px-2 py-1 text-sm"><span className="truncate">{item.header}</span><span className={item.field?'text-emerald-300':'text-amber-200'}>{item.field?`Likely ${item.field}`:'Review manually'}</span></div>)}</div></div>}<button disabled={disabled||busy||!file||!allowed(session,'data.import.stage')} className={primary} onClick={()=>void stageImport()}>Stage import for review</button><p className="text-xs text-slate-500">{allowed(session,'data.import.execute')?'This role may apply a reviewed plan after the server dry run.':'A separate authorized Admin must apply the reviewed plan.'}</p></Panel>}
  {section==='REPORTS'&&<Panel title="Reports center"><div className="flex flex-wrap gap-2"><select className={field+' max-w-xs'} value={reportCollection} onChange={event=>setReportCollection(event.target.value)}><option value="orders">Orders</option><option value="payments">Payments</option><option value="receiptDocuments">Receipts</option><option value="stockMovements">Stock movements</option><option value="goodsReceipts">Goods receipts</option><option value="journalEntries">Journal entries</option></select><button disabled={!reportRows.length} className={primary} onClick={exportReport}>Download CSV</button></div><div className="mt-3 grid gap-2 sm:grid-cols-3"><Fact label="Rows" value={String(reportRows.length)}/><Fact label="Products" value={String(products.length)}/><Fact label="Orders" value={String(orders.length)}/></div><p className="mt-3 text-xs text-slate-500">Exports contain only records present in this actor’s authorized snapshot. Provider reconciliation and backup health are shown separately and are never inferred as successful.</p></Panel>}
  {section==='SETTINGS'&&<Panel title="Business identity and policy"><div className="grid gap-3 sm:grid-cols-2"><Fact label="Business identity" value={String(data(settings)?.name||data(settings)?.tradingName||session.businessId)}/><Fact label="Employees visible" value={String(employees.length)}/><Fact label="Lifecycle" value={String(session.lifecycleStage||'LIVE')}/><Fact label="Readiness" value={session.readiness?.ready?'Ready':'Review checks'}/></div><div className="mt-3 flex flex-wrap gap-2"><button disabled={disabled||!allowed(session,'business.configure')} className={button} onClick={()=>void run('business.settings.save',{id:'business',data:{name:String(data(settings)?.name||data(settings)?.tradingName||''),taxPolicyVersion:String(data(settings)?.taxPolicyVersion||'A_STANDARD')}},'organization',String(settings?.id||'business'))}>Save verified settings</button><button disabled={disabled||!allowed(session,'business.view')} className={button} onClick={()=>void rpc('rpc/servos_v2_web_lifecycle',{action:'readiness.refresh',payload:{}}).then(()=>setNotice('Readiness refreshed.')).catch(cause=>setError(String(cause)))}>Refresh readiness</button></div><div className="mt-4 rounded-lg border border-slate-700 p-3"><h4 className="font-semibold">Room stays</h4><p className="mt-1 text-xs text-slate-400">One configured room type and nightly rate. Day stays use the same rate and can end any time before the cutoff.</p><div className="mt-3 grid gap-2 sm:grid-cols-2"><select className={field} value={roomStay.roomTypeId} onChange={event=>setRoomStay({...roomStay,roomTypeId:event.target.value})}>{roomTypes.map(record=><option key={record.id} value={record.id}>{String(record.data.name||record.id)}</option>)}</select><select className={field} value={roomStay.ratePlanId} onChange={event=>setRoomStay({...roomStay,ratePlanId:event.target.value})}>{rates.map(record=><option key={record.id} value={record.id}>{String(record.data.name||record.id)} · {money(record.data.priceMinor)}</option>)}</select><label className="text-sm">Nightly checkout<input className={field} type="time" value={roomStay.nightlyCheckoutTime} onChange={event=>setRoomStay({...roomStay,nightlyCheckoutTime:event.target.value})}/></label><label className="text-sm">Day-stay cutoff<input className={field} type="time" value={roomStay.dayStayCutoffTime} onChange={event=>setRoomStay({...roomStay,dayStayCutoffTime:event.target.value})}/></label></div><button disabled={disabled||!allowed(session,'business.configure')||!roomStay.roomTypeId||!roomStay.ratePlanId} className={`${button} mt-3`} onClick={()=>void run('roomStay.settings',{...roomStay,propertyVersion:property?.version},'property',String(property?.id||'property'))}>Save room-stay policy</button></div></Panel>}
  {section==='HEALTH'&&<Panel title="Backup, reconciliation and readiness health"><div className="grid gap-3 sm:grid-cols-2">{(session.readiness?.checks||[]).map(check=><Fact key={check.id} label={check.label} value={check.complete?'Complete':'Needs review'}/>)}</div><div className="mt-3 rounded-lg border border-amber-700/40 bg-amber-500/5 p-3 text-sm text-amber-100">Hosted backup verification and external payment reconciliation are operational checks, not browser assumptions. Confirm them during production cutover before Go Live.</div><button disabled={disabled||!allowed(session,'backup.create')} className={button} onClick={()=>void run('backup.request',{reason:'Admin web readiness rehearsal'})}>Request backup rehearsal</button></Panel>}
  {section==='AUTH'&&<Panel title="Auth invitation and recovery"><p className="text-sm text-slate-400">Supabase Auth owns invitation links and passwords. ServOS only requests an invitation or reset email and then binds the resulting Auth user to a staff profile.</p><div className="flex flex-wrap gap-2"><select className={field+' max-w-xs'} value={authAction} onChange={event=>setAuthAction(event.target.value as 'invite'|'reset')}><option value="invite">Invite staff member</option><option value="reset">Send password reset</option></select><input className={field+' max-w-sm'} type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="staff@example.com"/><button disabled={busy||!email.trim()||!allowed(session,'staff.create')} className={primary} onClick={()=>void invite()}>{authAction==='invite'?'Send invitation':'Send reset email'}</button></div></Panel>}
 </section>;
}
const Panel=({title,children}:{title:string;children:React.ReactNode})=><section className="rounded-xl border border-slate-800 bg-slate-900/50 p-4"><h3 className="mb-3 font-bold">{title}</h3><div className="space-y-3">{children}</div></section>;
const Fact=({label,value}:{label:string;value:string})=><div className="rounded-lg bg-slate-950 p-3"><div className="text-[10px] uppercase tracking-wide text-slate-500">{label}</div><div className="mt-1 font-semibold">{value}</div></div>;
