import React,{useEffect,useRef,useState} from 'react';
import {allowed,type BusinessRecord,type WebSession} from './session';
import type {QueuedCommand} from './BusinessStore';
import type {CommandOutcome} from '../../types/transactions';
import {parseMoneyToMinor} from '../../utils/fiscal';
const object=(value:unknown):Record<string,unknown>=>value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{};
const input='mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2';
const button='rounded border border-slate-600 px-3 py-2 disabled:opacity-40';
type Line={id:string;name:string;unit:string;accepted:number;priceMinor:number;totalMinor:number;quantity:string;price:string;total:string};
type Review={payable:BusinessRecord;grn:BusinessRecord;lines:Line[]};
export function WebApiPayables({records,session,queue,disabled,command}:{records:BusinessRecord[];session:WebSession;queue:QueuedCommand[];disabled:boolean;command:(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<CommandOutcome>}){
 const [review,setReview]=useState<Review|null>(null),[number,setNumber]=useState(''),[date,setDate]=useState(''),[due,setDue]=useState(''),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[pending,setPending]=useState(''),[message,setMessage]=useState('');const inFlight=useRef(false);
 const unresolved=queue.some(row=>(row.command.operation.startsWith('procurement.')||row.command.operation.startsWith('supplierPayable.')||row.command.operation.startsWith('supplierReturn.')||row.command.operation.startsWith('supplierCredit.'))&&['PENDING_SYNC','OUTCOME_UNKNOWN'].includes(row.state));
 const blocked=disabled||busy||unresolved||Boolean(pending),manage=allowed(session,'procurement.manage');
 useEffect(()=>{if(!pending)return;const entry=queue.find(row=>row.id===pending);if(!entry||!['SYNCHRONIZED','REJECTED','CONFLICT'].includes(entry.state))return;setPending('');setReview(null);setMessage(entry.state==='SYNCHRONIZED'?'Original invoice match confirmed.':entry.result?.error?.message||'Review the latest payable before another invoice action.');},[queue,pending]);
 const open=(payable:BusinessRecord)=>{try{
  const grn=records.find(row=>row.collection==='goodsReceipts'&&row.id===payable.data.goodsReceiptId),doc=records.find(row=>row.collection==='businessDocuments'&&row.id===grn?.data.documentId);if(!grn||!doc)throw new Error('Synchronize the original GRN document before matching an invoice.');
  const snapshot=object(doc.data.snapshot);if(!Array.isArray(snapshot.items))throw new Error('Original GRN lines are unavailable.');
  const lines=snapshot.items.map(object).filter(line=>Number(line.quantityAccepted)>0).map(line=>({id:String(line.id),name:String(object(line.stockSnapshot).name),unit:String(object(line.purchasePackageSnapshot).name||object(line.stockSnapshot).baseUnit),accepted:Number(line.quantityAccepted),priceMinor:Number(line.unitPriceMinor),totalMinor:Number(line.acceptedTotalMinor),quantity:'',price:'',total:''}));
  setReview({payable,grn,lines});setNumber('');setDate('');setDue('');setAmount('');setReason('');setAck(false);setMessage('');
 }catch(error){setMessage(error instanceof Error?error.message:'Cannot review payable.');}};
 const patch=(id:string,change:Partial<Line>)=>setReview(current=>current?{...current,lines:current.lines.map(line=>line.id===id?{...line,...change}:line)}:null);
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!review||blocked||inFlight.current||!manage||!ack)return;inFlight.current=true;setBusy(true);setMessage('');try{
  const lines=review.lines.map(line=>{if(!/^\d+(?:\.\d{1,6})?$/.test(line.quantity)||Number(line.quantity)<=0||Number(line.quantity)>1e9)throw new Error('Enter each billed quantity with at most six decimals.');const quantityBilled=Number(line.quantity),unitPriceMinor=parseMoneyToMinor(line.price),lineTotalMinor=parseMoneyToMinor(line.total);if(Math.round(quantityBilled*1e6)!==Math.round(line.accepted*1e6)||unitPriceMinor!==line.priceMinor||lineTotalMinor!==line.totalMinor)throw new Error('Invoice lines must match the accepted GRN. Resolve quantity or cost variances through a reviewed correction.');return {goodsReceiptLineId:line.id,quantityBilled,unitPriceMinor,lineTotalMinor};});
  const invoiceAmountMinor=parseMoneyToMinor(amount);if(invoiceAmountMinor!==Number(review.payable.data.amountMinor))throw new Error('Invoice total must match this received liability.');
  const outcome=await command('supplierPayable.matchInvoice','supplierPayables',review.payable.id,{payableId:review.payable.id,invoiceNumber:number.trim(),invoiceDate:date,dueDate:due,invoiceAmountMinor,reason:reason.trim(),lines,expectedVersions:[{collection:'supplierPayables',id:review.payable.id,version:review.payable.version}]});
  if(outcome.kind==='CONFIRMED'){setReview(null);setMessage('Invoice matched. The existing receiving liability is unchanged; no payment was recorded.');}else{if(outcome.kind==='PENDING'||outcome.kind==='OUTCOME_UNKNOWN')setPending(outcome.commandId);setMessage('message' in outcome?outcome.message:'Recover the original invoice match in Activity.');}
 }catch(error){setMessage(error instanceof Error?error.message:'Cannot match invoice.');}finally{inFlight.current=false;setBusy(false);}};
 return <section className="space-y-4" aria-label="Supplier payables"><h2 className="text-xl font-bold">Supplier invoices and payables</h2><p>Compare the supplier invoice with the accepted GRN. Matching records invoice evidence against the existing liability.</p>{unresolved&&<p role="status">Recover the original procurement action in Activity before another invoice match.</p>}
 {records.filter(row=>row.collection==='supplierPayables').map(row=><article key={row.id} className="space-y-2 rounded border border-slate-700 p-3"><p>GRN: {String(records.find(grn=>grn.collection==='goodsReceipts'&&grn.id===row.data.goodsReceiptId)?.data.documentNumber||row.data.goodsReceiptId)}</p><p>{String(row.data.status)} - Outstanding KES {(Number(row.data.outstandingMinor)/100).toFixed(2)}</p>{typeof row.data.invoiceNumber==='string'&&row.data.invoiceNumber&&<p>Invoice: {String(row.data.invoiceNumber)} - Due: {String(row.data.dueDate)}</p>}{manage&&row.data.status==='RECEIVED_UNINVOICED'&&<button className={button} disabled={blocked} onClick={()=>open(row)}>Review supplier invoice</button>}</article>)}
 {review&&<form aria-label="Match supplier invoice" onSubmit={event=>void submit(event)} className="space-y-4 rounded border border-slate-700 p-4"><h3 className="font-bold">Match invoice to {String(review.grn.data.documentNumber)}</h3><fieldset disabled={blocked} className="space-y-3"><label className="block">Invoice reference<input required maxLength={80} className={input} value={number} onChange={event=>setNumber(event.target.value)}/></label><div className="grid gap-3 sm:grid-cols-2"><label>Invoice date<input required type="date" className={input} value={date} onChange={event=>setDate(event.target.value)}/></label><label>Due date<input required type="date" min={date} className={input} value={due} onChange={event=>setDue(event.target.value)}/></label></div>
 {review.lines.map(line=><fieldset key={line.id} className="rounded border border-slate-700 p-3"><legend>{line.name}</legend><p>Accepted {line.accepted} {line.unit}; agreed unit cost KES {(line.priceMinor/100).toFixed(2)}; accepted amount KES {(line.totalMinor/100).toFixed(2)}</p><div className="grid gap-3 sm:grid-cols-3">{(['quantity','price','total'] as const).map(key=><label key={key}>{key==='quantity'?'Billed quantity':key==='price'?'Invoice unit cost (KES)':'Invoice line amount (KES)'}<input required inputMode="decimal" className={input} value={line[key]} onChange={event=>patch(line.id,{[key]:event.target.value})}/></label>)}</div></fieldset>)}
 <p>Partial-delivery line amounts use the frozen cumulative rounding basis shown above.</p><label className="block">Invoice total (KES)<input required inputMode="decimal" className={input} value={amount} onChange={event=>setAmount(event.target.value)}/></label><label className="block">Review reason<textarea required minLength={3} maxLength={500} className={input} value={reason} onChange={event=>setReason(event.target.value)}/></label><label className="block"><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/> I checked the supplier invoice reference, dates, quantities, costs and total against this GRN.</label><button className={button} disabled={!ack}>Match reviewed invoice</button></fieldset><button type="button" className={button} disabled={busy||Boolean(pending)} onClick={()=>setReview(null)}>Close</button></form>}{message&&<p role="status">{message}</p>}
 </section>;
}
