import React,{useEffect,useMemo,useState} from 'react';
import {isCommandConfirmed,type CommandOutcome} from '../../types/transactions';
import {parseMoneyToMinor,parsePercentToBasisPoints} from '../../utils/fiscal';
import {businessDateTimeAfterBusinessDays,businessDateTimeInput,businessDateTimeToUtc} from '../../utils/businessTime';
import {allowed,type BusinessRecord,type WebSession} from './session';

type Command=(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<CommandOutcome>;
const field='mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2';
const button='min-h-11 rounded border border-slate-600 px-3 py-2 disabled:opacity-40';
const primary='min-h-11 rounded bg-amber-400 px-4 py-2 font-bold text-slate-950 disabled:opacity-40';
const active=(records:BusinessRecord[],collection:string)=>records.filter(row=>row.collection===collection&&!row.archived);
const baseline=(row:BusinessRecord)=>({collection:row.collection,id:row.id,version:row.version});
const money=(amount:unknown)=>(Number(amount||0)/100).toLocaleString('en-KE',{style:'currency',currency:'KES'});
const messageFor=(outcome:CommandOutcome,success:string)=>isCommandConfirmed(outcome)?success:outcome.kind==='DRAFT_SAVED'?'Saved as a draft; no reservation or room change was made.':outcome.kind==='PENDING'?'Saved and waiting to synchronize.':outcome.kind==='OUTCOME_UNKNOWN'||outcome.kind==='REJECTED'||outcome.kind==='CONFLICT'||outcome.kind==='BLOCKED'?outcome.message:'The action was not confirmed.';
const uuid=()=>crypto.randomUUID();

export function WebApiRoomsView({records,session,disabled,command}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:Command}){
 const canManage=allowed(session,'rooms.manage'),canOperate=allowed(session,'rooms.operate');
 const roomTypes=active(records,'roomTypes'),rooms=active(records,'rooms'),rates=active(records,'ratePlans'),reservations=active(records,'roomReservations'),customers=active(records,'customers'),folios=active(records,'folios');
 const hospitality=active(records,'hospitalitySettings')[0],propertyTimeZone=String(hospitality?.data.timeZone||session.propertyContext?.timeZone||'Africa/Nairobi'),checkoutTime=String(hospitality?.data.nightlyCheckoutTime||session.propertyContext?.nightlyCheckoutTime||'10:00'),dayCutoff=String(hospitality?.data.dayStayCutoffTime||session.propertyContext?.dayStayCutoffTime||'18:00');
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [typeId,setTypeId]=useState(''),[typeName,setTypeName]=useState(''),[typeCode,setTypeCode]=useState(''),[typeCapacity,setTypeCapacity]=useState('2');
 const [roomNumber,setRoomNumber]=useState(''),[roomTypeId,setRoomTypeId]=useState(''),[roomCapacity,setRoomCapacity]=useState('2'),[turnaround,setTurnaround]=useState('30');
 const [rateName,setRateName]=useState(''),[rateTypeId,setRateTypeId]=useState(''),[rateMode,setRateMode]=useState<'NIGHTLY'|'DAY_USE'>('NIGHTLY'),[ratePrice,setRatePrice]=useState(''),[rateTax,setRateTax]=useState('0'),[dayMinutes,setDayMinutes]=useState('480');
 const [reservationRoomId,setReservationRoomId]=useState(''),[reservationRateId,setReservationRateId]=useState(''),[guestId,setGuestId]=useState(''),[guestCount,setGuestCount]=useState('1'),[arrival,setArrival]=useState(()=>businessDateTimeInput(new Date(),propertyTimeZone)),[departure,setDeparture]=useState(()=>businessDateTimeInput(businessDateTimeAfterBusinessDays(new Date(),1,checkoutTime,propertyTimeZone),propertyTimeZone));
 useEffect(()=>{setArrival(businessDateTimeInput(new Date(),propertyTimeZone));setDeparture(businessDateTimeInput(businessDateTimeAfterBusinessDays(new Date(),1,checkoutTime,propertyTimeZone),propertyTimeZone))},[propertyTimeZone,checkoutTime]);
 const typeById=useMemo(()=>new Map(roomTypes.map(row=>[row.id,row])),[roomTypes]);
 const selectedRoom=rooms.find(row=>row.id===reservationRoomId);
 const matchingRates=rates.filter(row=>row.data.roomTypeId===selectedRoom?.data.roomTypeId);
 const roomBlocks=active(records,'roomBlocks'),workOrders=active(records,'maintenanceWorkOrders');let requestedStart=NaN,requestedEnd=NaN;try{requestedStart=Date.parse(businessDateTimeToUtc(arrival,propertyTimeZone));requestedEnd=Date.parse(businessDateTimeToUtc(departure,propertyTimeZone))}catch{}const potentiallyAvailableRooms=rooms.filter(room=>room.data.housekeepingState==='READY'&&room.data.maintenanceState==='AVAILABLE'&&(!Number.isFinite(requestedStart)||!Number.isFinite(requestedEnd)||requestedEnd<=requestedStart||(!reservations.some(row=>row.data.roomId===room.id&&['RESERVED','CHECKED_IN'].includes(String(row.data.status))&&Date.parse(String(row.data.startsAt))<requestedEnd+(Number(room.data.turnaroundMinutes||0)*60000)&&Date.parse(String(row.data.blockedUntil||row.data.endsAt))>requestedStart)&&!roomBlocks.some(row=>row.data.roomId===room.id&&row.data.status==='ACTIVE'&&Date.parse(String(row.data.startsAt))<requestedEnd+(Number(room.data.turnaroundMinutes||0)*60000)&&(!row.data.endsAt||Date.parse(String(row.data.endsAt))>requestedStart)))));

 const run=async(operation:string,collection:string,id:string,payload:Record<string,unknown>,success:string)=>{
  if(disabled||busy)return;setBusy(true);setMessage('');
  try{const outcome=await command(operation,collection,id,payload);setMessage(messageFor(outcome,success));if(isCommandConfirmed(outcome))return true;return false}
  catch(error){setMessage(error instanceof Error?error.message:'The API outcome could not be checked. Review Activity before retrying.');return false}
  finally{setBusy(false)}
 };
 const saveType=async(event:React.FormEvent)=>{
  event.preventDefault();const name=typeName.trim(),code=(typeCode.trim()||name.toUpperCase().replace(/[^A-Z0-9]+/g,'-')),id=typeId||uuid(),current=roomTypes.find(row=>row.id===id);
  if(!name)return setMessage('Enter a room type name.');
  if(await run('roomType.save','roomTypes',id,{id,data:{name,code,maxGuests:Number(typeCapacity)},expectedVersions:[{collection:'roomTypes',id,version:current?.version??0},...(current?[]:[])]},'Room type saved.')){setTypeId(id);setTypeName('');setTypeCode('');}
 };
 const saveRoom=async(event:React.FormEvent)=>{
  event.preventDefault();const id=uuid(),roomType=roomTypes.find(row=>row.id===roomTypeId);if(!roomType)return setMessage('Choose an active room type first.');
  if(await run('room.save','rooms',id,{id,data:{number:roomNumber,roomTypeId,capacity:Number(roomCapacity),turnaroundMinutes:Number(turnaround),floor:'',amenities:[],notes:''},expectedVersions:[{collection:'rooms',id,version:0},baseline(roomType)]},'Room saved.')){setRoomNumber('');setRoomCapacity(String(roomType.data.maxGuests));}
 };
 const saveRate=async(event:React.FormEvent)=>{
  event.preventDefault();const id=uuid(),roomType=roomTypes.find(row=>row.id===rateTypeId);if(!roomType)return setMessage('Choose an active room type first.');
  try{const data={name:rateName,roomTypeId:rateTypeId,mode:rateMode,priceMinor:parseMoneyToMinor(ratePrice),currency:'KES',taxBasisPoints:parsePercentToBasisPoints(rateTax),...(rateMode==='DAY_USE'?{durationMinutes:Number(dayMinutes)}:{})};
   if(await run('ratePlan.save','ratePlans',id,{id,data,expectedVersions:[{collection:'ratePlans',id,version:0},baseline(roomType)]},'Rate plan saved.'))setRateName('');
  }catch(error){setMessage(error instanceof Error?error.message:'Enter a valid rate.');}
 };
 const reserve=async(event:React.FormEvent,walkIn=false)=>{
  event.preventDefault();const room=rooms.find(row=>row.id===reservationRoomId),rate=matchingRates.find(row=>row.id===reservationRateId),guest=customers.find(row=>row.id===guestId);if(!room||!rate||!guest)return setMessage('Choose an available room, matching rate and named guest.');
  let startsAt:string,endsAt:string;try{startsAt=businessDateTimeToUtc(arrival,propertyTimeZone);endsAt=businessDateTimeToUtc(departure,propertyTimeZone)}catch(error){return setMessage(error instanceof Error?error.message:'Enter valid property-local arrival and departure times.')}
  const id=uuid(),operation=walkIn?'roomReservation.walkIn':'roomReservation.create';
  if(await run(operation,'roomReservations',id,{id,roomId:room.id,ratePlanId:rate.id,customerId:guest.id,stayType:rate.data.mode==='DAY_USE'?'DAY':'NIGHTLY',guests:Number(guestCount),startsAt,endsAt,expectedVersions:[{collection:'roomReservations',id,version:0},baseline(room),baseline(rate),baseline(guest)]},walkIn?'Walk-in checked in.':'Reservation confirmed.')){
   setGuestId('');setGuestCount('1');setArrival(businessDateTimeInput(new Date(),propertyTimeZone));setDeparture(businessDateTimeInput(businessDateTimeAfterBusinessDays(new Date(),1,checkoutTime,propertyTimeZone),propertyTimeZone));
  }
 };
 const cancel=async(reservation:BusinessRecord)=>{
  const reason=window.prompt('Cancellation reason (required)');if(!reason?.trim())return;
  await run('roomReservation.cancel','roomReservations',reservation.id,{id:reservation.id,reason:reason.trim(),expectedVersions:[baseline(reservation)]},'Reservation cancelled.');
 };
 const checkIn=async(reservation:BusinessRecord)=>{await run('stay.checkIn','roomReservations',reservation.id,{id:reservation.id,expectedVersions:[baseline(reservation)]},'Guest checked in.');};
 const housekeeping=async(room:BusinessRecord,state:string)=>{await run('room.housekeeping','rooms',room.id,{id:room.id,state,expectedVersions:[baseline(room)]},`Room marked ${state.toLowerCase()}.`);};
 const openMaintenance=async(room:BusinessRecord)=>{const title=window.prompt(`Maintenance title for room ${String(room.data.number)}`,'Room fault');if(!title?.trim())return;const fault=window.prompt('Describe the fault');if(!fault?.trim())return;const id=uuid();await run('maintenance.open','maintenanceWorkOrders',id,{id,roomId:room.id,title:title.trim(),fault:fault.trim(),reason:fault.trim(),expectedVersions:[baseline(room)]},'Room blocked and maintenance work order opened.');};
 const resolveMaintenance=async(work:BusinessRecord)=>{const resolution=window.prompt('Describe the completed repair');if(!resolution?.trim())return;await run('maintenance.resolve','maintenanceWorkOrders',work.id,{id:work.id,resolution:resolution.trim(),expectedVersions:[baseline(work)]},'Maintenance resolution recorded.');};
 const returnToService=async(room:BusinessRecord)=>{if(!window.confirm(`Return room ${String(room.data.number)} to housekeeping? It will move to DIRTY for inspection.`))return;await run('maintenance.returnToService','rooms',room.id,{id:room.id,expectedVersions:[baseline(room)]},'Room returned to service as dirty.');};

 if(!allowed(session,'rooms.view')&&!canManage&&!canOperate)return <section className="rounded-xl border border-slate-800 p-5">Room access is not enabled for this staff account.</section>;
 return <section className="space-y-5">
  <header><h2 className="text-2xl font-bold">Rooms and reservations</h2><p className="mt-1 text-sm text-slate-400">Room availability is checked and serialized by the API when a reservation is confirmed.</p></header>
  {message&&<p role="status" aria-live="polite" className="rounded border border-slate-700 bg-slate-900 p-3 text-sm">{message}</p>}
  {canManage&&<div className="grid gap-4 xl:grid-cols-3">
   <form className="space-y-3 rounded-xl border border-slate-800 p-4" onSubmit={event=>void saveType(event)}><h3 className="font-semibold">Room types</h3><label className="block text-sm">Name<input required className={field} value={typeName} disabled={disabled||busy} onChange={event=>setTypeName(event.target.value)}/></label><label className="block text-sm">Code<input className={field} value={typeCode} disabled={disabled||busy} onChange={event=>setTypeCode(event.target.value)}/></label><label className="block text-sm">Maximum guests<input required type="number" min="1" max="1000" className={field} value={typeCapacity} disabled={disabled||busy} onChange={event=>setTypeCapacity(event.target.value)}/></label><button className={button} disabled={disabled||busy}>Add room type</button><div className="space-y-1 text-sm">{roomTypes.map(row=><button type="button" key={row.id} className="block text-left text-slate-300" onClick={()=>{setTypeId(row.id);setTypeName(String(row.data.name));setTypeCode(String(row.data.code));setTypeCapacity(String(row.data.maxGuests))}}>{String(row.data.name)} · up to {String(row.data.maxGuests)}</button>)}</div>{typeId&&<button type="button" className={button} onClick={()=>setTypeId('')}>Cancel edit</button>}</form>
   <form className="space-y-3 rounded-xl border border-slate-800 p-4" onSubmit={event=>void saveRoom(event)}><h3 className="font-semibold">Add room</h3><label className="block text-sm">Room number<input required className={field} value={roomNumber} disabled={disabled||busy} onChange={event=>setRoomNumber(event.target.value)}/></label><label className="block text-sm">Room type<select required className={field} value={roomTypeId} disabled={disabled||busy} onChange={event=>{setRoomTypeId(event.target.value);const found=typeById.get(event.target.value);if(found)setRoomCapacity(String(found.data.maxGuests))}}><option value="">Select room type</option>{roomTypes.map(row=><option key={row.id} value={row.id}>{String(row.data.name)}</option>)}</select></label><label className="block text-sm">Guest capacity<input required type="number" min="1" className={field} value={roomCapacity} disabled={disabled||busy} onChange={event=>setRoomCapacity(event.target.value)}/></label><label className="block text-sm">Turnaround minutes<input required type="number" min="0" max="10080" className={field} value={turnaround} disabled={disabled||busy} onChange={event=>setTurnaround(event.target.value)}/></label><button className={button} disabled={disabled||busy||!roomTypes.length}>Add room</button></form>
   <form className="space-y-3 rounded-xl border border-slate-800 p-4" onSubmit={event=>void saveRate(event)}><h3 className="font-semibold">Add rate plan</h3><label className="block text-sm">Name<input required className={field} value={rateName} disabled={disabled||busy} onChange={event=>setRateName(event.target.value)}/></label><label className="block text-sm">Room type<select required className={field} value={rateTypeId} disabled={disabled||busy} onChange={event=>setRateTypeId(event.target.value)}><option value="">Select room type</option>{roomTypes.map(row=><option key={row.id} value={row.id}>{String(row.data.name)}</option>)}</select></label><label className="block text-sm">Stay type<select className={field} value={rateMode} disabled={disabled||busy} onChange={event=>setRateMode(event.target.value as 'NIGHTLY'|'DAY_USE')}><option value="NIGHTLY">Nightly</option><option value="DAY_USE">Day use</option></select></label>{rateMode==='DAY_USE'&&<label className="block text-sm">Duration minutes<input required type="number" min="30" max="1440" className={field} value={dayMinutes} disabled={disabled||busy} onChange={event=>setDayMinutes(event.target.value)}/></label>}<label className="block text-sm">Rate (KES)<input required type="number" min="0" step="0.01" className={field} value={ratePrice} disabled={disabled||busy} onChange={event=>setRatePrice(event.target.value)}/></label><label className="block text-sm">Tax rate (%)<input required type="number" min="0" max="100" step="0.01" className={field} value={rateTax} disabled={disabled||busy} onChange={event=>setRateTax(event.target.value)}/></label><button className={button} disabled={disabled||busy||!roomTypes.length}>Add rate plan</button></form>
  </div>}
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{rooms.map(room=><article key={room.id} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-lg font-semibold">Room {String(room.data.number)}</h3><p className="text-sm text-slate-400">{String(typeById.get(String(room.data.roomTypeId))?.data.name||'Room type unavailable')} · capacity {String(room.data.capacity)}</p></div><span className="rounded border border-slate-700 px-2 py-1 text-xs">{String(room.data.housekeepingState)} · {String(room.data.maintenanceState)}</span></div>{canOperate&&<div className="mt-3 flex flex-wrap gap-2">{room.data.housekeepingState==='DIRTY'&&<button className={button} disabled={disabled||busy} onClick={()=>void housekeeping(room,'CLEANING')}>Start cleaning</button>}{room.data.housekeepingState==='CLEANING'&&<button className={button} disabled={disabled||busy} onClick={()=>void housekeeping(room,'INSPECTED')}>Submit for inspection</button>}{room.data.housekeepingState==='INSPECTED'&&<><button className={button} disabled={disabled||busy} onClick={()=>void housekeeping(room,'READY')}>Mark ready</button><button className={button} disabled={disabled||busy} onClick={()=>void housekeeping(room,'DIRTY')}>Return to dirty</button></>}{room.data.housekeepingState==='READY'&&<button className={button} disabled={disabled||busy} onClick={()=>void housekeeping(room,'DIRTY')}>Mark dirty</button>}{allowed(session,'maintenance.manage')&&room.data.maintenanceState!=='OUT_OF_SERVICE'&&<button className={button} disabled={disabled||busy} onClick={()=>void openMaintenance(room)}>Report fault / block room</button>}{allowed(session,'maintenance.manage')&&room.data.maintenanceState==='OUT_OF_SERVICE'&&<button className={button} disabled={disabled||busy||workOrders.some(work=>work.data.roomId===room.id&&work.data.status==='OPEN')} onClick={()=>void returnToService(room)}>Return to service</button>}{workOrders.filter(work=>work.data.roomId===room.id&&work.data.status==='OPEN').map(work=><button key={work.id} className={button} disabled={disabled||busy||!allowed(session,'maintenance.manage')} onClick={()=>void resolveMaintenance(work)}>Resolve: {String(work.data.title)}</button>)}</div>}</article>)}</section>
  {canOperate&&<form className="space-y-3 rounded-xl border border-slate-800 p-4" onSubmit={event=>void reserve(event)}><h3 className="text-lg font-semibold">Reservation / walk-in</h3><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><label className="text-sm">Room<select required className={field} value={reservationRoomId} disabled={disabled||busy} onChange={event=>{setReservationRoomId(event.target.value);setReservationRateId('')}}><option value="">Select room</option>{potentiallyAvailableRooms.map(row=><option key={row.id} value={row.id}>Room {String(row.data.number)}</option>)}</select></label><label className="text-sm">Rate plan<select required className={field} value={reservationRateId} disabled={disabled||busy||!matchingRates.length} onChange={event=>setReservationRateId(event.target.value)}><option value="">Select rate</option>{matchingRates.map(row=><option key={row.id} value={row.id}>{String(row.data.name)} · {money(row.data.priceMinor)} {row.data.mode==='NIGHTLY'?'per night':'day use'}</option>)}</select></label><label className="text-sm">Guest<select required className={field} value={guestId} disabled={disabled||busy} onChange={event=>setGuestId(event.target.value)}><option value="">Select named guest</option>{customers.map(row=><option key={row.id} value={row.id}>{String(row.data.name)}</option>)}</select></label><label className="text-sm">Guests<input required type="number" min="1" max="1000" className={field} value={guestCount} disabled={disabled||busy} onChange={event=>setGuestCount(event.target.value)}/></label><label className="text-sm">Arrival<input required type="datetime-local" className={field} value={arrival} disabled={disabled||busy} onChange={event=>setArrival(event.target.value)}/></label><label className="text-sm">Departure<input required type="datetime-local" className={field} value={departure} disabled={disabled||busy} onChange={event=>setDeparture(event.target.value)}/></label></div><div className="flex flex-wrap gap-2"><button className={primary} disabled={disabled||busy||!rooms.length||!rates.length||!customers.length}>Confirm reservation</button><button type="button" className={button} disabled={disabled||busy||!reservationRoomId||!reservationRateId||!guestId} onClick={event=>void reserve(event as unknown as React.FormEvent,true)}>Walk in and check in</button></div><p className="text-xs text-slate-500">Room availability and overlapping reservations are rechecked in one API transaction. Rates are snapshotted when confirmed.</p></form>}
  <section className="space-y-3"><h3 className="text-lg font-semibold">Reservations and stays</h3>{reservations.map(reservation=>{
   const guest=customers.find(row=>row.id===reservation.data.customerId),room=rooms.find(row=>row.id===reservation.data.roomId);
   return <article key={reservation.id} className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="font-semibold">{guest?String(guest.data.name):'Guest details restricted'} · Room {String(room?.data.number||'unavailable')}</h4><p className="mt-1 text-sm text-slate-400">{String(reservation.data.status)} · {new Date(String(reservation.data.startsAt)).toLocaleString()} – {new Date(String(reservation.data.endsAt)).toLocaleString()}</p><p className="text-sm">{String(reservation.data.guests)} guests · quoted {money(reservation.data.quotedAmountMinor)} · {String(reservation.data.stayType)}</p></div><div className="flex flex-wrap gap-2">{reservation.data.status==='RESERVED'&&<>{canOperate&&<button className={button} disabled={disabled||busy} onClick={()=>void checkIn(reservation)}>Check in</button>}{canOperate&&<button className={button} disabled={disabled||busy} onClick={()=>void cancel(reservation)}>Cancel</button>}{canManage&&new Date(String(reservation.data.endsAt))<new Date()&&<button className={button} disabled={disabled||busy} onClick={()=>void run('roomReservation.noShow','roomReservations',reservation.id,{id:reservation.id,expectedVersions:[baseline(reservation)]},'Reservation marked no-show.')}>Mark no-show</button>}{!folios.some(folio=>folio.id===reservation.id)&&allowed(session,'folio.manage')&&<button className={button} disabled={disabled||busy} onClick={()=>void run('folio.open','folios',reservation.id,{id:reservation.id},'Guest folio opened.')}>Open folio</button>}<button className={button} disabled={disabled||busy} onClick={()=>void run('roomReservation.confirmation','businessDocuments',reservation.id,{id:reservation.id},'Reservation confirmation issued.')}>Issue confirmation</button></>}</div></div></article>;
  })}{reservations.length===0&&<p className="rounded border border-dashed border-slate-700 p-6 text-center text-sm text-slate-400">No reservations yet.</p>}</section>
 </section>;
}
