import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {Dialog} from '../../design-system/controls';
import {createServOSApiClient,type ApiImportBatch,type ApiImportPlan,type ApiImportRow,type ApiImportTemplate} from './apiClient';
import type {ImportTemplateKey} from '../../types/imports';

type Client=ReturnType<typeof createServOSApiClient>;
const button='rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm font-semibold hover:bg-slate-800 disabled:opacity-40';
const primary='rounded-lg bg-amber-400 px-3 py-2 text-sm font-bold text-slate-950 hover:bg-amber-300 disabled:opacity-40';
const input='w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white outline-none focus:border-amber-400';
const safeRows=(value:ApiImportRow[]|undefined)=>Array.isArray(value)?value:[];
const downloadCsv=(template:ApiImportTemplate)=>{const blob=new Blob([`${template.headers.join(',')}\r\n`],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`${template.key}.csv`;anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)};

export function WebApiImportCenter({client,disabled,canExecute}:{client:Client;disabled:boolean;canExecute:boolean}){
 const [templates,setTemplates]=useState<ApiImportTemplate[]>([]),[batches,setBatches]=useState<ApiImportBatch[]>([]),[selected,setSelected]=useState('products'),[file,setFile]=useState<File|null>(null),[plan,setPlan]=useState<ApiImportPlan|null>(null),[cancel,setCancel]=useState<ApiImportBatch|null>(null),[cancelReason,setCancelReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const template=useMemo(()=>templates.find(row=>row.key===selected),[templates,selected]);
 const refresh=useCallback(async()=>{const [catalog,current]=await Promise.all([client.importTemplates(),client.importBatches()]);setTemplates(catalog.templates);setBatches(current.batches)},[client]);
 useEffect(()=>{let active=true;void refresh().catch(cause=>{if(active)setError(cause instanceof Error?cause.message:'API import data could not be loaded.')});return()=>{active=false}},[refresh]);
 const act=async(label:string,work:()=>Promise<unknown>)=>{setBusy(true);setError('');setNotice('');try{await work();await refresh();setNotice(label)}catch(cause){setError(cause instanceof Error?cause.message:'The API import operation failed.')}finally{setBusy(false)}};
 const stage=async()=>{if(!file||!template)return;if(file.size>2*1024*1024){setError('Choose a CSV file no larger than 2 MB.');return}const csvText=await file.text();await act('CSV staged. Review the row validation and run a server dry run.',async()=>{const result=await client.stageImport({id:crypto.randomUUID(),templateKey:template.key,fileName:file.name,csvText});setPlan(null);setFile(null);setBatches(current=>[result.batch,...current.filter(batch=>batch.id!==result.batch.id)])})};
 const openPlan=async(batch:ApiImportBatch)=>{await act('Server dry run complete. Review every row before applying.',async()=>{const result=await client.planImport(batch.id);setPlan(result.plan)})};
 const apply=async(batch:ApiImportBatch)=>{await act('API import application finished. Confirm the row results and reload the workspace.',async()=>{const current=plan?.batchId===batch.id?plan:(await client.importBatch(batch.id)).plan;if(!current)throw new Error('The reviewed plan is unavailable. Run a new server dry run before applying.');const result=await client.applyImport(current.id);setPlan(result.plan)})};
 const cancelBatch=async()=>{if(!cancel||cancelReason.trim().length<3)return;await act('Unapplied source CSV purged; the cancellation event was retained.',async()=>{await client.cancelImport(cancel.id,cancelReason.trim());setCancel(null);setCancelReason('');setPlan(null)})};
 const loadBatch=async(batch:ApiImportBatch)=>{try{const refreshed=await client.importBatch(batch.id);setBatches(current=>current.map(row=>row.id===batch.id?refreshed.batch:row));if(refreshed.plan)setPlan(refreshed.plan)}catch{/* The batch list remains useful if its source was purged after apply. */}};
 return <section className="space-y-5" aria-labelledby="api-import-title">
  <header><h2 id="api-import-title" className="text-xl font-bold">API controlled CSV import</h2><p className="mt-1 max-w-3xl text-sm text-slate-400">Stage supported master data, validate it against the live API, then apply through audited ServOS domain commands. Imports are create-only; dependencies must be imported first. Opening stock, staff credentials, transactions, and history are not importable here.</p></header>
  <section className="grid gap-3 rounded-xl border border-slate-800 bg-slate-900/50 p-4 md:grid-cols-[minmax(0,1fr)_auto]">
   <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Template<select className={`${input} mt-1`} value={selected} onChange={event=>{setSelected(event.target.value);setPlan(null)}}>{templates.map(item=><option key={item.key} value={item.key} disabled={!item.importable}>{item.label}{item.importable?'':' · permission required'}</option>)}</select></label><label className="text-sm">CSV file<input className={`${input} mt-1`} type="file" accept=".csv,text/csv" onChange={event=>setFile(event.target.files?.[0]||null)}/></label></div>
   <div className="flex flex-wrap items-end gap-2"><button type="button" className={button} disabled={!template} onClick={()=>template&&downloadCsv(template)}>Download header template</button><button type="button" className={primary} disabled={disabled||busy||!file||!template?.importable} onClick={()=>void stage()}>{busy?'Working…':'Stage for review'}</button></div>
   {template&&<p className="text-xs text-slate-500 sm:col-span-2">Required columns: {template.required.join(', ')}. Limit: 2 MB and 20,000 rows. Header names must match the downloaded template.</p>}
  </section>
  {error&&<p role="alert" className="rounded-lg border border-rose-900 bg-rose-950/50 p-3 text-sm text-rose-200">{error}</p>}{notice&&<p role="status" className="rounded-lg border border-emerald-900 bg-emerald-950/40 p-3 text-sm text-emerald-200">{notice}</p>}
  <section className="space-y-3"><h3 className="font-semibold">Staged batches</h3>{batches.length===0?<p className="text-sm text-slate-400">No API import batches have been staged.</p>:batches.map(batch=>{const cancellable=['STAGED','DRY_RUN_READY','DRY_RUN_BLOCKED'].includes(batch.status),canPlan=['STAGED','DRY_RUN_READY','DRY_RUN_BLOCKED'].includes(batch.status);return <article key={batch.id} className="rounded-xl border border-slate-700 bg-slate-950/50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="font-semibold">{batch.fileName}</h4><p className="mt-1 text-xs text-slate-400">{batch.templateKey} · {batch.status} · {batch.rowCount} rows · {batch.validCount} valid · {batch.invalidCount} invalid</p><p className="mt-1 text-xs text-slate-500">SHA-256 {batch.sourceHash}</p></div><div className="flex flex-wrap gap-2">{canPlan&&<button className={button} disabled={disabled||busy} onClick={()=>void openPlan(batch)}>Run server dry run</button>}{(batch.status==='DRY_RUN_READY'||batch.status==='APPLYING')&&canExecute&&<button className={primary} disabled={disabled||busy||batch.status==='DRY_RUN_READY'&&plan?.batchId===batch.id&&plan.status!=='READY'} onClick={()=>void apply(batch)}>{batch.status==='APPLYING'?'Resume application':'Apply reviewed import'}</button>}{cancellable&&<button className={`${button} border-rose-900 text-rose-200`} disabled={disabled||busy} onClick={()=>{setCancel(batch);setCancelReason('')}}>Cancel batch</button>}</div></div>
   {batch.status==='DRY_RUN_READY'&&canExecute&&!plan&&<p className="mt-2 text-xs text-amber-200">Load the plan with “Run server dry run” before applying.</p>}
   {plan?.batchId===batch.id&&<div className="mt-4 space-y-2 border-t border-slate-800 pt-3"><div className="flex flex-wrap justify-between gap-2 text-sm"><strong>Plan: {plan.status}</strong><span>{plan.summary.applied} applied · {plan.summary.blocked+plan.summary.conflict} blocked · {plan.summary.failed} failed</span></div>{plan.steps.map(step=><div key={step.rowNumber} className="rounded bg-slate-900 px-3 py-2 text-xs"><span className={step.status==='PLANNED'||step.status==='APPLIED'?'text-emerald-300':'text-rose-300'}>Row {step.rowNumber} · {step.action} · {step.status}</span><span className="ml-2 text-slate-300">{step.reason}</span></div>)}{plan.stepsTruncated&&<p className="text-xs text-slate-500">Only the first 500 plan rows are shown.</p>}</div>}
   {canPlan&&<ImportPreview batch={batch} client={client} onLoad={loadBatch}/>}{batch.status==='APPLIED'&&<p className="mt-2 text-xs text-emerald-300">All rows applied. The raw CSV has been purged; the source hash and command outcomes remain.</p>}{batch.status==='PARTIAL'&&<p className="mt-2 text-xs text-amber-200">Some row commands applied and others failed. The plan retains per-row outcomes; reconcile before staging corrections.</p>}{batch.status==='CANCELLED'&&<p className="mt-2 text-xs text-slate-400">Raw CSV removed; cancellation evidence retained.</p>}
  </article>})}</section>
  {cancel&&<Dialog title="Cancel staged import" onClose={()=>{setCancel(null);setCancelReason('')}} footer={<><button className={button} onClick={()=>setCancel(null)}>Keep batch</button><button className="rounded-lg bg-rose-600 px-3 py-2 text-sm font-bold text-white disabled:opacity-40" disabled={busy||cancelReason.trim().length<3} onClick={()=>void cancelBatch()}>Cancel and purge source</button></>}><p className="text-sm text-slate-300">This removes the staged CSV and plan. Applied batches cannot be cancelled.</p><label className="mt-3 block text-sm">Reason<textarea className={`${input} mt-1`} rows={3} value={cancelReason} onChange={event=>setCancelReason(event.target.value)}/></label></Dialog>}
 </section>;
}

function ImportPreview({batch,client,onLoad}:{batch:ApiImportBatch;client:Client;onLoad:(batch:ApiImportBatch)=>Promise<void>}){
 const [rows,setRows]=useState<ApiImportRow[]>([]),[busy,setBusy]=useState(false);
 const load=async()=>{if(batch.rows){setRows(safeRows(batch.rows));return}setBusy(true);try{const result=await client.importBatch(batch.id);setRows(safeRows(result.batch.rows));await onLoad(batch)}finally{setBusy(false)}};
 if(batch.status==='APPLIED'||batch.status==='PARTIAL'||batch.status==='CANCELLED')return null;
 return <div className="mt-3 border-t border-slate-800 pt-3"><details onToggle={event=>{if((event.currentTarget as HTMLDetailsElement).open&&!rows.length)void load()}}><summary className="cursor-pointer text-sm text-slate-300">{busy?'Loading preview…':`CSV preview (${rows.length||batch.rowCount} rows total)`}</summary><div className="mt-2 max-h-56 space-y-1 overflow-auto">{rows.slice(0,20).map(row=><div key={row.rowNumber} className="rounded bg-slate-900 px-2 py-1 text-xs"><span className={row.status==='VALID'?'text-emerald-300':'text-rose-300'}>Row {row.rowNumber} · {row.status}</span><span className="ml-2 text-slate-400">{row.errors.join(' ')}</span></div>)}{rows.length>20&&<p className="text-xs text-slate-500">Showing the first 20 preview rows here; the server dry run reviews the complete file.</p>}</div></details></div>
}
