import React,{useEffect,useRef,useState} from 'react';
import {allowed,type BusinessRecord,type WebSession} from './session';
import type {QueuedCommand} from './BusinessStore';
import type {CommandOutcome} from '../../types/transactions';
import {parseMoneyToMinor} from '../../utils/fiscal';
const input='mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2',button='rounded border border-slate-600 px-3 py-2 disabled:opacity-40';
export function WebApiSupplierCredits({records,session,queue,disabled,command}:{records:BusinessRecord[];session:WebSession;queue:QueuedCommand[];disabled:boolean;command:(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<CommandOutcome>}){
 const [creditId,setCreditId]=useState(''),[payableId,setPayableId]=useState(''),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[pending,setPending]=useState(''),[message,setMessage]=useState('');const inFlight=useRef(false);
 const unresolved=queue.some(row=>(row.command.operation.startsWith('procurement.')||row.command.operation.startsWith('supplierPayable.')||row.command.operation.startsWith('supplierReturn.')||row.command.operation.startsWith('supplierCredit.'))&&['PENDING_SYNC','OUTCOME_UNKNOWN'].includes(row.state)),blocked=disabled||busy||unresolved||Boolean(pending),manage=allowed(session,'procurement.manage');
 const credits=records.filter(row=>row.collection==='supplierCredits'&&Number(row.data.availableMinor)>0),credit=credits.find(row=>row.id===creditId),payables=records.filter(row=>row.collection==='supplierPayables'&&row.data.supplierId===credit?.data.supplierId&&Number(row.data.outstandingMinor)>0&&row.data.status!=='REVERSED'),payable=payables.find(row=>row.id===payableId);
 useEffect(()=>{if(!pending)return;const row=queue.find(entry=>entry.id===pending);if(!row||!['SYNCHRONIZED','REJECTED','CONFLICT'].includes(row.state))return;setPending('');setCreditId('');setPayableId('');setMessage(row.state==='SYNCHRONIZED'?'Supplier credit application confirmed.':row.result?.error?.message||'Review current credit and payable balances.');},[pending,queue]);
 const apply=async(event:React.FormEvent)=>{event.preventDefault();if(!credit||!payable||blocked||inFlight.current||!manage||!ack)return;inFlight.current=true;setBusy(true);setMessage('');try{const amountMinor=parseMoneyToMinor(amount);if(amountMinor<=0||amountMinor>Number(credit.data.availableMinor)||amountMinor>Number(payable.data.outstandingMinor))throw new Error('Application must fit both available credit and payable balance.');const id=crypto.randomUUID();const outcome=await command('supplierCredit.apply','supplierCreditApplications',id,{id,creditNoteId:credit.id,payableId:payable.id,amountMinor,reason:reason.trim(),expectedVersions:[{collection:'supplierCreditApplications',id,version:0},{collection:'supplierCredits',id:credit.id,version:credit.version},{collection:'supplierPayables',id:payable.id,version:payable.version}]});if(outcome.kind==='CONFIRMED'){setCreditId('');setPayableId('');setAmount('');setReason('');setAck(false);setMessage('Supplier credit applied to the reviewed payable.');}else{if(outcome.kind==='PENDING'||outcome.kind==='OUTCOME_UNKNOWN')setPending(outcome.commandId);setMessage('message' in outcome?outcome.message:'Recover the original credit application in Activity.');}}catch(error){setMessage(error instanceof Error?error.message:'Cannot apply supplier credit.');}finally{inFlight.current=false;setBusy(false);}};
 return <section className="space-y-4" aria-label="Supplier credit balances"><h2 className="text-xl font-bold">Supplier credit balances</h2><p>Apply an available credit note to a payable for the same supplier. This records accounting allocation; it does not initiate a refund.</p>{unresolved&&<p role="status">Recover the original procurement action before applying another supplier credit.</p>}
 {records.filter(row=>row.collection==='supplierCredits').map(row=><article key={row.id} className="rounded border border-slate-700 p-3"><p>{String(row.data.reference)} - Available KES {(Number(row.data.availableMinor)/100).toFixed(2)}</p><p>Credit date: {String(row.data.creditDate)}; applied KES {(Number(row.data.appliedMinor)/100).toFixed(2)}</p></article>)}
 {manage&&credits.length>0&&<form aria-label="Apply supplier credit" onSubmit={event=>void apply(event)} className="space-y-3 rounded border border-slate-700 p-4"><h3 className="font-bold">Apply available supplier credit</h3><fieldset disabled={blocked} className="space-y-3"><label className="block">Supplier credit<select required className={input} value={creditId} onChange={event=>{setCreditId(event.target.value);setPayableId('');}}><option value="">Choose credit</option>{credits.map(row=><option key={row.id} value={row.id}>{String(row.data.reference)} - KES {(Number(row.data.availableMinor)/100).toFixed(2)}</option>)}</select></label><label className="block">Same-supplier payable<select required className={input} value={payableId} onChange={event=>setPayableId(event.target.value)}><option value="">Choose payable</option>{payables.map(row=><option key={row.id} value={row.id}>{String(row.data.invoiceNumber||row.data.goodsReceiptId)} - KES {(Number(row.data.outstandingMinor)/100).toFixed(2)} outstanding</option>)}</select></label><label className="block">Amount to apply (KES)<input required inputMode="decimal" className={input} value={amount} onChange={event=>setAmount(event.target.value)}/></label><label className="block">Reason<textarea required minLength={3} maxLength={500} className={input} value={reason} onChange={event=>setReason(event.target.value)}/></label><label className="block"><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/> I reviewed the same-supplier credit and payable balances and confirm this allocation.</label><button className={button} disabled={!ack||!credit||!payable}>Apply reviewed credit</button></fieldset></form>}
 {records.filter(row=>row.collection==='supplierCreditApplications').map(row=><p key={row.id}>Applied KES {(Number(row.data.amountMinor)/100).toFixed(2)} from credit {String(row.data.creditNoteId)} to payable {String(row.data.payableId)}.</p>)}{message&&<p role="status">{message}</p>}</section>;
}
