import React,{useEffect,useRef,useState} from 'react';
import {allowed,type BusinessRecord,type WebSession} from './session';
import type {QueuedCommand} from './BusinessStore';
import type {CommandOutcome} from '../../types/transactions';
import {inventoryRevisions} from './inventoryRevisions';
type Row={id:string;stockItemId:string;name:string;unit:string;remaining:number;bottle:boolean;delivered:string;accepted:string;rejected:string;rejectionReason:string;sealedContainers:string;openQuantity:string};
type Review={id:string;po:BusinessRecord;records:BusinessRecord[];rows:Row[]};
const obj=(v:unknown):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{};
const input='mt-1 w-full rounded border border-slate-700 bg-slate-950 p-2';
const button='rounded border border-slate-600 px-3 py-2 disabled:opacity-40';
const quantity=(value:string)=>{if(!/^\d+(?:\.\d{1,6})?$/.test(value)||Number(value)>1e9)throw new Error('Use non-negative quantities with at most six decimals.');return Number(value);};
export function WebApiGoodsReceipts({records,session,queue,disabled,command}:{records:BusinessRecord[];session:WebSession;queue:QueuedCommand[];disabled:boolean;command:(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<CommandOutcome>}){
 const [review,setReview]=useState<Review|null>(null),[location,setLocation]=useState(''),[reference,setReference]=useState(''),[reason,setReason]=useState(''),[over,setOver]=useState(false),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[pending,setPending]=useState(''),[message,setMessage]=useState('');const submitting=useRef(false);
 const unresolved=queue.some(row=>row.command.operation.startsWith('procurement.')&&['PENDING_SYNC','OUTCOME_UNKNOWN'].includes(row.state));
 const blocked=disabled||busy||unresolved||Boolean(pending),receive=allowed(session,'procurement.receive');
 useEffect(()=>{if(!pending)return;const result=queue.find(row=>row.id===pending);if(!result||!['SYNCHRONIZED','REJECTED','CONFLICT'].includes(result.state))return;setPending('');setReview(null);setMessage(result.state==='SYNCHRONIZED'?'Original goods receipt confirmed.':result.result?.error?.message||'Review the latest purchase order before another receiving action.');},[pending,queue]);
 const open=(po:BusinessRecord)=>{setReview({id:crypto.randomUUID(),po,records,rows:(Array.isArray(po.data.items)?po.data.items:[]).map(value=>{const line=obj(value),stock=obj(line.stockSnapshot),pack=obj(line.purchasePackageSnapshot);return {id:String(line.id),stockItemId:String(line.stockItemId),name:String(stock.name),unit:String(pack.name||stock.baseUnit),remaining:Math.max(0,Number(line.quantityOrdered)-Number(line.quantityReceived)),bottle:Number(stock.sealedContainerSize)>0,delivered:'0',accepted:'0',rejected:'0',rejectionReason:'',sealedContainers:'0',openQuantity:'0'};})});setLocation('');setReference('');setReason('');setOver(false);setAck(false);setMessage('');};
 const patch=(id:string,change:Partial<Row>)=>setReview(current=>current?{...current,rows:current.rows.map(row=>row.id===id?{...row,...change}:row)}:null);
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!review||blocked||submitting.current||!receive||!ack)return;submitting.current=true;setBusy(true);setMessage('');try{
  const items=review.rows.map(row=>{const delivered=quantity(row.delivered),accepted=quantity(row.accepted),rejected=quantity(row.rejected);if(Math.round(delivered*1e6)!==Math.round(accepted*1e6)+Math.round(rejected*1e6))throw new Error('Delivered quantity must equal accepted plus rejected.');if(accepted>row.remaining&&(!over||!allowed(session,'procurement.over_receive')))throw new Error('Over-receiving requires permission and explicit review.');return {purchaseOrderLineId:row.id,quantityDelivered:delivered,quantityAccepted:accepted,quantityRejected:rejected,rejectionReason:row.rejectionReason,...(accepted>0&&row.bottle?{sealedContainers:quantity(row.sealedContainers),openQuantity:quantity(row.openQuantity)}:{})};}).filter(row=>row.quantityDelivered>0);
  if(!items.length)throw new Error('Enter at least one delivered line.');
  const stockIds=review.rows.filter(row=>quantity(row.accepted)>0).map(row=>row.stockItemId),revisions=inventoryRevisions(review.records,stockIds,[location]);
  const policy=review.records.find(row=>row.collection==='inventoryPolicy'&&row.id===session.businessId);
  const outcome=await command('procurement.receive','goodsReceipts',review.id,{id:review.id,purchaseOrderId:review.po.id,locationId:location,deliveryReference:reference.trim(),reason:reason.trim(),overReceiveAcknowledged:over,items,expectedBalanceVersions:revisions.expectedBalanceVersions,expectedVersions:[{collection:'goodsReceipts',id:review.id,version:0},{collection:'purchaseOrders',id:review.po.id,version:review.po.version},{collection:'inventoryPolicy',id:session.businessId,version:policy?.version??0},...revisions.expectedVersions]});
  if(outcome.kind==='CONFIRMED'){setReview(null);setMessage('Goods receipt confirmed. Only accepted quantities were posted to stock.');}else{if(outcome.kind==='PENDING'||outcome.kind==='OUTCOME_UNKNOWN')setPending(outcome.commandId);setMessage('message' in outcome?outcome.message:'Recover the original receiving command in Activity.');}
 }catch(error){setMessage(error instanceof Error?error.message:'Cannot receive this delivery.');}finally{submitting.current=false;setBusy(false);}};
 return <section className="space-y-4" aria-label="Goods receiving"><h2 className="text-xl font-bold">Receive purchase deliveries</h2><p>Receiving posts accepted stock and creates an immutable GRN. It does not record a supplier invoice or payment.</p>{unresolved&&<p role="status">Recover the original procurement action in Activity before another receiving action.</p>}
 {receive&&records.filter(row=>row.collection==='purchaseOrders'&&['ISSUED','PARTIALLY_RECEIVED'].includes(String(row.data.status))).map(po=><button key={po.id} className={button} disabled={blocked} onClick={()=>open(po)}>Receive {String(po.data.documentNumber)}</button>)}
 {review&&<form onSubmit={event=>void submit(event)} aria-label="Review goods receipt" className="space-y-4 rounded border border-slate-700 p-4"><h3 className="font-bold">{String(review.po.data.documentNumber)}</h3><fieldset disabled={blocked} className="space-y-4">
 <label className="block">Receiving location<select required className={input} value={location} onChange={event=>setLocation(event.target.value)}><option value="">Choose location</option>{review.records.filter(row=>row.collection==='stockLocations'&&!row.archived).map(row=><option key={row.id} value={row.id}>{String(row.data.name)}</option>)}</select></label>
 <label className="block">Supplier delivery reference<input required maxLength={160} className={input} value={reference} onChange={event=>setReference(event.target.value)}/></label>
 {review.rows.map(row=><fieldset key={row.id} className="rounded border border-slate-700 p-3"><legend>{row.name} - remaining {row.remaining} {row.unit}</legend><div className="grid gap-3 sm:grid-cols-3">{(['delivered','accepted','rejected'] as const).map(key=><label key={key}>{key}<input required inputMode="decimal" className={input} value={row[key]} onChange={event=>patch(row.id,{[key]:event.target.value})}/></label>)}</div>{Number(row.rejected)>0&&<label className="block">Rejection reason<input required minLength={3} maxLength={500} className={input} value={row.rejectionReason} onChange={event=>patch(row.id,{rejectionReason:event.target.value})}/></label>}{row.bottle&&Number(row.accepted)>0&&<div className="grid gap-3 sm:grid-cols-2"><label>Sealed containers<input required inputMode="numeric" className={input} value={row.sealedContainers} onChange={event=>patch(row.id,{sealedContainers:event.target.value})}/></label><label>Open base quantity<input required inputMode="decimal" className={input} value={row.openQuantity} onChange={event=>patch(row.id,{openQuantity:event.target.value})}/></label></div>}</fieldset>)}
 {allowed(session,'procurement.over_receive')&&<label className="block"><input type="checkbox" checked={over} onChange={event=>setOver(event.target.checked)}/> I explicitly authorize accepted quantities above this order's remaining quantities.</label>}
 <label className="block">Receiving reason<textarea required minLength={3} maxLength={500} className={input} value={reason} onChange={event=>setReason(event.target.value)}/></label><label className="block"><input type="checkbox" checked={ack} onChange={event=>setAck(event.target.checked)}/> I reviewed the physical delivery, accepted quantities, rejections and receiving location.</label>
 <button className={button} disabled={!ack}>Confirm reviewed goods receipt</button></fieldset><button type="button" className={button} disabled={busy||Boolean(pending)} onClick={()=>setReview(null)}>Close</button></form>}
 {message&&<p role="status">{message}</p>}
 <h3 className="font-bold">Confirmed goods receipts</h3>{records.filter(row=>row.collection==='goodsReceipts').map(row=><article key={row.id} className="rounded border border-slate-700 p-3"><p>{String(row.data.documentNumber)} - {String(row.data.deliveryReference)}</p><p>Accepted value KES {(Number(row.data.acceptedTotalMinor)/100).toFixed(2)}</p></article>)}
 </section>;
}
