import React,{useEffect,useRef,useState} from 'react';
import {Activity,BedDouble,Boxes,CheckCircle2,ChevronRight,ClipboardCheck,CreditCard,HelpCircle,Home,LockKeyhole,LogIn,Martini,PackageSearch,RefreshCw,Settings,ShieldCheck,Truck,Users,WalletCards,Wifi,WifiOff} from 'lucide-react';
import {BusinessStore,type QueuedCommand} from './BusinessStore';
import {startAutomaticSync,synchronizeStore} from './sync';
import {allowed,loadAuthorizedSnapshot,openWebDevice,type BusinessRecord,type Rpc,type WebGuidanceProgress,type WebSession} from './session';

const WebCatalogView=React.lazy(()=>import('./WebCatalogInventory').then(module=>({default:module.WebCatalogView})));
const WebInventoryView=React.lazy(()=>import('./WebCatalogInventory').then(module=>({default:module.WebInventoryView})));
const WebProcurementView=React.lazy(()=>import('./WebProcurementView').then(module=>({default:module.WebProcurementView})));
const WebPosView=React.lazy(()=>import('./WebPosView').then(module=>({default:module.WebPosView})));
const WebFinanceView=React.lazy(()=>import('./WebFinanceView').then(module=>({default:module.WebFinanceView})));
const WebStaffAdminView=React.lazy(()=>import('./WebStaffAdminView').then(module=>({default:module.WebStaffAdminView})));
const WebAdministrationView=React.lazy(()=>import('./WebAdministrationView').then(module=>({default:module.WebAdministrationView})));
const WebKDSView=React.lazy(()=>import('./WebKDSView').then(module=>({default:module.WebKDSView})));
const WebRefundsView=React.lazy(()=>import('./WebRefundsView').then(module=>({default:module.WebRefundsView})));
const WebFinancialControlsView=React.lazy(()=>import('./WebFinancialControlsView').then(module=>({default:module.WebFinancialControlsView})));
const WebMasterDataView=React.lazy(()=>import('./WebMasterDataView').then(module=>({default:module.WebMasterDataView})));
const WebGuidedTour=React.lazy(()=>import('./WebGuidanceViews').then(module=>({default:module.WebGuidedTour})));
const WebHelpView=React.lazy(()=>import('./WebGuidanceViews').then(module=>({default:module.WebHelpView})));
const WebStartHere=React.lazy(()=>import('./WebGuidanceViews').then(module=>({default:module.WebStartHere})));
const WebLifecycleView=React.lazy(()=>import('./WebLifecycleViews').then(module=>({default:module.WebLifecycleView})));
const WebStaffWelcome=React.lazy(()=>import('./WebLifecycleViews').then(module=>({default:module.WebStaffWelcome})));
const WebFrontDeskView=React.lazy(()=>import('./WebHospitalityViews').then(module=>({default:module.WebFrontDeskView})));
const WebGuestAccountsView=React.lazy(()=>import('./WebHospitalityViews').then(module=>({default:module.WebGuestAccountsView})));
const WebHousekeepingView=React.lazy(()=>import('./WebHospitalityViews').then(module=>({default:module.WebHousekeepingView})));
import {ActivitySyncCenter} from './ActivitySyncCenter';
import {ConnectivityBadge,Notice,PageHeader,StatusBadge} from '../../design-system/components';
import {ds} from '../../design-system/tokens';
import {canSeeWorkspace,visibleWorkspaces,workspaceById,workspaceGroups} from './workspaceRegistry';
type Values=Record<string,string>;
type Field={key:string;label:string;type?:'text'|'number'|'money'|'datetime-local'|'select';options?:Array<{value:string;label:string}>;value?:string;optional?:boolean};
type Editor={title:string;operation:string;collection:string;id:string;fields:Field[];payload:(values:Values)=>Record<string,unknown>};
const input='w-full rounded-lg border border-slate-600 bg-slate-950 p-2 text-white';
const button='inline-flex items-center justify-center gap-2 rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-sm font-semibold text-slate-200 transition hover:border-slate-600 hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-40';
const primaryButton='inline-flex items-center justify-center gap-2 rounded-xl bg-amber-400 px-4 py-2.5 text-sm font-bold text-slate-950 transition hover:bg-amber-300 disabled:cursor-not-allowed disabled:opacity-40';
const label=(r:BusinessRecord)=>String(r.data.name||r.data.number||r.data.tag||r.id);
const money=(value:unknown)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES'}).format(Number(value||0)/100);
const minor=(value:string)=>Math.round(Number(value)*100);
type WorkspaceTab='Home'|'POS'|'KDS'|'Catalog'|'Inventory'|'Procurement'|'Front Desk'|'Guest Accounts'|'Housekeeping'|'Rooms'|'Assets'|'Master Data'|'Refunds'|'Finance Controls'|'Settings'|'Finance'|'Staff'|'Administration'|'Activity'|'Help';
const tabPermissions:Record<WorkspaceTab,string[]>={Home:[],POS:['pos.sell','records.view'],KDS:['kds.view'],Catalog:['catalog.view','catalog.manage'],Inventory:['inventory.view','inventory.adjust','inventory.receive'],Procurement:['procurement.view','procurement.manage','procurement.receive'],'Front Desk':['rooms.view','rooms.operate'],'Guest Accounts':['folio.view','folio.manage','payment.record'],'Housekeeping':['rooms.view','rooms.operate'],Rooms:['rooms.view','rooms.manage','rooms.operate'],Assets:['assets.view','assets.manage'],'Master Data':['customers.manage','suppliers.manage','roomTypes.manage','assetCategories.manage'],Refunds:['order.refund','payment.reverse'],'Finance Controls':['credit.view','credit.manage','credit.settle','credit.reconcile','mpesa.reconcile'],Settings:['customers.manage','roomTypes.manage','assetCategories.manage'],Finance:['reports.view','till.view'],Staff:['staff.view','devices.manage'],Administration:['business.view','business.configure','data.import.view','reports.view','staff.create','backup.create'],Activity:['records.view'],Help:['help.view']};
const canSeeTab=(session:WebSession,tab:WorkspaceTab)=>canSeeWorkspace(session,workspaceById(tab));
const workspaceNavigation=[
 {group:'Start',items:[{id:'Home',icon:Home},{id:'Help',icon:HelpCircle}]},
  {group:'Operations',items:[{id:'POS',icon:Martini},{id:'KDS',icon:ClipboardCheck},{id:'Inventory',icon:Boxes},{id:'Procurement',icon:Truck},{id:'Front Desk',icon:LogIn},{id:'Guest Accounts',icon:WalletCards},{id:'Housekeeping',icon:ClipboardCheck},{id:'Rooms',icon:BedDouble}]},
  {group:'Management',items:[{id:'Catalog',icon:PackageSearch},{id:'Assets',icon:ShieldCheck},{id:'Master Data',icon:Users},{id:'Refunds',icon:CreditCard},{id:'Finance Controls',icon:WalletCards},{id:'Finance',icon:CreditCard}]},
 {group:'System',items:[{id:'Settings',icon:Settings},{id:'Staff',icon:Users},{id:'Administration',icon:ShieldCheck},{id:'Activity',icon:Activity}]},
] as const;
const tabDescriptions:Record<WorkspaceTab,string>={
  Home:'Choose a task or find a guide.',POS:'Take orders and record payments.',KDS:'Move orders through the bar, kitchen, or service pass.',Catalog:'Manage the items and stock available to your business.',Inventory:'Review stock levels and record counts, transfers, or waste.',Procurement:'Buy supplies and record what arrived.','Front Desk':'Manage arrivals, current stays, departures, and room moves.','Guest Accounts':'Settle guest folios, deposits, accommodation, and services.',Housekeeping:'Move rooms through readiness and maintenance states.',Rooms:'Set up rooms, rates, reservations, and availability.',Assets:'Track property items and their operational history.','Master Data':'Keep guests, suppliers, room types, and categories ready to use.',Refunds:'Review paid transactions and record controlled refunds.','Finance Controls':'Reconcile M-Pesa and manage customer accounts, settlements, and write-offs.',Settings:'Maintain business records used by operations.',Finance:'Manage till activity and review close-day reports.',Staff:'Manage staff access, approvals, and devices.',Administration:'Manage imports, reports, business settings, Auth lifecycle and readiness.',Activity:'Review saved changes and anything still waiting to sync.',Help:'Find a simple guide for the task you need.',
};

export function WebBusinessApp({initialSession,rpc,onSignOut}:{initialSession:WebSession;rpc:Rpc;onSignOut:()=>void}){
 const [session,setSession]=useState(initialSession);const [records,setRecords]=useState<BusinessRecord[]>([]);const [queue,setQueue]=useState<QueuedCommand[]>([]);
 const [drafts,setDrafts]=useState<Array<{id:string;operation:string;payload:Record<string,unknown>;updatedAt:string}>>([]);
 const [tab,setTab]=useState<WorkspaceTab>('Home');const [helpQuery,setHelpQuery]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [ready,setReady]=useState(false);const [busy,setBusy]=useState(false);const [syncing,setSyncing]=useState(false);const [online,setOnline]=useState(()=>typeof navigator==='undefined'||navigator.onLine);const [tourOpen,setTourOpen]=useState(false);const [guidance,setGuidance]=useState<WebGuidanceProgress[]>([]);const [lifecycleRefresh,setLifecycleRefresh]=useState(0);
 const [editor,setEditor]=useState<Editor|null>(null);const [values,setValues]=useState<Values>({});
 const store=useRef<BusinessStore|null>(null);const rpcRef=useRef(rpc);rpcRef.current=rpc;const sessionRef=useRef(session);sessionRef.current=session;
 const syncRef=useRef<()=>Promise<void>>(async()=>{});
 const refresh=async()=>{if(!store.current)return;const [r,q,d]=await Promise.all([store.current.records(),store.current.queue(),store.current.drafts()]);setRecords(r);setQueue(q);setDrafts(d)};
  useEffect(()=>{
  let stopped=false;let needsSnapshot=true;let automatic:ReturnType<typeof startAutomaticSync>|undefined;let opened:BusinessStore|undefined;
  const run=async()=>{
    let latest:WebSession;try{latest=await rpcRef.current('rpc/servos_v2_session',{})}catch(error){if([401,403].includes((error as {status?:number}).status||0)){setReady(false);setRecords([])}throw error}
    if(latest.businessId!==initialSession.businessId||latest.actorId!==initialSession.actorId){setReady(false);setRecords([]);throw new Error('This workspace is no longer enabled for this session. Sign in again.')}
    sessionRef.current=latest;if(!stopped)setSession(latest);
    if(latest.lifecycleStage&&latest.lifecycleStage!=='LIVE'){
      setReady(false);setRecords([]);return;
    }
    if(!latest.enabled){setReady(false);setRecords([]);throw new Error('This workspace is not enabled for this session. Sign in again.')}
    if(!opened||stopped)return;
   if(needsSnapshot||latest.policyVersion!==await opened.policyVersion()){
    setReady(false);setRecords([]);await navigator.locks.request(`servos-v2-sync:${opened.scope}:${opened.deviceId}:${opened.actorId}`,()=>loadAuthorizedSnapshot(opened!,rpcRef.current,latest));needsSnapshot=false;
   }
   await synchronizeStore(opened,{execute:command=>rpcRef.current('rpc/servos_v2_execute',{command}),pull:cursor=>rpcRef.current('rpc/servos_v2_pull',{after_sequence:cursor,page_size:100})});
   if(!stopped){await refresh();setReady(true);setError('')}
  };
  syncRef.current=run;
  void(async()=>{try{
   const latest=await rpcRef.current('rpc/servos_v2_session',{}) as WebSession;
   if(latest.lifecycleStage&&latest.lifecycleStage!=='LIVE'){await run();return}
   opened=await openWebDevice(initialSession,rpcRef.current);if(stopped){opened.close();return}store.current=opened;
   automatic=startAutomaticSync(run,e=>{if(!stopped){setError(String(e));if((e as {status?:number}).status===403){setReady(false);setRecords([])}}});
  }catch(e){if(!stopped)setError(String(e))}})();
  return()=>{stopped=true;automatic?.stop();opened?.close();store.current=null};
 },[initialSession.businessId,initialSession.actorId,lifecycleRefresh]);
  const syncNow=async()=>{setSyncing(true);try{await syncRef.current()}finally{setSyncing(false)}};
  useEffect(()=>{const handleOnline=()=>setOnline(true);const handleOffline=()=>setOnline(false);window.addEventListener('online',handleOnline);window.addEventListener('offline',handleOffline);return()=>{window.removeEventListener('online',handleOnline);window.removeEventListener('offline',handleOffline)}},[]);
 useEffect(()=>{let active=true;void rpcRef.current('rpc/servos_v2_guidance_progress',{}).then(rows=>{if(active)setGuidance(Array.isArray(rows)?rows:[])}).catch(()=>undefined);return()=>{active=false}},[session.businessId,session.actorId]);
 const saveGuidance=async(next:WebGuidanceProgress)=>{setGuidance(rows=>[next,...rows.filter(row=>row.guideId!==next.guideId)]);try{const saved=await rpcRef.current('rpc/servos_v2_guidance_save',{progress:next});setGuidance(rows=>[saved,...rows.filter(row=>row.guideId!==saved.guideId)])}catch{ /* local progress keeps the tour usable during an outage */ }};
 const active=(collection:string)=>records.filter(r=>r.collection===collection&&!r.archived);
 const find=(collection:string,id:string)=>records.find(r=>r.collection===collection&&r.id===id);
 const choices=(collection:string)=>active(collection).map(r=>({value:r.id,label:label(r)}));
 const select=(key:string,title:string,collection:string):Field=>({key,label:title,type:'select',options:choices(collection)});
 const open=(next:Editor)=>{setEditor(next);setValues(Object.fromEntries(next.fields.map(f=>[f.key,f.value??''])));setError('')};
 const submit=async(operation:string,collection:string,id:string,payload:Record<string,unknown>):Promise<boolean>=>{
  if(!store.current||!ready)return false;setBusy(true);setError('');setNotice('');
  try{
    if(!navigator.onLine){await store.current.saveDraft(crypto.randomUUID(),operation,payload);setNotice('Saved on this browser. It will be sent when you are back online.');await refresh();setEditor(null);return false}
   const baselines=records.map(({collection,id,version})=>({collection,id,version}));
    for(const target of [collection,...(operation.startsWith('stay.')?['folios','stays']:[])])if(!baselines.some(r=>r.collection===target&&r.id===id))baselines.push({collection:target,id,version:0});
    for(const [target,targetId] of [['folios',String(payload.folioId||'')],['tables',String(payload.sourceTableId||'')],['tables',String(payload.targetTableId||'')],['orders',String(payload.targetOrderId||'')]] as Array<[string,string]>)if(targetId&&!baselines.some(r=>r.collection===target&&r.id===targetId)){const record=records.find(row=>row.collection===target&&row.id===targetId);baselines.push({collection:target,id:targetId,version:record?.version||0})}
    const command=await store.current.enqueue(operation,payload,baselines);setEditor(null);setNotice('Saved on this browser; waiting to sync.');await refresh();
   try{await syncRef.current()}catch(e){setError(`${String(e)}. The queued command is retained for retry.`);return false}
   const result=(await store.current.queue()).find(q=>q.id===command.id)?.result;
   if(result?.status==='SYNCHRONIZED'){setNotice('Saved and synchronized.');return true}
    setNotice('');setError(result?.error?.message||'This change is waiting to sync. See Saved changes.');return false
  }catch(e){setError(String(e));return false}finally{setBusy(false)}
 };
 const action=(title:string,operation:string,collection:string,id:string,fields:Field[]=[],extra:Record<string,unknown>={})=>open({title,operation,collection,id,fields,payload:v=>({id,...extra,...v})});
 const master=(collection:string,title:string,fields:Field[])=>{const id=crypto.randomUUID();open({title,operation:'record.save',collection,id,fields,payload:v=>({id,collection,data:{...v,...(collection==='roomTypes'?{maxGuests:Number(v.maxGuests)}:{}),...(collection==='suppliers'?{paymentTermsDays:Number(v.paymentTermsDays)}:{})}})})};
 const editRoom=(room?:BusinessRecord)=>{const id=room?.id||crypto.randomUUID();const fields:Field[]=[{key:'number',label:'Room number'},select('roomTypeId','Room type','roomTypes'),{key:'capacity',label:'Guest capacity',type:'number'},{key:'turnaroundMinutes',label:'Turnaround minutes',type:'number'}];open({title:room?'Edit room':'Add room',operation:'room.save',collection:'rooms',id,fields:fields.map(f=>({...f,value:String(room?.data[f.key]??(f.key==='turnaroundMinutes'?30:''))})),payload:v=>({id,data:{...v,capacity:Number(v.capacity),turnaroundMinutes:Number(v.turnaroundMinutes)}})})};
  const addRate=()=>{const id=crypto.randomUUID();open({title:'Add room stay rate',operation:'ratePlan.save',collection:'ratePlans',id,fields:[{key:'name',label:'Rate name'},select('roomTypeId','Room type','roomTypes'),{key:'mode',label:'Stay type',type:'select',options:[{value:'NIGHTLY',label:'Nightly'}],value:'NIGHTLY'},{key:'price',label:'Rate (KES, tax included)',type:'money'},{key:'taxBasisPoints',label:'Tax basis points (1600 = 16%)',type:'number',value:'0'}],payload:v=>({id,data:{name:v.name,roomTypeId:v.roomTypeId,mode:'NIGHTLY',priceMinor:minor(v.price),taxBasisPoints:Number(v.taxBasisPoints),currency:'KES'}})})};
  const reserve=(room:BusinessRecord)=>{const id=crypto.randomUUID();const property=active('property')[0]?.data||{};open({title:`Reserve room ${label(room)}`,operation:'roomReservation.create',collection:'roomReservations',id,fields:[select('customerId','Guest','customers'),{key:'stayType',label:'Stay type',type:'select',options:[{value:'NIGHTLY',label:`Nightly · checkout ${String(property.nightlyCheckoutTime||'10:00')}`},{value:'DAY',label:`Day stay · cutoff ${String(property.dayStayCutoffTime||'18:00')}`}],value:'NIGHTLY'},{key:'guests',label:'Guests',type:'number',value:'1'},{key:'startsAt',label:'Arrival (this device’s local time)',type:'datetime-local'},{key:'endsAt',label:'Departure (this device’s local time)',type:'datetime-local'}],payload:v=>({id,roomId:room.id,customerId:v.customerId,stayType:v.stayType,guests:Number(v.guests),startsAt:new Date(v.startsAt).toISOString(),endsAt:new Date(v.endsAt).toISOString()})})};
 const editAsset=(asset?:BusinessRecord)=>{const id=asset?.id||crypto.randomUUID();const fields:Field[]=[{key:'name',label:'Asset name'},{key:'tag',label:'Unique asset tag'},select('assetCategoryId','Category','assetCategories'),{...select('roomId','Room','rooms'),optional:true},{...select('locationId','Stock location','stockLocations'),optional:true},{key:'serialNumber',label:'Serial number',optional:true},{key:'purchaseCostMinor',label:'Acquisition cost (KES)',type:'money'}];open({title:asset?'Edit asset':'Add asset',operation:'asset.save',collection:'assets',id,fields:fields.map(f=>({...f,value:f.key==='purchaseCostMinor'?String(Number(asset?.data.purchaseCostMinor||0)/100):String(asset?.data[f.key]??'')})),payload:v=>({id,data:{...v,purchaseCostMinor:minor(v.purchaseCostMinor)}})})};
 const payment=(booking:BusinessRecord,deposit:boolean)=>open({title:deposit?'Record deposit':'Settle folio',operation:deposit?'folio.deposit':'folio.pay',collection:'folios',id:booking.id,fields:[select('accountId','Payment account','paymentAccounts'),{key:'amount',label:'Amount received (KES)',type:'money'},{key:'cashTendered',label:'Cash tendered (cash only)',type:'money',optional:true},{key:'reference',label:'External reference (non-cash)',optional:true},{key:'confirmation',label:'External payment confirmation',type:'select',optional:true,options:[{value:'confirmed',label:'I have manually verified receipt of funds'}]}],payload:v=>({id:booking.id,accountId:v.accountId,amountMinor:minor(v.amount),...(v.cashTendered?{cashTenderedMinor:minor(v.cashTendered)}:{}),reference:v.reference,manuallyConfirmed:v.confirmation==='confirmed'})});
  const quickProduct=()=>{const id=crypto.randomUUID();open({title:'Add item or menu product',operation:'product.save',collection:'products',id,fields:[{key:'name',label:'Item name'},{key:'code',label:'Item code / SKU'},{key:'price',label:'Selling price (KES)',type:'money'},{key:'category',label:'Category',value:'GENERAL'},{key:'routeTo',label:'Service area',type:'select',options:[{value:'BAR',label:'Bar'},{value:'KITCHEN',label:'Kitchen'},{value:'ROOMS',label:'Rooms'}],value:'BAR'}],payload:v=>({id,data:{name:v.name,code:v.code,priceMinor:minor(v.price),category:v.category,routeTo:v.routeTo,taxClassId:'A_STANDARD'}})})};
  const quickAdd=(id:string)=>{if(id==='product')quickProduct();if(id==='room')editRoom();if(id==='asset')editAsset();if(id==='guest')master('customers','Add guest',[{key:'name',label:'Guest name'},{key:'phone',label:'Phone',optional:true},{key:'email',label:'Email',optional:true}]);if(id==='supplier')master('suppliers','Add supplier',[{key:'name',label:'Supplier name'},{key:'code',label:'Supplier code',optional:true},{key:'phone',label:'Phone',optional:true},{key:'email',label:'Email',optional:true}])};
 const pending=queue.some(q=>q.state==='PENDING_SYNC');const pendingCount=queue.filter(q=>q.state==='PENDING_SYNC').length;const conflictCount=queue.filter(q=>q.state==='CONFLICT'||q.state==='REJECTED').length;const disabled=busy||!ready;
  const tabs=visibleWorkspaces(session).map(workspace=>workspace.id).filter(t=>canSeeTab(session,t as WorkspaceTab)) as WorkspaceTab[];
 const visibleGroups=workspaceNavigation.map(group=>({...group,items:group.items.filter(item=>tabs.includes(item.id as typeof tabs[number]))})).filter(group=>group.items.length>0);
  const headerStatus=pending?`${pendingCount} change${pendingCount===1?'':'s'} waiting to sync`:ready?'All changes synchronized':'Connecting to your business records';
  const currentWorkspace=workspaceById(tab);
  const renderNavigation=(mobile=false)=><nav aria-label="Business workspace" className={mobile?'flex gap-2 overflow-x-auto border-t border-slate-800 bg-slate-900 p-2 md:hidden':'flex-1 space-y-5 overflow-auto p-3'}>{mobile?tabs.map(t=><button key={t} aria-current={tab===t?'page':undefined} className={`shrink-0 rounded-xl px-3 py-2 text-xs font-semibold ${tab===t?'bg-amber-400 text-slate-950':'text-slate-300 hover:bg-slate-800'}`} onClick={()=>setTab(t)}>{workspaceById(t).label}</button>):workspaceGroups(session).map(group=><section key={group.group}><h2 className="mb-2 px-3 text-[10px] font-black uppercase tracking-[.18em] text-slate-500">{group.group}</h2><div className="space-y-1">{group.items.map(item=>{const Icon=item.icon;return <button key={item.id} aria-current={tab===item.id?'page':undefined} data-guide-anchor={`navigation.${String(item.id).toLowerCase().replace(/ /g,'-')}`} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition ${tab===item.id?'bg-amber-400 font-bold text-slate-950 shadow-lg shadow-amber-950/20':'text-slate-300 hover:bg-slate-800 hover:text-white'}`} onClick={()=>setTab(item.id)}><Icon className="h-4 w-4 shrink-0"/><span className="flex-1">{item.label}</span>{tab===item.id&&<ChevronRight className="h-4 w-4"/>}</button>})}</div></section>)}</nav>;
 return <div className="flex h-screen min-h-[600px] overflow-hidden bg-slate-950 text-slate-100">
  <aside className="hidden w-64 shrink-0 flex-col border-r border-slate-800 bg-slate-900 md:flex"><div className="border-b border-slate-800 p-4"><div className="text-xs font-black tracking-[.25em] text-amber-400">SERVOS</div><div className="mt-1 font-bold">Remote Operations</div><div className="mt-1 truncate text-xs text-slate-500">Authorized business workspace</div></div>{renderNavigation()}<div className="border-t border-slate-800 p-3"><div className="flex items-center gap-2 text-sm font-semibold"><LockKeyhole className="h-4 w-4 text-amber-300"/>Authenticated session</div><p className="mt-1 truncate pl-6 text-xs text-slate-500">{session.actorId}</p></div></aside>
  <div className="flex min-w-0 flex-1 flex-col"><header className="flex shrink-0 flex-wrap items-center justify-between gap-3 border-b border-slate-800 bg-slate-900 px-4 py-3 sm:px-6"><div className="min-w-0"><div className="text-[10px] font-black uppercase tracking-[.2em] text-amber-400 md:hidden">SERVOS WEB</div><h1 className="truncate text-lg font-bold sm:text-xl">{tab==='Home'?'Start here':tab==='Help'?'Help':tab==='POS'?'Point of Sale':tab==='KDS'?'Bar / Kitchen Pass':tab==='Inventory'?'Stock':tab==='Procurement'?'Purchasing':tab==='Rooms'?'Rooms and stays':tab==='Assets'?'Property assets':tab==='Finance'?'Finance and close day':tab==='Staff'?'Staff and devices':tab}</h1><div data-guide-anchor="web.status shell.status" className="mt-1 flex items-center gap-2 text-xs text-slate-400"><span className={`inline-flex h-2 w-2 rounded-full ${navigator.onLine?'bg-emerald-400':'bg-amber-400'}`}/>{navigator.onLine?'Online':'Offline · saved changes only'}<span className="text-slate-700">·</span><span>{headerStatus}</span></div></div><div className="flex items-center gap-2"><button data-guide-anchor="web.sync" aria-label="Synchronize" disabled={!ready||busy} className={button} onClick={()=>void syncRef.current().catch(e=>setError(String(e)))}><RefreshCw className={`h-4 w-4 ${busy?'animate-spin':''}`}/><span className="hidden sm:inline">Synchronize</span></button>{canSeeTab(session,'Help')&&<button data-guide-anchor="web.help-button shell.help" aria-label="Open Help" className={button} onClick={()=>setTab('Help')}><HelpCircle className="h-4 w-4"/><span className="hidden sm:inline">Help</span></button>}<button data-guide-anchor="shell.lock" className={button} onClick={onSignOut}>Sign out</button></div></header>
  {renderNavigation(true)}<main className="min-h-0 flex-1 overflow-auto"><div className="mx-auto max-w-[1700px] p-4 sm:p-6"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><PageHeader eyebrow={tab==='POS'?'OPERATIONS':'BUSINESS WORKSPACE'} title={currentWorkspace.label} description={currentWorkspace.description} actions={<><ConnectivityBadge online={typeof navigator==='undefined'||navigator.onLine} pending={pendingCount} syncing={syncing} conflicts={conflictCount}/>{pending&&<button className={ds.button} data-guide-anchor="shell.sync" disabled={syncing} onClick={()=>void syncNow().catch(e=>setError(String(e)))}>{syncing?'Synchronizing…':'Synchronize'}</button>}</>}/></div>
  <div className="mb-4 flex flex-wrap items-center gap-2"><StatusBadge tone={ready?'success':'warning'}>{ready?'Workspace ready':headerStatus}</StatusBadge>{conflictCount>0&&<StatusBadge tone="danger">{conflictCount} item{conflictCount===1?'':'s'} need review</StatusBadge>}</div>
  {error&&<Notice tone="danger">{error}</Notice>}{notice&&<div className="mt-3"><Notice tone="success">{notice}</Notice></div>}
  <React.Suspense fallback={<section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><div className="flex items-start gap-3"><RefreshCw className="h-5 w-5 animate-spin text-amber-300"/><div><h2 className="font-bold">Opening workspace</h2><p className="mt-1 text-sm text-slate-400">Loading the tools for this workspace…</p></div></div></section>}>
  {session.lifecycleStage&&session.lifecycleStage!=='LIVE'?<WebLifecycleView session={session} rpc={rpcRef.current} onUpdated={next=>{setSession(next);setLifecycleRefresh(value=>value+1)}}/>:<>{ready&&<WebStaffWelcome session={session} onDismiss={()=>undefined} onStartTour={()=>setTourOpen(true)}/>} {!ready&&<section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><div className="flex items-start gap-3"><Wifi className="mt-1 h-5 w-5 text-amber-300"/><div><h2 className="font-bold">Preparing your workspace</h2><p className="mt-1 text-sm text-slate-400">Online sign-in, device registration, and an authorized business snapshot are required before operations can begin.</p></div></div></section>}</>}
  <div className="rounded-2xl border border-slate-800 bg-slate-900/30 p-4 shadow-xl shadow-black/10 sm:p-5">
  {ready&&tab==='Home'&&<WebStartHere permissions={session.permissions} onNavigate={next=>setTab(next as WorkspaceTab)} onQuickAdd={quickAdd} onOpenHelp={query=>{setHelpQuery(query||'');setTab('Help')}} onStartTour={()=>setTourOpen(true)}/>}
  {ready&&tab==='Help'&&<WebHelpView initialQuery={helpQuery} progress={guidance} onStartTour={()=>setTourOpen(true)} onRestartGuide={guideId=>void saveGuidance({guideId,guideVersion:1,state:'IN_PROGRESS',currentStepId:null,completedStepIds:[]})}/>}
  {ready&&tab==='POS'&&<WebPosView records={records} session={session} disabled={disabled} command={submit}/>}
  {ready&&tab==='KDS'&&<WebKDSView records={records} session={session} disabled={disabled} command={submit}/>}
  {ready&&tab==='Catalog'&&<WebCatalogView records={records} session={session} disabled={disabled} command={submit}/>}
  {ready&&tab==='Inventory'&&<WebInventoryView records={records} session={session} disabled={disabled} command={submit}/>}
  {ready&&tab==='Procurement'&&<WebProcurementView records={records} session={session} disabled={disabled} command={submit}/>}
  {ready&&tab==='Front Desk'&&<WebFrontDeskView records={records} session={session} disabled={disabled} command={submit}/>}
  {ready&&tab==='Guest Accounts'&&<WebGuestAccountsView records={records} session={session} disabled={disabled} command={submit}/>}
  {ready&&tab==='Housekeeping'&&<WebHousekeepingView records={records} session={session} disabled={disabled} command={submit}/>}
  {ready&&tab==='Rooms'&&<section className="space-y-5"><div className="flex flex-wrap gap-2">{allowed(session,'rooms.manage')&&<><button disabled={disabled||!active('roomTypes').length} className={primaryButton} onClick={()=>editRoom()}><BedDouble className="h-4 w-4"/>Add room</button><button disabled={disabled||!active('roomTypes').length} className={button} onClick={addRate}>Add rate</button></>}</div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{active('rooms').map(room=><article key={room.id} className="rounded-2xl border border-slate-800 bg-slate-900 p-4 transition hover:border-amber-500/40"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold">Room {label(room)}</h2><p className="mt-1 text-sm text-slate-400">Capacity {String(room.data.capacity)} &#183; {String(room.data.turnaroundMinutes)} min turnaround</p></div><span className="rounded-full border border-slate-700 bg-slate-950 px-2.5 py-1 text-xs font-semibold text-emerald-200">{String(room.data.housekeepingState||'CLEAN')}</span></div><p className="mt-2 text-xs text-slate-500">{String(room.data.maintenanceState||'AVAILABLE')}</p><div className="mt-4 flex flex-wrap gap-2">{allowed(session,'rooms.manage')&&<button className={button} disabled={disabled} onClick={()=>editRoom(room)}>Edit</button>}{allowed(session,'rooms.operate')&&<button className={primaryButton} disabled={disabled} onClick={()=>reserve(room)}>Reserve / walk-in</button>}{allowed(session,'rooms.manage')&&<button className={button} disabled={disabled} onClick={()=>action('Update housekeeping','room.housekeeping','rooms',room.id,[{key:'state',label:'Next housekeeping state',type:'select',options:['DIRTY','CLEANING','INSPECTION','CLEAN'].map(value=>({value,label:value}))}])}>Housekeeping</button>}</div></article>)}</div>{active('rooms').length===0&&<section className="rounded-2xl border border-dashed border-slate-700 bg-slate-950/60 px-6 py-12 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-slate-800 text-amber-300"><BedDouble className="h-7 w-7"/></span><h2 className="mt-4 text-lg font-bold">Set up your first room</h2><p className="mx-auto mt-2 max-w-lg text-sm text-slate-400">Start with a room type and rate plan, then add rooms. Reservations and stays will appear here once created.</p><div className="mt-5 flex flex-wrap justify-center gap-2">{allowed(session,'roomTypes.manage')&&<button className={primaryButton} onClick={()=>setTab('Settings')}>Set up room types</button>}</div></section>}
   <section className="rounded-2xl border border-slate-800 bg-slate-950/50 p-4"><h2 className="mb-3 flex items-center gap-2 text-lg font-bold"><BedDouble className="h-5 w-5 text-amber-300"/>Reservations and stays</h2>{active('roomReservations').map(booking=>{const folio=find('folios',booking.id);return <article key={booking.id} className="mb-3 rounded-xl border border-slate-800 bg-slate-900 p-4"><h3 className="font-bold">{label(find('customers',String(booking.data.customerId))||booking)} &#183; Room {String(find('rooms',String(booking.data.roomId))?.data.number||booking.data.roomId)}</h3><p className="mt-1 text-sm text-slate-400">{String(booking.data.status)} &#183; {new Date(String(booking.data.startsAt)).toLocaleString()} – {new Date(String(booking.data.endsAt)).toLocaleString()}</p>{folio&&<p className="mt-2 text-sm">Balance {money(folio.data.balanceMinor)} &#183; Unapplied deposit {money(folio.data.depositMinor)}</p>}<div className="mt-3 flex flex-wrap gap-2">
    {booking.data.status==='RESERVED'&&allowed(session,'rooms.operate')&&<><button disabled={disabled} className={button} onClick={()=>action('Check in','stay.checkIn','stays',booking.id)}>Check in</button><button disabled={disabled} className={button} onClick={()=>action('Cancel reservation','roomReservation.cancel','roomReservations',booking.id,[{key:'reason',label:'Cancellation reason'}])}>Cancel</button></>}
    {!folio&&allowed(session,'folio.manage')&&booking.data.status==='RESERVED'&&<button disabled={disabled} className={button} onClick={()=>action('Open folio for deposits','folio.open','folios',booking.id)}>Open folio</button>}
    {folio?.data.status==='OPEN'&&allowed(session,'folio.manage')&&<><button disabled={disabled} className={button} onClick={()=>payment(booking,true)}>Deposit</button><button disabled={disabled} className={button} onClick={()=>payment(booking,false)}>Payment</button><button disabled={disabled} className={button} onClick={()=>open({title:'Apply deposit',operation:'folio.applyDeposit',collection:'folios',id:booking.id,fields:[{key:'amount',label:'Amount to apply (KES)',type:'money'}],payload:v=>({id:booking.id,amountMinor:minor(v.amount)})})}>Apply deposit</button>{booking.data.status==='CHECKED_IN'&&<button disabled={disabled} className={button} onClick={()=>action('Post all booked accommodation for settlement','folio.postAccommodation','folios',booking.id,[],{settleBookedStay:true})}>Post accommodation</button>}</>}
    {booking.data.status==='CHECKED_IN'&&allowed(session,'rooms.operate')&&<><button disabled={disabled} className={button} onClick={()=>action('Move guest','stay.move','stays',booking.id,[select('roomId','Destination room','rooms'),{key:'reason',label:'Move reason'}])}>Move room</button><button disabled={disabled} className={button} onClick={()=>action('Check out after settlement','stay.checkOut','stays',booking.id)}>Check out</button></>}
   </div></article>})}
  </section></section>}
  {ready&&tab==='Assets'&&<section className="space-y-4">{allowed(session,'assets.manage')&&<button disabled={disabled} className={button} onClick={()=>editAsset()}>Add asset</button>}{active('assets').map(asset=><article key={asset.id} className="rounded-xl border border-slate-700 p-4"><h2 className="font-bold">{label(asset)} &#183; {String(asset.data.tag)}</h2><p>{String(asset.data.status)} &#183; {String(asset.data.condition)} &#183; Custodian: {String(find('employees',String(asset.data.custodianId))?.data.name||'Unassigned')}</p><div className="mt-3 flex flex-wrap gap-2">{allowed(session,'assets.manage')&&<button disabled={disabled} className={button} onClick={()=>editAsset(asset)}>Edit</button>}{allowed(session,'assets.operate')&&<><button disabled={disabled} className={button} onClick={()=>action('Assign asset','asset.assign','assets',asset.id,[select('custodianId','Custodian','employees'),{key:'reason',label:'Assignment reason'}])}>Assign</button><button disabled={disabled} className={button} onClick={()=>action('Return asset','asset.return','assets',asset.id,[{key:'reason',label:'Return reason'}])}>Return</button><button disabled={disabled} className={button} onClick={()=>action('Transfer asset','asset.transfer','assets',asset.id,[{...select('roomId','Destination room','rooms'),optional:true},{...select('locationId','Destination location','stockLocations'),optional:true},{key:'reason',label:'Transfer reason'}])}>Transfer</button><button disabled={disabled} className={button} onClick={()=>action('Inspect asset','asset.inspect','assets',asset.id,[{key:'condition',label:'Condition',type:'select',options:['GOOD','FAIR','POOR','BROKEN'].map(value=>({value,label:value}))},{key:'reason',label:'Inspection notes'}])}>Inspect</button></>}</div></article>)}{active('assets').length===0&&<p>No assets yet. Add a category in Settings and assign each asset to a room or stock location.</p>}</section>}
  {ready&&tab==='Settings'&&<section className="space-y-4"><h2 className="text-xl font-bold">Business master records</h2><div className="flex flex-wrap gap-2">{allowed(session,'customers.manage')&&<button disabled={disabled} className={button} onClick={()=>master('customers','Add guest',[{key:'name',label:'Guest name'},{key:'phone',label:'Phone',optional:true},{key:'email',label:'Email',optional:true}])}>Add guest</button>}{allowed(session,'roomTypes.manage')&&<button disabled={disabled} className={button} onClick={()=>master('roomTypes','Add room type',[{key:'name',label:'Room type'},{key:'maxGuests',label:'Maximum guests',type:'number'}])}>Add room type</button>}{allowed(session,'assetCategories.manage')&&<button disabled={disabled} className={button} onClick={()=>master('assetCategories','Add asset category',[{key:'name',label:'Category name'}])}>Add asset category</button>}</div>{['customers','roomTypes','ratePlans','assetCategories','paymentAccounts','hotelServices'].map(collection=><div key={collection}><h3 className="font-semibold">{collection}</h3><ul className="space-y-1">{active(collection).map(r=><li key={r.id}>{label(r)}{r.data.priceMinor!==undefined?` &#183; ${money(r.data.priceMinor)}`:''}</li>)}</ul></div>)}</section>}
  {ready&&tab==='Activity'&&<ActivitySyncCenter queue={queue} drafts={drafts} online={online} syncing={syncing} onSync={syncNow}/>} 
   {ready&&tab==='Finance Controls'&&<WebFinancialControlsView records={records} session={session} disabled={disabled} command={submit}/>}
   {ready&&tab==='Finance'&&(allowed(session,'reports.view')||allowed(session,'till.view'))&&<WebFinanceView records={records} session={session} disabled={disabled} command={submit}/>}
   {ready&&tab==='Staff'&&(allowed(session,'staff.view')||allowed(session,'devices.manage'))&&<WebStaffAdminView records={records} session={session} disabled={disabled} command={submit} rpc={rpcRef.current} currentDeviceId={localStorage.getItem(`servos-device:${session.businessId}:${session.actorId}`)||''}/>}
   {ready&&tab==='Administration'&&<WebAdministrationView records={records} session={session} disabled={disabled} command={submit} rpc={rpcRef.current}/>}
  {editor&&<div className="fixed inset-0 z-50 overflow-y-auto bg-black/75 p-4"><form role="dialog" aria-modal="true" aria-label={editor.title} className="mx-auto my-5 max-w-xl space-y-4 rounded-xl border border-slate-600 bg-slate-900 p-5" onSubmit={e=>{e.preventDefault();try{void submit(editor.operation,editor.collection,editor.id,editor.payload(values))}catch(error){setError(String(error))}}}><h2 className="text-xl font-bold">{editor.title}</h2>{editor.fields.length===0&&<p>Review the details, then choose Confirm. Your access and the latest business information are checked before saving.</p>}{editor.fields.map(f=><label key={f.key} className="block">{f.label}{f.type==='select'?<select required={!f.optional} className={input} value={values[f.key]||''} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}><option value="">Select…</option>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input required={!f.optional} className={input} type={f.type==='money'?'number':f.type||'text'} min={f.type==='number'||f.type==='money'?0:undefined} step={f.type==='money'?'0.01':f.type==='number'?'1':undefined} value={values[f.key]||''} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}/>}</label>)}<div className="flex gap-2"><button disabled={busy} className={`${button} bg-amber-400 text-slate-950`}>Confirm</button><button type="button" className={button} onClick={()=>setEditor(null)}>Cancel</button></div></form></div>}
  {ready&&tab==='Master Data'&&<WebMasterDataView records={records} session={session} disabled={disabled} command={submit}/>}
   {ready&&tab==='Refunds'&&<WebRefundsView records={records} session={session} disabled={disabled} command={submit}/>}
  </React.Suspense>
   </div></div></main></div>{tourOpen&&<WebGuidedTour progress={guidance.find(row=>row.guideId==='servos.core')} onProgress={saveGuidance} onNavigate={next=>setTab(next as WorkspaceTab)} onClose={()=>setTourOpen(false)}/>}</div>;
}
