import React,{useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowRightLeft,Boxes,PackageCheck,Search} from 'lucide-react';
import {useBarcodeScanner,barcodeEquals} from '../../hooks/useBarcodeScanner';
import {allowed,type BusinessRecord,type WebSession} from './session';
import {parseQuantity} from '../../utils/fiscal';
import {calculateRecipeCost,canonicalizeMeasurement} from '../../utils/inventoryUnits';
import {Dialog} from '../../design-system/controls';
import {WebLinkedCorrectionDialog} from './WebLinkedCorrectionDialog';
import {WebPhysicalCountDialog} from './WebPhysicalCountDialog';
import {WebStockCountHistory} from './WebStockCountHistory';
import {physicalStock,movementPayload} from '../../utils/bottleInventory';
import {SmartItemDialog} from './SmartItemDialog';
import {isCommandConfirmed,type CommandOutcome} from '../../types/transactions';

type CommandFn=(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<CommandOutcome>;
const field='w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white outline-none focus:border-amber-400';
const button='rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm font-semibold hover:bg-slate-800 disabled:opacity-40';
const primary='rounded-lg bg-amber-400 px-3 py-2 text-sm font-bold text-slate-950 hover:bg-amber-300 disabled:opacity-40';
const money=(minor:unknown)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES'}).format(Number(minor||0)/100);
const data=(record?:BusinessRecord)=>record?.data as Record<string,any>|undefined;
const active=(records:BusinessRecord[],collection:string)=>records.filter(r=>r.collection===collection&&!r.archived);
const archived=(records:BusinessRecord[],collection:string)=>records.filter(r=>r.collection===collection&&r.archived);
const total=(stock:BusinessRecord)=>Object.values(data(stock)?.currentStock||{}).reduce((sum:number,value)=>sum+Number(value||0),0);
const status=(stock:BusinessRecord)=>{const q=total(stock),r=Number(data(stock)?.reorderLevel||0);return q<=0?'OUT':r>0&&q<=r?'LOW':'HEALTHY'};
const tone=(s:string)=>s==='OUT'?'border-rose-500/30 bg-rose-500/10 text-rose-200':s==='LOW'?'border-amber-500/30 bg-amber-500/10 text-amber-200':'border-emerald-500/30 bg-emerald-500/10 text-emerald-200';
const sealedOpenBalance=(stock:BusinessRecord,locationId:string)=>{const d=data(stock)!;const size=Number(d.sealedContainerSize||0);if(d.baseUnit!=='ml'||!Number.isFinite(size)||size<=0)return null;const stored=d.sealedOpenStock?.[locationId];const totalAtLocation=Number(d.currentStock?.[locationId]||0);const sealed=Number.isFinite(Number(stored?.sealedContainers))?Number(stored.sealedContainers):Math.floor(totalAtLocation/size);const open=Number.isFinite(Number(stored?.openQuantity))?Number(stored.openQuantity):Number((totalAtLocation-sealed*size).toFixed(6));if(sealed<0||open<0||open>=size+0.000001||Math.abs(sealed*size+open-totalAtLocation)>0.001)return null;return {sealed,open,size}};
const splitBottleQuantity=(size:number,quantity:number)=>{const sealed=Math.floor(quantity/size);return {sealed,open:Number((quantity-sealed*size).toFixed(6))}};
const outcomeMessage=(outcome:CommandOutcome,action='Action')=>{switch(outcome.kind){case'CONFIRMED':return `${action} confirmed and synchronized.`;case'DRAFT_SAVED':return `${action} saved as a draft; it has not taken effect.`;case'PENDING':return `${action} is waiting to synchronize. Do not submit it again.`;case'OUTCOME_UNKNOWN':case'REJECTED':case'CONFLICT':case'BLOCKED':return outcome.message}};

export function WebCatalogView({records,session,disabled,command,closeWhenQueued=false}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:CommandFn;closeWhenQueued?:boolean}){
 const products=active(records,'products');const stocks=active(records,'stockItems');const locations=active(records,'stockLocations');
 const [kind,setKind]=useState<'PRODUCT'|'STOCK'|'LOCATION'|null>(null);const [editing,setEditing]=useState<BusinessRecord|null>(null);
 const [form,setForm]=useState<Record<string,any>>({});
 const [recipeStockId,setRecipeStockId]=useState('');const [recipeQuantity,setRecipeQuantity]=useState(1);const [recipeUnit,setRecipeUnit]=useState('g');
 const [validationError,setValidationError]=useState('');
 const [commandNotice,setCommandNotice]=useState('');
 const [smartItemOpen,setSmartItemOpen]=useState(false);
 const canCatalog=allowed(session,'catalog.manage');const canInventory=allowed(session,'inventory.adjust');
 const open=(next:'PRODUCT'|'STOCK'|'LOCATION',record?:BusinessRecord)=>{
  setCommandNotice('');setKind(next);setEditing(record||null);setValidationError('');const d=data(record)||{};
  if(next==='PRODUCT')setForm({name:d.name||'',code:d.code||'',price:Number(d.priceMinor||0)/100,category:d.category||'GENERAL',routeTo:d.routeTo||'BAR',stockItemId:Array.isArray(d.recipeIngredients)&&d.recipeIngredients.length? '':d.stockItemId||'',barcode:d.barcode||'',favorite:!!d.favorite,taxClassId:d.taxClassId||'',recipeIngredients:Array.isArray(d.recipeIngredients)?d.recipeIngredients:[]});
  if(next==='STOCK')setForm({name:d.name||'',code:d.code||'',baseUnit:d.baseUnit||'unit',barcode:d.barcode||'',purchasePackages:Array.isArray(d.purchasePackages)?d.purchasePackages:[],scanUnitQuantity:Number(d.scanUnitQuantity||1),reorderLevel:Number(d.reorderLevel||0),averageUnitCost:Number(d.averageUnitCostMinor||0)/100,sealedContainerSize:Number(d.sealedContainerSize||0)});
  if(next==='LOCATION')setForm({name:d.name||'',code:d.code||'',type:d.type||'STORE'});
 };
 const save=async()=>{
  setValidationError('');
  const id=editing?.id||crypto.randomUUID();
  let outcome:CommandOutcome|undefined;
  if(kind==='PRODUCT')outcome=await command('product.save','products',id,{id,data:{name:String(form.name||'').trim(),code:String(form.code||'').trim(),priceMinor:Math.round(Number(form.price||0)*100),category:String(form.category||'GENERAL').trim(),routeTo:String(form.routeTo||'BAR'),stockItemId:String(form.stockItemId||'').trim()||undefined,barcode:String(form.barcode||'').trim()||undefined,favorite:!!form.favorite,taxClassId:String(form.taxClassId||''),recipeIngredients:Array.isArray(form.recipeIngredients)?form.recipeIngredients:[]}});
  if(kind==='STOCK'){try{const scanUnitQuantity=parseQuantity(form.scanUnitQuantity,{min:Number.MIN_VALUE});const reorderLevel=parseQuantity(form.reorderLevel);const sealedContainerSize=form.sealedContainerSize?parseQuantity(form.sealedContainerSize,{min:Number.MIN_VALUE}):undefined;outcome=await command('stockItem.save','stockItems',id,{id,data:{name:String(form.name||'').trim(),code:String(form.code||'').trim(),baseUnit:String(form.baseUnit||'unit').trim(),barcode:String(form.barcode||'').trim()||undefined,purchasePackages:Array.isArray(form.purchasePackages)?form.purchasePackages:[],scanUnitQuantity,reorderLevel,averageUnitCostMinor:Number(form.averageUnitCost||0)*100,...(sealedContainerSize?{sealedContainerSize}:{})}})}catch(error){setValidationError(error instanceof Error?error.message:'Enter valid quantity values.');return}}
  if(kind==='LOCATION')outcome=await command('stockLocation.save','stockLocations',id,{id,data:{name:String(form.name||'').trim(),code:String(form.code||'').trim(),type:String(form.type||'STORE')}});
  if((outcome?.kind==='PENDING'||outcome?.kind==='OUTCOME_UNKNOWN')&&closeWhenQueued){setCommandNotice(outcomeMessage(outcome,'Catalog save'));setKind(null);setEditing(null);return}
  if(!outcome||!isCommandConfirmed(outcome)){setValidationError(outcome?outcomeMessage(outcome,'Catalog save'):'Choose a catalog record type before saving.');return}
  setKind(null);setEditing(null);
 };
 const masterAction=async(record:BusinessRecord,op:string)=>{const outcome=await command(op,record.collection,record.id,{id:record.id});setCommandNotice(outcomeMessage(outcome,'Catalog action'))};
 const addRecipeIngredient=()=>{const stock=stocks.find(item=>item.id===recipeStockId);if(!stock)return;const baseUnit=String(data(stock)?.baseUnit||'piece').toLowerCase();const mode=baseUnit==='g'||baseUnit==='kg'?'WEIGHT':baseUnit==='ml'||baseUnit==='l'?'VOLUME':'COUNT';try{const entered=canonicalizeMeasurement(recipeQuantity,recipeUnit,mode);const base=canonicalizeMeasurement(1,baseUnit,mode);const quantity=Number((entered.quantity/base.quantity).toFixed(6));if(!Number.isFinite(quantity)||quantity<=0)throw new Error('Enter a positive compatible quantity.');setForm((previous:any)=>({...previous,stockItemId:'',recipeIngredients:[...(previous.recipeIngredients||[]),{stockItemId:recipeStockId,quantity,tracked:true}]}));setRecipeStockId('');setRecipeQuantity(1);setValidationError('')}catch{setValidationError(`Enter a valid ${recipeUnit} amount compatible with ${baseUnit}.`)}};
 const recipeStock=stocks.find(item=>item.id===recipeStockId);const recipeBase=String(data(recipeStock)?.baseUnit||'piece').toLowerCase();const recipeUnits=recipeBase==='g'||recipeBase==='kg'?['g','kg']:recipeBase==='ml'||recipeBase==='l'?['ml','l']:[recipeBase];
 const recipeCostMinor=(()=>{try{return calculateRecipeCost((form.recipeIngredients||[]).map((line:any)=>({quantity:Number(line.quantity),averageCostMinor:Number(data(stocks.find(item=>item.id===line.stockItemId))?.averageUnitCostMinor||0)})))}catch{return Number.NaN}})();
 return <section className="space-y-5">
   <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">Items and stock</h2><p className="mt-1 text-sm text-slate-400">Add the items you sell and the stock you keep. Change quantities from Stock, not from this list.</p></div><div className="flex flex-wrap gap-2">{(canInventory||canCatalog&&allowed(session,'inventory.view'))&&<button disabled={disabled} className={primary} onClick={()=>setSmartItemOpen(true)}>Smart item setup</button>}{canCatalog&&<><button disabled={disabled} className={button} onClick={()=>open('PRODUCT')}>New product</button><button disabled={disabled} className={button} onClick={()=>open('STOCK')}>New stock item</button></>}{canInventory&&<button disabled={disabled} className={button} onClick={()=>open('LOCATION')}>New stock location</button>}</div></div>
  {commandNotice&&!kind&&!smartItemOpen&&<p role="status" className="rounded-lg border border-slate-700 bg-slate-900 p-3 text-sm">{commandNotice}</p>}
  <div className="grid gap-4 xl:grid-cols-2">
   <Panel title={`Products · ${products.length}`}>{products.map(r=>{const d=data(r)!;return <article key={r.id} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="flex items-start justify-between gap-3"><div><b>{String(d.name)}</b><div className="font-mono text-[11px] text-slate-500">{String(d.code)}</div></div><span className="font-semibold text-amber-300">{money(d.priceMinor)}</span></div><div className="mt-1 text-xs text-slate-500">{String(d.category||'GENERAL')} · {String(d.routeTo||'BAR')}{d.stockItemId?' · stock linked':''}</div>{canCatalog&&<div className="mt-3 flex gap-2"><button disabled={disabled} className={button} onClick={()=>open('PRODUCT',r)}>Edit</button><button disabled={disabled} className={button} onClick={()=>void masterAction(r,'product.archive')}>Archive</button></div>}</article>})}</Panel>
   <Panel title={`Stock masters · ${stocks.length}`}>{stocks.map(r=>{const d=data(r)!;return <article key={r.id} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="flex items-start justify-between gap-3"><div><b>{String(d.name)}</b><div className="font-mono text-[11px] text-slate-500">{String(d.code)}</div></div><span>{total(r).toLocaleString()} {String(d.baseUnit||'units')}</span></div><div className="mt-1 text-xs text-slate-500">Reorder at {Number(d.reorderLevel||0).toLocaleString()} · Avg cost {money(d.averageUnitCostMinor)}</div>{canCatalog&&<div className="mt-3 flex gap-2"><button disabled={disabled} className={button} onClick={()=>open('STOCK',r)}>Edit</button><button disabled={disabled} className={button} onClick={()=>void masterAction(r,'stockItem.archive')}>Archive</button></div>}</article>})}</Panel>
  </div>
  <Panel title={`Stock locations · ${locations.length}`}><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{locations.map(r=>{const d=data(r)!;return <article key={r.id} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><b>{String(d.name)}</b><div className="text-xs text-slate-500">{String(d.code||r.id)} · {String(d.type||'STORE')}</div>{canInventory&&<div className="mt-3 flex gap-2"><button disabled={disabled} className={button} onClick={()=>open('LOCATION',r)}>Edit</button><button disabled={disabled} className={button} onClick={()=>void masterAction(r,'stockLocation.archive')}>Archive</button></div>}</article>})}</div></Panel>
  {(archived(records,'products').length+archived(records,'stockItems').length+archived(records,'stockLocations').length)>0&&<details className="rounded-xl border border-slate-800 bg-slate-900 p-3"><summary className="cursor-pointer font-semibold">Archived masters</summary><div className="mt-3 space-y-2">{archived(records,'products').map(r=><Restore key={r.id} record={r} label={String(data(r)?.name||r.id)} disabled={disabled} onRestore={()=>masterAction(r,'product.reactivate')}/>)}{archived(records,'stockItems').map(r=><Restore key={r.id} record={r} label={String(data(r)?.name||r.id)} disabled={disabled} onRestore={()=>masterAction(r,'stockItem.reactivate')}/>)}{archived(records,'stockLocations').map(r=><Restore key={r.id} record={r} label={String(data(r)?.name||r.id)} disabled={disabled} onRestore={()=>masterAction(r,'stockLocation.reactivate')}/>)}</div></details>}
  {smartItemOpen&&<SmartItemDialog records={records} session={session} disabled={disabled} command={command} onClose={()=>setSmartItemOpen(false)}/>}
  {kind&&<Modal title={editing?`Edit ${kind.toLowerCase()}`:`New ${kind.toLowerCase()}`} onClose={()=>setKind(null)}><div className="space-y-3">
   <label className="block text-sm">Name<input className={field} value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label>
   <label className="block text-sm">Code / SKU<input className={field} value={form.code||''} onChange={e=>setForm({...form,code:e.target.value})}/></label>
   {kind==='PRODUCT'&&<><label className="block text-sm">Price (KES)<input type="number" min="0" step="0.01" className={field} value={form.price??0} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></label><label className="block text-sm">Category<input className={field} value={form.category||''} onChange={e=>setForm({...form,category:e.target.value})}/></label><label className="block text-sm">Route<select className={field} value={form.routeTo||'BAR'} onChange={e=>setForm({...form,routeTo:e.target.value})}><option>BAR</option><option>KITCHEN</option><option>SERVICE</option></select></label><label className="block text-sm">Tax class<select required className={field} value={form.taxClassId||''} onChange={e=>setForm({...form,taxClassId:e.target.value})}><option value="">Select tax class…</option><option value="A_16">Standard · 16%</option><option value="B_0">Zero-rated · 0%</option><option value="C_EXEMPT">Exempt</option></select></label><label className="block text-sm">Linked stock item<select className={field} value={form.stockItemId||''} onChange={e=>setForm({...form,stockItemId:e.target.value})}><option value="">Untracked / later recipe</option>{stocks.map(s=><option key={s.id} value={s.id}>{String(data(s)?.name)}</option>)}</select></label><label className="block text-sm">Barcode<input className={field} value={form.barcode||''} onChange={e=>setForm({...form,barcode:e.target.value})}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!form.favorite} onChange={e=>setForm({...form,favorite:e.target.checked})}/>Favorite</label></>}
   {kind==='PRODUCT'&&<section className="space-y-3 rounded-lg border border-slate-800 p-3"><div><b>Recipe ingredients</b><p className="text-xs text-slate-400">Enter kitchen units; ServOS converts to each ingredient's stock unit. POS will deduct these quantities when the order is fired.</p></div><div className="grid gap-2 sm:grid-cols-[1fr_100px_90px_auto]"><select aria-label="Recipe stock ingredient" className={field} value={recipeStockId} onChange={event=>{const id=event.target.value;setRecipeStockId(id);const stock=stocks.find(item=>item.id===id);const unit=String(data(stock)?.baseUnit||'piece').toLowerCase();setRecipeUnit(unit==='kg'?'kg':unit==='l'?'l':unit==='g'?'g':unit==='ml'?'ml':'piece')}}><option value="">Choose ingredient stock</option>{stocks.filter(item=>!(form.recipeIngredients||[]).some((line:any)=>line.stockItemId===item.id)).map(item=><option key={item.id} value={item.id}>{String(data(item)?.name)} · {String(data(item)?.baseUnit||'piece')}</option>)}</select><input aria-label="Recipe ingredient quantity" type="number" min="0.000001" step="any" className={field} value={recipeQuantity} onChange={event=>setRecipeQuantity(Number(event.target.value))}/><select aria-label="Recipe amount unit" className={field} value={recipeUnit} onChange={event=>setRecipeUnit(event.target.value)}>{recipeUnits.map(unit=><option key={unit} value={unit}>{unit}</option>)}</select><button type="button" className={button} disabled={!recipeStockId||!Number.isFinite(recipeQuantity)||recipeQuantity<=0} onClick={addRecipeIngredient}>Add</button></div>{Array.isArray(form.recipeIngredients)&&form.recipeIngredients.map((line:any)=><div key={line.stockItemId} className="flex items-center justify-between rounded bg-slate-950 p-2 text-sm"><span>{String(data(stocks.find(item=>item.id===line.stockItemId))?.name||line.stockItemId)} · {line.quantity} {String(data(stocks.find(item=>item.id===line.stockItemId))?.baseUnit||'piece')}</span><button type="button" className="text-rose-300" onClick={()=>setForm({...form,recipeIngredients:form.recipeIngredients.filter((item:any)=>item.stockItemId!==line.stockItemId)})}>Remove</button></div>)}</section>}
   {kind==='STOCK'&&<><label className="block text-sm">Base unit<input className={field} value={form.baseUnit||''} onChange={e=>setForm({...form,baseUnit:e.target.value})}/></label><label className="block text-sm">Barcode<input className={field} value={form.barcode||''} onChange={e=>setForm({...form,barcode:e.target.value})}/></label><label className="block text-sm">Quantity represented by one scan<input type="number" min="0.000001" step="0.001" className={field} value={form.scanUnitQuantity??1} onChange={e=>setForm({...form,scanUnitQuantity:Number(e.target.value)})}/></label><label className="block text-sm">Reorder level<input type="number" min="0" step="0.001" className={field} value={form.reorderLevel??0} onChange={e=>setForm({...form,reorderLevel:Number(e.target.value)})}/></label><label className="block text-sm">Average unit cost (KES)<input type="number" min="0" step="0.01" className={field} value={form.averageUnitCost??0} onChange={e=>setForm({...form,averageUnitCost:Number(e.target.value)})}/><span className="text-xs text-slate-500">Once stock exists, average cost changes must come through Procurement.</span></label></>}
   {kind==='STOCK'&&form.baseUnit==='ml'&&<label className="block text-sm">Sealed bottle/container size (ml)<input type="number" min="0" step="0.1" className={field} value={form.sealedContainerSize||''} onChange={e=>setForm({...form,sealedContainerSize:e.target.value===''?0:Number(e.target.value)})}/><span className="text-xs text-slate-500">Optional. Enables sealed/open tracking; the size cannot change while stock remains.</span></label>}
   {kind==='LOCATION'&&<label className="block text-sm">Type<select className={field} value={form.type||'STORE'} onChange={e=>setForm({...form,type:e.target.value})}><option>STORE</option><option>FRIDGE</option><option>BAR</option><option>KITCHEN</option><option>OTHER</option></select></label>}
   {kind==='PRODUCT'&&Array.isArray(form.recipeIngredients)&&form.recipeIngredients.length>0&&<p className="rounded-lg bg-slate-950 p-3 text-sm">Calculated recipe cost per sale: <b>{Number.isFinite(recipeCostMinor)?money(recipeCostMinor):'Review ingredient stock costs and quantities'}</b></p>}
   {validationError&&<p className="rounded-lg border border-rose-700/50 bg-rose-500/10 p-2 text-sm text-rose-200">{validationError}</p>}<div className="flex gap-2"><button disabled={disabled||!String(form.name||'').trim()||!String(form.code||'').trim()} className={primary} onClick={()=>void save()}>Save</button><button className={button} onClick={()=>setKind(null)}>Cancel</button></div>
  </div></Modal>}
 </section>;
}

export function WebInventoryView({records,session,disabled,command,apiAuthority=false}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:CommandFn;apiAuthority?:boolean}){
 type BottleCount={sealed:number;open:number};
 type CountSession={locationId:string;startedAt:string;revision:number;counts:Record<string,number|null>;bottleCounts:Record<string,BottleCount>;baseline:Record<string,{expectedQuantity:number;name:string;baseUnit:string;scanUnitQuantity:number;version:number}>};
 const readCountSession=(key:string):CountSession|null=>{try{const value=JSON.parse(localStorage.getItem(key)||'null');if(!value||typeof value!=='object'||Array.isArray(value)||typeof value.locationId!=='string'||!value.locationId.trim())return null;const rawCounts=value.counts&&typeof value.counts==='object'&&!Array.isArray(value.counts)?value.counts:{};const counts:Record<string,number|null>={};for(const [stockId,quantity] of Object.entries(rawCounts)){if(!stockId.trim())continue;if(quantity===null){counts[stockId]=null}else if(typeof quantity==='number'&&Number.isFinite(quantity)&&quantity>=0){counts[stockId]=quantity}}const rawBottles=value.bottleCounts&&typeof value.bottleCounts==='object'&&!Array.isArray(value.bottleCounts)?value.bottleCounts:{};const bottleCounts=Object.fromEntries(Object.entries(rawBottles).flatMap(([id,raw])=>{if(!id.trim()||!raw||typeof raw!=='object'||Array.isArray(raw))return [];const row=raw as Record<string,unknown>;const sealed=Number(row.sealed),open=Number(row.open);return Number.isInteger(sealed)&&sealed>=0&&Number.isFinite(open)&&open>=0?[[id,{sealed,open}]]:[]}));const rawBaseline=value.baseline&&typeof value.baseline==='object'&&!Array.isArray(value.baseline)?value.baseline:{};const baseline=Object.fromEntries(Object.entries(rawBaseline).flatMap(([id,row])=>{if(!id.trim()||!row||typeof row!=='object'||Array.isArray(row))return [];const item=row as Record<string,unknown>;const expectedQuantity=Number(item.expectedQuantity),scanUnitQuantity=Number(item.scanUnitQuantity),version=Number(item.version);if(!Number.isFinite(expectedQuantity)||expectedQuantity<0||!Number.isFinite(scanUnitQuantity)||scanUnitQuantity<=0||!Number.isSafeInteger(version)||version<1||typeof item.name!=='string'||typeof item.baseUnit!=='string')return [];return [[id,{expectedQuantity,name:item.name,baseUnit:item.baseUnit,scanUnitQuantity,version}]]}));return {locationId:value.locationId,startedAt:typeof value.startedAt==='string'&&Number.isFinite(Date.parse(value.startedAt))?value.startedAt:new Date(0).toISOString(),revision:Number.isSafeInteger(value.revision)&&value.revision>0?value.revision:1,counts,bottleCounts,baseline}}catch{return null}};
 const stocks=active(records,'stockItems');const products=active(records,'products');const locations=active(records,'stockLocations');const movements=active(records,'stockMovements').slice().sort((a,b)=>String(data(b)?.occurredAt||'').localeCompare(String(data(a)?.occurredAt||'')));
  const [search,setSearch]=useState('');const [state,setState]=useState('ALL');const [location,setLocation]=useState('ALL');const [selectedId,setSelectedId]=useState(stocks[0]?.id||'');
  const [reversing,setReversing]=useState<BusinessRecord|null>(null);
  const [physicalCount,setPhysicalCount]=useState<{scope:'FULL'|'SELECTED';locationId:string}|null>(null);
  const [modal,setModal]=useState<'COUNT'|'ADJUST'|'TRANSFER'|'WASTE'|null>(null);const [batchOpen,setBatchOpen]=useState(false);const [form,setForm]=useState<Record<string,any>>({stockItemId:stocks[0]?.id||'',locationId:locations[0]?.id||'',toLocationId:locations[1]?.id||'',countedQty:0,quantity:1,disposition:'SEALED',reason:'',scan:''});
  const sessionKey=`servos-web-count:${session.businessId}:${session.actorId}`;const [unknownBarcodes,setUnknownBarcodes]=useState<string[]>(()=>{try{const value=JSON.parse(localStorage.getItem(sessionKey+':unknown')||'[]');return Array.isArray(value)?value:[]}catch{return []}});const [unknownTargets,setUnknownTargets]=useState<Record<string,string>>({});const [unknownBusy,setUnknownBusy]=useState('');const [unknownError,setUnknownError]=useState('');const [commandNotice,setCommandNotice]=useState('');const [resumable,setResumable]=useState<CountSession|null>(()=>readCountSession(sessionKey));
 const selected=stocks.find(s=>s.id===selectedId)||stocks[0];
 const rows=useMemo(()=>stocks.map(stock=>({stock,total:total(stock),status:status(stock)})).filter(row=>{const d=data(row.stock)!;const q=search.trim().toLowerCase();return (!q||[d.name,d.code,d.barcode].some(v=>String(v||'').toLowerCase().includes(q)))&&(state==='ALL'||row.status===state)}),[stocks,search,state]);
 const stockValue=stocks.reduce((sum,s)=>sum+total(s)*Number(data(s)?.averageUnitCostMinor||0),0);
  const canCount=allowed(session,'inventory.count')||!apiAuthority&&allowed(session,'inventory.adjust');const canCorrect=allowed(session,'inventory.adjust');const canBatch=canCorrect;const canReverseMovement=!apiAuthority&&canCorrect;const canAssignBarcode=!apiAuthority&&canCorrect;const canTransfer=allowed(session,'inventory.transfer');const canWaste=allowed(session,'inventory.waste');
  const persistSession=(next:CountSession)=>{setResumable(next);localStorage.setItem(sessionKey,JSON.stringify(next))};
  const clearCommittedSession=()=>{localStorage.removeItem(sessionKey);localStorage.removeItem(sessionKey+':unknown');setResumable(null);setUnknownBarcodes([])};
  useEffect(()=>{if(!resumable)return;const committed=active(records,'stockCounts').some(record=>data(record)?.sessionId===sessionKey&&Number(data(record)?.revision)===resumable.revision);if(committed)clearCommittedSession()},[records,resumable,sessionKey]);
  const countValue=(stockId:string)=>resumable?.counts?.[stockId]??0;
  const assignUnknownBarcode=async(code:string)=>{const stockId=unknownTargets[code];const target=stocks.find(item=>item.id===stockId);if(!target)return;const duplicate=stocks.some(item=>{const d=data(item)!;return [d.barcode,d.code,...(Array.isArray(d.barcodeAliases)?d.barcodeAliases:[]),...(Array.isArray(d.purchasePackages)?d.purchasePackages.map((pkg:any)=>pkg.barcode):[])].some(value=>value&&barcodeEquals(String(value),code))});if(duplicate){setUnknownError(`“${code}” already matches a stock code or barcode. Resolve the duplicate in Catalog first.`);return}const d=data(target)!;const aliases=Array.isArray(d.barcodeAliases)?d.barcodeAliases.filter((value:unknown)=>typeof value==='string'):[];setCommandNotice('');setUnknownBusy(code);setUnknownError('');try{const outcome=await command('stockItem.save','stockItems',target.id,{id:target.id,data:{name:String(d.name||''),code:String(d.code||''),baseUnit:String(d.baseUnit||'unit'),barcode:d.barcode||undefined,barcodeAliases:Array.from(new Set([...aliases,code])),purchasePackages:Array.isArray(d.purchasePackages)?d.purchasePackages:[],scanUnitQuantity:Number(d.scanUnitQuantity||1),reorderLevel:Number(d.reorderLevel||0),averageUnitCostMinor:Number(d.averageUnitCostMinor||0)}});if(isCommandConfirmed(outcome)){const next=unknownBarcodes.filter(value=>value!==code);setUnknownBarcodes(next);localStorage.setItem(sessionKey+':unknown',JSON.stringify(next));setUnknownTargets(value=>{const copy={...value};delete copy[code];return copy})}else setUnknownError(`${outcomeMessage(outcome,'Barcode assignment')} The count draft is unchanged.`)}catch(error){setUnknownError(error instanceof Error?error.message:'Barcode assignment failed. The count draft is unchanged.')}finally{setUnknownBusy('')}};
  const updateCount=(stockId:string,value:unknown)=>{if(!resumable)return;try{const quantity=parseQuantity(value);const stock=stocks.find(item=>item.id===stockId);const d=stock?data(stock):undefined;const size=Number(d?.sealedContainerSize||0);const bottleCounts={...resumable.bottleCounts};if(d?.baseUnit==='ml'&&size>0)bottleCounts[stockId]={sealed:Math.floor(quantity/size),open:Number((quantity-Math.floor(quantity/size)*size).toFixed(6))};persistSession({...resumable,counts:{...(resumable.counts||{}),[stockId]:quantity},bottleCounts});setForm(prev=>({...prev,stockItemId:stockId,countedQty:quantity,...(bottleCounts[stockId]?{sealedContainers:bottleCounts[stockId].sealed,openQuantity:bottleCounts[stockId].open}:{})}))}catch{}}
  const updateBottleCount=(stockId:string,sealed:number,open:number)=>{if(!resumable)return;const stock=stocks.find(item=>item.id===stockId);const size=Number(data(stock)?.sealedContainerSize||0);if(!Number.isFinite(size)||size<=0||!Number.isInteger(sealed)||sealed<0||!Number.isFinite(open)||open<0||open>=size||sealed*size+open>1_000_000_000)return;let quantity:number;try{quantity=parseQuantity(sealed*size+open)}catch{return}persistSession({...resumable,counts:{...resumable.counts,[stockId]:quantity},bottleCounts:{...resumable.bottleCounts,[stockId]:{sealed,open}}});setForm(prev=>({...prev,stockItemId:stockId,countedQty:quantity,sealedContainers:sealed,openQuantity:open}))};
  const open=(kind:'COUNT'|'ADJUST'|'TRANSFER'|'WASTE',stock?:BusinessRecord,loc?:string)=>{
    setCommandNotice('');
    const s=stock||selected||stocks[0];
    const locationId=loc||resumable?.locationId||locations[0]?.id||'';
    if(kind==='COUNT'&&resumable&&resumable.locationId!==locationId&&(Object.values(resumable.counts).some(value=>value!==null)||unknownBarcodes.length>0)){
      setUnknownError('Finish the saved count at its starting location before opening a count for another location. Your current draft was kept.');
      return;
    }
    setUnknownError('');
    if(kind==='COUNT'){
      const same=resumable?.locationId===locationId;
      const baseline=same&&resumable?.baseline?resumable.baseline:Object.fromEntries(stocks.map(item=>{const d=data(item)!;return [item.id,{expectedQuantity:Number(d.currentStock?.[locationId]||0),name:String(d.name||''),baseUnit:String(d.baseUnit||''),scanUnitQuantity:Number(d.scanUnitQuantity||1),version:item.version}]}));
      const counts=same&&resumable?resumable.counts:Object.fromEntries(stocks.map(item=>[item.id,null]));
      const bottleCounts=same&&resumable?resumable.bottleCounts:{};
      const next:CountSession={locationId,startedAt:same&&resumable?resumable.startedAt:new Date().toISOString(),revision:same&&resumable?.revision||1,counts,bottleCounts,baseline};
      persistSession(next);
      const stockId=s?.id||'';const savedBottle=bottleCounts[stockId];const counted=typeof counts[stockId]==='number'?Number(counts[stockId]):null;
      const balance=s?sealedOpenBalance(s,locationId):null;const size=Number(data(s)?.sealedContainerSize||0);
      const bottle=savedBottle||(counted!==null&&size>0?splitBottleQuantity(size,counted):balance);
      setForm({stockItemId:stockId,locationId,toLocationId:locations.find(x=>x.id!==locationId)?.id||'',countedQty:counted??(bottle?bottle.sealed*size+bottle.open:Number(data(s)?.currentStock?.[locationId]||0)),sealedContainers:bottle?.sealed??0,openQuantity:bottle?.open??0,quantity:1,disposition:'SEALED',reason:'',scan:''});
    }else{
      const balance=s?sealedOpenBalance(s,locationId):null;
      setForm({stockItemId:s?.id||'',locationId,toLocationId:locations.find(x=>x.id!==locationId)?.id||'',countedQty:Number(data(s)?.currentStock?.[locationId]||0),expectedQuantity:Number(data(s)?.currentStock?.[locationId]||0),expectedBaseUnit:String(data(s)?.baseUnit||''),expectedSealedContainerSize:Number(data(s)?.sealedContainerSize||0),expectedSealedContainers:balance?.sealed??null,expectedOpenQuantity:balance?.open??null,sealedContainers:balance?.sealed??0,openQuantity:balance?.open??0,quantity:1,disposition:'SEALED',reason:'',scan:''});
    }
    setSelectedId(s?.id||'');setModal(kind);
  };
  const scan=(raw:string)=>{if(modal!=='COUNT')return;const code=raw.trim();if(!code)return;const matches=stocks.filter(s=>{const d=data(s)!;return barcodeEquals(String(d.barcode||''),code)||barcodeEquals(String(d.code||''),code)||(Array.isArray(d.barcodeAliases)&&d.barcodeAliases.some((alias:any)=>barcodeEquals(String(alias),code)))||(Array.isArray(d.purchasePackages)&&d.purchasePackages.some((pkg:any)=>barcodeEquals(String(pkg.barcode||''),code)))});if(matches.length!==1){setUnknownBarcodes(previous=>{const next=Array.from(new Set([...previous,code]));localStorage.setItem(sessionKey+':unknown',JSON.stringify(next));return next}) ;return}const s=matches[0];const d=data(s)!;const pkg=Array.isArray(d.purchasePackages)?d.purchasePackages.find((candidate:any)=>barcodeEquals(String(candidate.barcode||''),code)):undefined;let increment:number;try{increment=parseQuantity(pkg?.baseQuantity??d.scanUnitQuantity??1,{min:Number.MIN_VALUE})}catch{return}setSelectedId(s.id);updateCount(s.id,countValue(s.id)+increment);setForm(prev=>({...prev,scan:''}))};
 useEffect(()=>{const onInput=(event:Event)=>{if(modal!=='COUNT')return;const target=event.target;if(target instanceof HTMLInputElement&&target.type==='number'&&target.dataset.bottleState!=='true')updateCount(form.stockItemId,target.value)};document.addEventListener('input',onInput,true);return()=>document.removeEventListener('input',onInput,true)},[modal,form.stockItemId,resumable]);
 useBarcodeScanner({enabled:modal==='COUNT',onScan:scan});
 const commitAdjustment=async()=>{const id=form.stockItemId;let countedQty:number;try{countedQty=adjustmentBreakdownRequired?parseQuantity(Number(form.sealedContainers)*adjustmentSize+Number(form.openQuantity)):parseQuantity(form.countedQty)}catch{return}const outcome=await command('inventory.adjust','stockItems',id,{id,stockItemId:id,locationId:form.locationId,expectedQuantity:Number(form.expectedQuantity),expectedBaseUnit:String(form.expectedBaseUnit||''),expectedSealedContainerSize:Number(form.expectedSealedContainerSize||0),...(adjustmentBreakdownRequired?{expectedSealedContainers:Number(form.expectedSealedContainers),expectedOpenQuantity:Number(form.expectedOpenQuantity),sealedContainers:Number(form.sealedContainers),openQuantity:Number(form.openQuantity)}:{}),countedQty,reason:String(form.reason||'').trim()});setCommandNotice(outcomeMessage(outcome,'Stock correction'));if(isCommandConfirmed(outcome))setModal(null)};
 const commit=async()=>{
  const id=form.stockItemId;let outcome:CommandOutcome|undefined;
  if(modal==='ADJUST'){
   let countedQty:number;try{countedQty=parseQuantity(form.countedQty)}catch{return}
   outcome=await command('inventory.adjust','stockItems',id,{id,stockItemId:id,locationId:form.locationId,countedQty,reason:String(form.reason||'').trim()});
  }else if(modal==='COUNT'&&resumable){
   const rows=stocks.map(stock=>{const d=data(stock)!;const baseline=resumable.baseline?.[stock.id];let countedQuantity:number;let scanUnitQuantity:number;try{countedQuantity=parseQuantity(resumable.counts?.[stock.id]);scanUnitQuantity=parseQuantity(baseline?.scanUnitQuantity??d.scanUnitQuantity??1,{min:Number.MIN_VALUE})}catch{return null}const size=Number(d.sealedContainerSize||0);const bottle=size>0&&d.baseUnit==='ml'?(resumable.bottleCounts?.[stock.id]||{sealed:Math.floor(countedQuantity/size),open:Number((countedQuantity-Math.floor(countedQuantity/size)*size).toFixed(6))}):null;return {stockItemId:stock.id,expectedQuantity:baseline?.expectedQuantity??Number(d.currentStock?.[resumable.locationId]||0),countedQuantity,...(bottle?{countedSealedContainers:bottle.sealed,countedOpenQuantity:bottle.open}:{}),name:baseline?.name||String(d.name||''),baseUnit:baseline?.baseUnit||String(d.baseUnit||''),scanUnitQuantity}});
   if(rows.some(row=>row===null))return;
   outcome=await command('inventory.countLocation','stockItems',id,{id,locationId:resumable.locationId,sessionId:sessionKey,sessionRevision:resumable.revision,rows,reason:form.reason||'Physical stock count',unknownBarcodes});
  }else if(modal==='TRANSFER'||modal==='WASTE'){
   let quantity:number;try{quantity=parseQuantity(form.quantity,{min:Number.MIN_VALUE})}catch{return}
   const operation=modal==='TRANSFER'?'inventory.transfer':'inventory.waste';
   outcome=await command(operation,'stockItems',id,{id,stockItemId:id,locationId:form.locationId,...(modal==='TRANSFER'?{toLocationId:form.toLocationId}:{}),...movementPayload({...data(stocks.find(stock=>stock.id===id)),id},form.disposition||'SEALED',String(quantity),form.reason)});
  }
  if(!outcome)return;setCommandNotice(outcomeMessage(outcome,'Inventory action'));if(!isCommandConfirmed(outcome))return;
  if(modal==='COUNT'){localStorage.removeItem(sessionKey);localStorage.removeItem(sessionKey+':unknown');setResumable(null);setUnknownBarcodes([])}setModal(null);
 };
 const selectedData=data(selected);
 const recent=selected?movements.filter(m=>data(m)?.stockItemId===selected.id).slice(0,12):[];
 const countIncomplete=modal==='COUNT'&&!!resumable&&stocks.some(stock=>resumable.counts?.[stock.id]===null||resumable.counts?.[stock.id]===undefined);
 const countStock=stocks.find(stock=>stock.id===form.stockItemId);const countSize=Number(data(countStock)?.sealedContainerSize||0);const countBottleRequired=modal==='COUNT'&&data(countStock)?.baseUnit==='ml'&&countSize>0;const countBottleInvalid=countBottleRequired&&(!Number.isInteger(Number(form.sealedContainers))||Number(form.sealedContainers)<0||!Number.isFinite(Number(form.openQuantity))||Number(form.openQuantity)<0||Number(form.openQuantity)>=countSize||Number(form.sealedContainers)*countSize+Number(form.openQuantity)>1_000_000_000||Math.abs(Number(form.countedQty)-(Number(form.sealedContainers)*countSize+Number(form.openQuantity)))>0.001);
 const adjustmentStock=stocks.find(stock=>stock.id===form.stockItemId);const adjustmentSize=Number(data(adjustmentStock)?.sealedContainerSize||0);const adjustmentSealedBalance=adjustmentStock&&Number.isFinite(Number(form.expectedSealedContainers))&&Number.isFinite(Number(form.expectedOpenQuantity))?{sealed:Number(form.expectedSealedContainers),open:Number(form.expectedOpenQuantity)}:null;const adjustmentBreakdownRequired=modal==='ADJUST'&&adjustmentSize>0;const adjustmentBreakdownInvalid=adjustmentBreakdownRequired&&(!adjustmentSealedBalance||!Number.isInteger(Number(form.sealedContainers))||Number(form.sealedContainers)<0||!Number.isFinite(Number(form.openQuantity))||Number(form.openQuantity)<0||Number(form.openQuantity)>=adjustmentSize);
 return <section className="space-y-5">
   {unknownError&&<p role="alert" className="rounded-lg border border-rose-700/40 bg-rose-500/5 p-3 text-sm text-rose-200">{unknownError}</p>}
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">Stock</h2><p className="mt-1 text-sm text-slate-400">{apiAuthority?'Review stock, record counts, transfers, and waste.':'See what is on hand, count a storage place, move stock, or record waste.'}</p>{apiAuthority&&<p className="mt-1 text-xs text-slate-400">Transfers and waste require an active connection; batch preparation requires an active connection; corrections require a reason and current balance.</p>}{!apiAuthority&&resumable&&<p className="mt-2 text-xs text-amber-200">A count session for {String(resumable.locationId)} is saved on this browser and can be resumed.</p>}{!apiAuthority&&unknownBarcodes.length>0&&<p className="mt-1 text-xs text-rose-200">{unknownBarcodes.length} unknown barcode(s) waiting for assignment.</p>}</div><div className="flex flex-wrap gap-2">{canBatch&&<button disabled={disabled} className={button} onClick={()=>{setCommandNotice('');setBatchOpen(true)}}>Prepare batch</button>}{canCount&&<button data-guide-anchor="inventory.count" disabled={disabled} className={primary} onClick={()=>!apiAuthority&&resumable?open('COUNT'):setPhysicalCount({scope:'FULL',locationId:''})}>{!apiAuthority&&resumable?'Resume count':'Count stock'}</button>}{canCount&&(apiAuthority||!resumable)&&<button disabled={disabled} className={button} onClick={()=>setPhysicalCount({scope:'SELECTED',locationId:''})}>Quick count</button>}{canCorrect&&<button disabled={disabled||!selected} className={button} onClick={()=>open('ADJUST',selected)}>Correct selected stock</button>}{canTransfer&&<button disabled={disabled} className={button} onClick={()=>open('TRANSFER')}>Transfer</button>}{canWaste&&<button disabled={disabled} className={button} onClick={()=>open('WASTE')}>Waste</button>}</div></div>
  {commandNotice&&<p role="status" className="rounded-lg border border-slate-700 bg-slate-900 p-3 text-sm">{commandNotice}</p>}
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Boxes className="h-4 w-4"/>} label="Stock masters" value={String(stocks.length)}/><Metric icon={<PackageCheck className="h-4 w-4"/>} label="Stock value" value={money(stockValue)}/><Metric icon={<AlertTriangle className="h-4 w-4"/>} label="Low stock" value={String(stocks.filter(s=>status(s)==='LOW').length)}/><Metric icon={<AlertTriangle className="h-4 w-4"/>} label="Out of stock" value={String(stocks.filter(s=>status(s)==='OUT').length)}/></div>
  <div className="grid gap-2 md:grid-cols-[1fr_180px_220px]"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-500"/><input className={field+' pl-9'} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search stock name, SKU or barcode"/></label><select className={field} value={state} onChange={e=>setState(e.target.value)}><option value="ALL">All stock states</option><option>HEALTHY</option><option>LOW</option><option>OUT</option></select><select className={field} value={location} onChange={e=>setLocation(e.target.value)}><option value="ALL">All locations / total</option>{locations.map(l=><option key={l.id} value={l.id}>{String(data(l)?.name)}</option>)}</select></div>
  <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-900 text-xs uppercase text-slate-500"><tr><th className="p-3">Stock item</th><th className="p-3">State</th><th className="p-3 text-right">On hand</th><th className="p-3 text-right">Reorder</th><th className="p-3 text-right">Value</th></tr></thead><tbody>{rows.map(({stock,total:qty,status:st})=>{const d=data(stock)!;const shown=location==='ALL'?qty:Number(d.currentStock?.[location]||0);return <tr key={stock.id} onClick={()=>setSelectedId(stock.id)} className="cursor-pointer border-t border-slate-800 hover:bg-slate-900"><td className="p-3"><b>{String(d.name)}</b><div className="font-mono text-[11px] text-slate-500">{String(d.code)}</div></td><td className="p-3"><span className={`rounded-full border px-2 py-1 text-[10px] font-black ${tone(st)}`}>{st}</span></td><td className="p-3 text-right font-mono">{physicalStock({...d,id:stock.id},location==='ALL'?undefined:location)}<small className="block text-slate-500">{shown.toLocaleString()} {String(d.baseUnit||'')}</small></td><td className="p-3 text-right">{Number(d.reorderLevel||0).toLocaleString()}</td><td className="p-3 text-right">{money(qty*Number(d.averageUnitCostMinor||0))}</td></tr>})}</tbody></table></div>
   <aside className="rounded-xl border border-slate-800 bg-slate-900 p-4">{selected&&selectedData?<><div className="flex items-start justify-between"><div><div className="text-xs uppercase text-slate-500">Selected stock</div><h3 className="text-lg font-bold">{String(selectedData.name)}</h3></div><span className={`rounded-full border px-2 py-1 text-[10px] font-black ${tone(status(selected))}`}>{status(selected)}</span></div><div className="mt-4 space-y-2">{locations.map(l=>{const balance=sealedOpenBalance(selected,l.id);return <button key={l.id} disabled={!canCount||disabled} onClick={()=>!apiAuthority&&resumable?open('COUNT',selected,l.id):setPhysicalCount({scope:'FULL',locationId:l.id})} className="flex w-full items-center justify-between rounded-lg border border-slate-800 bg-slate-950 p-3 text-left"><span>{String(data(l)?.name)}{balance&&<span className="mt-1 block text-xs text-slate-400">{balance.sealed} sealed · {balance.open.toLocaleString()} ml open</span>}</span><span className="text-right font-mono">{Number(selectedData.currentStock?.[l.id]||0).toLocaleString()} {String(selectedData.baseUnit||'')}</span></button>})}</div><div className="mt-5 text-xs font-bold uppercase text-slate-500">Recent movements</div><div className="mt-2 max-h-64 space-y-2 overflow-auto">{recent.map(m=>{const d=data(m)!;const effect=d.sealedOpenEffect||d.sealedOpenAfter;return <div key={m.id} className="rounded-lg bg-slate-950 p-3 text-xs"><div className="flex justify-between gap-2"><b>{String(d.movementType)}</b><span>{Number(d.quantityDelta)>0?'+':''}{Number(d.quantityDelta).toLocaleString()} {String(d.baseUnit||'')}</span></div>{effect&&<div className="mt-1 text-amber-200">{Number(effect.sealedContainersBefore??effect.sealedContainers??0)} → {Number(effect.sealedContainersAfter??effect.sealedContainers??0)} sealed · {Number(effect.openQuantityBefore??effect.openQuantity??0).toLocaleString()} → {Number(effect.openQuantityAfter??effect.openQuantity??0).toLocaleString()} ml open</div>}<div className="mt-1 text-slate-500">{String(d.reason||d.reasonCode||'')}</div>{canReverseMovement&&['WASTE','TRANSFER_IN','TRANSFER_OUT'].includes(String(d.movementType))&&<button className={button} onClick={()=>setReversing(m)}>Correct mistake ? Reverse recording</button>}</div>})}</div></>:<p className="text-sm text-slate-500">No stock items.</p>}</aside>
  </div>
   <WebStockCountHistory records={records}/>
   {reversing&&<WebLinkedCorrectionDialog records={records} session={session} record={reversing} movement command={command} onClose={()=>setReversing(null)}/>}
   {physicalCount&&<WebPhysicalCountDialog records={records} session={session} scope={physicalCount.scope} locationId={physicalCount.locationId} command={command} onClose={()=>setPhysicalCount(null)}/>}
   {batchOpen&&<Modal title="Prepare a recipe batch" onClose={()=>setBatchOpen(false)}><WebBatchPreparationForm products={products} stocks={stocks} locations={locations} disabled={disabled} onClose={()=>setBatchOpen(false)} onSubmit={async payload=>{const target=String(payload.outputStockItemId||'');const outcome=await command('inventory.produceBatch','stockItems',target,{id:target,...payload});setCommandNotice(outcomeMessage(outcome,'Batch preparation'));if(isCommandConfirmed(outcome))setBatchOpen(false);return outcome}}/></Modal>}
   {modal&&<Modal title={modal==='COUNT'?'Physical stock count':modal==='ADJUST'?'Admin stock correction':modal==='TRANSFER'?'Transfer stock':'Record waste'} onClose={()=>setModal(null)}>
    <div className="space-y-3">
     {commandNotice&&<p role="status" className="rounded-lg border border-slate-700 bg-slate-900 p-3 text-sm">{commandNotice}</p>}
     <label className="block text-sm">Stock item<select className={field} value={form.stockItemId} onChange={event=>{const stockId=event.target.value;const stock=stocks.find(item=>item.id===stockId);const balance=stock?sealedOpenBalance(stock,form.locationId):null;const saved=resumable?.bottleCounts?.[stockId];const counted=resumable?.counts?.[stockId];const size=Number(data(stock)?.sealedContainerSize||0);const bottle=saved||(typeof counted==='number'&&size>0?splitBottleQuantity(size,counted):balance);setForm({...form,stockItemId:stockId,countedQty:modal==='ADJUST'?Number(data(stock)?.currentStock?.[form.locationId]||0):typeof counted==='number'?counted:bottle?bottle.sealed*size+bottle.open:Number(data(stock)?.currentStock?.[form.locationId]||0),expectedQuantity:Number(data(stock)?.currentStock?.[form.locationId]||0),expectedBaseUnit:String(data(stock)?.baseUnit||''),expectedSealedContainerSize:Number(data(stock)?.sealedContainerSize||0),expectedSealedContainers:balance?.sealed??null,expectedOpenQuantity:balance?.open??null,sealedContainers:bottle?.sealed??0,openQuantity:bottle?.open??0})}}>{stocks.map(stock=><option key={stock.id} value={stock.id}>{String(data(stock)?.name)}</option>)}</select></label>
     <label className="block text-sm">Location<select disabled={modal==='COUNT'} className={field} value={form.locationId} onChange={event=>{const locationId=event.target.value;const stock=stocks.find(item=>item.id===form.stockItemId);const balance=stock?sealedOpenBalance(stock,locationId):null;setForm({...form,locationId,toLocationId:locations.find(location=>location.id!==locationId)?.id||'',countedQty:Number(data(stock)?.currentStock?.[locationId]||0),expectedQuantity:Number(data(stock)?.currentStock?.[locationId]||0),expectedBaseUnit:String(data(stock)?.baseUnit||''),expectedSealedContainerSize:Number(data(stock)?.sealedContainerSize||0),expectedSealedContainers:balance?.sealed??null,expectedOpenQuantity:balance?.open??null,sealedContainers:balance?.sealed??0,openQuantity:balance?.open??0})}}>{locations.map(location=><option key={location.id} value={location.id}>{String(data(location)?.name)}</option>)}</select>{modal==='COUNT'&&<span className="mt-1 block text-xs text-slate-500">A count draft is tied to its starting location. Close and choose another location from the stock list to count elsewhere.</span>}</label>
     {modal==='TRANSFER'&&<label className="block text-sm">Destination<select className={field} value={form.toLocationId} onChange={event=>setForm({...form,toLocationId:event.target.value})}>{locations.filter(location=>location.id!==form.locationId).map(location=><option key={location.id} value={location.id}>{String(data(location)?.name)}</option>)}</select></label>}
     {modal==='COUNT'?<>
      <div className="grid grid-cols-2 gap-2"><Fact label="Expected" value={`${Number(data(stocks.find(stock=>stock.id===form.stockItemId))?.currentStock?.[form.locationId]||0).toLocaleString()}`}/><Fact label="Draft variance" value={`${(Number(form.countedQty)-Number(data(stocks.find(stock=>stock.id===form.stockItemId))?.currentStock?.[form.locationId]||0)).toLocaleString()}`}/></div>
      {unknownBarcodes.length>0&&<div className="space-y-2 rounded-lg border border-rose-700/40 bg-rose-500/5 p-3 text-xs"><b>Unknown barcodes · resolve before count</b>{unknownBarcodes.map(code=>{const duplicate=stocks.some(item=>{const d=data(item)!;return [d.barcode,d.code,...(Array.isArray(d.barcodeAliases)?d.barcodeAliases:[]),...(Array.isArray(d.purchasePackages)?d.purchasePackages.map((pkg:any)=>pkg.barcode):[])].some(value=>value&&barcodeEquals(String(value),code))});return <div key={code} className="grid gap-2 rounded-lg bg-slate-950 p-2 sm:grid-cols-[1fr_1fr_auto_auto] sm:items-center"><code>{code}</code><select aria-label={`Assign ${code} to stock item`} className={field} value={unknownTargets[code]||''} onChange={event=>setUnknownTargets(previous=>({...previous,[code]:event.target.value}))}><option value="">Choose matching stock item</option>{stocks.map(item=><option key={item.id} value={item.id}>{String(data(item)?.name)}</option>)}</select>{canAssignBarcode&&!duplicate&&<button type="button" disabled={disabled||!unknownTargets[code]||Boolean(unknownBusy)} className={button} onClick={()=>void assignUnknownBarcode(code)}>{unknownBusy===code?'Saving…':'Assign barcode'}</button>}{duplicate&&<span className="text-amber-200">Duplicate match: correct Catalog first</span>}<button type="button" className={button} disabled={Boolean(unknownBusy)} onClick={()=>setUnknownBarcodes(previous=>{const next=previous.filter(value=>value!==code);localStorage.setItem(sessionKey+':unknown',JSON.stringify(next));return next})}>Remove</button></div>})}{unknownError&&<p role="alert" className="text-rose-200">{unknownError}</p>}<p className="text-slate-400">Assignment queues a barcode-alias update and does not change stock. Rescan the assigned code to add its scan quantity; count submission stays blocked until every unresolved code is assigned or explicitly removed.</p></div>}
      {countBottleRequired?<><p className="rounded-lg border border-amber-600/30 bg-amber-500/5 p-3 text-sm">Count sealed bottles and the liquid in the one open bottle. Total on hand is calculated for this location.</p><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm">Sealed bottles<input data-bottle-state="true" type="number" min="0" max="1000000000" step="1" className={field} value={form.sealedContainers} onChange={event=>updateBottleCount(form.stockItemId,Number(event.target.value),Number(form.openQuantity||0))}/></label><label className="block text-sm">Open liquid (ml)<input data-bottle-state="true" type="number" min="0" max={Math.max(0,countSize-0.000001)} step="0.1" className={field} value={form.openQuantity} onChange={event=>updateBottleCount(form.stockItemId,Number(form.sealedContainers||0),Number(event.target.value))}/></label></div><Fact label="Calculated physical quantity" value={`${Number(form.countedQty||0).toLocaleString()} ml`}/>{countBottleInvalid&&<p role="alert" className="text-sm text-rose-200">Enter whole sealed bottles and less than {countSize} ml for the open bottle.</p>}</>:<label className="block text-sm">Physical quantity<input type="number" min="0" step="0.001" className={field} value={form.countedQty} onChange={event=>{try{setForm({...form,countedQty:parseQuantity(event.target.value)})}catch{}}}/></label>}
      <label className="block text-sm">Scan barcode / SKU<input data-barcode-capture="true" className={field} value={form.scan} onChange={event=>setForm({...form,scan:event.target.value})}/></label><button type="button" className={button} disabled={!form.scan.trim()} onClick={()=>scan(form.scan)}>Apply typed barcode</button>
     </>:modal==='ADJUST'?adjustmentBreakdownRequired?<><div className="rounded-lg border border-amber-600/30 bg-amber-500/5 p-3 text-sm">Reviewed before: {adjustmentSealedBalance?`${adjustmentSealedBalance.sealed} sealed · ${adjustmentSealedBalance.open} ml open`: 'Sealed/open balance is not reconciled'}<br/>Corrected equivalent: {(Number(form.sealedContainers||0)*adjustmentSize+Number(form.openQuantity||0)).toLocaleString()} ml · change {((Number(form.sealedContainers||0)*adjustmentSize+Number(form.openQuantity||0))-Number(form.expectedQuantity||0)).toLocaleString()} ml</div><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm">Correct sealed bottles<input type="number" min="0" step="1" className={field} value={form.sealedContainers} onChange={event=>setForm({...form,sealedContainers:Number(event.target.value)})}/></label><label className="block text-sm">Open liquid (ml)<input type="number" min="0" max={Math.max(0,adjustmentSize-0.000001)} step="0.1" className={field} value={form.openQuantity} onChange={event=>setForm({...form,openQuantity:Number(event.target.value)})}/></label></div>{adjustmentBreakdownInvalid&&<p role="alert" className="text-sm text-rose-200">Enter whole sealed bottles and less than {adjustmentSize} ml in the open bottle.</p>}</>:<><div className="grid grid-cols-2 gap-2"><Fact label="Reviewed balance" value={`${Number(form.expectedQuantity||0).toLocaleString()} ${String(form.expectedBaseUnit||'')}`}/><Fact label="Change" value={`${(Number(form.countedQty)-Number(form.expectedQuantity||0)).toLocaleString()} ${String(form.expectedBaseUnit||'')}`}/></div><label className="block text-sm">Corrected physical balance<input type="number" min="0" step="0.001" className={field} value={form.countedQty} onChange={event=>{try{setForm({...form,countedQty:parseQuantity(event.target.value)})}catch{}}}/></label></>:<><label className="block text-sm">Physical stock<select className={field} value={form.disposition||'SEALED'} onChange={event=>setForm({...form,disposition:event.target.value})}><option value="SEALED">Sealed bottles (where configured)</option><option value="OPEN">Open liquid / base units</option></select></label><label className="block text-sm">Quantity<input type="number" min="0.001" step="0.001" className={field} value={form.quantity} onChange={event=>setForm({...form,quantity:event.target.value})}/></label></>}
     <label className="block text-sm">Reason / review note<textarea className={field} value={form.reason} onChange={event=>setForm({...form,reason:event.target.value})}/></label>
     <button disabled={disabled||countIncomplete||modal==='COUNT'&&(unknownBarcodes.length>0||countBottleInvalid)||modal==='ADJUST'&&(!String(form.reason||'').trim()||!form.stockItemId||adjustmentBreakdownInvalid)||(modal==='TRANSFER'||modal==='WASTE')&&(!String(form.reason||'').trim()||!form.stockItemId||!Number.isFinite(Number(form.quantity))||Number(form.quantity)<=0||modal==='TRANSFER'&&!form.toLocationId)} className={primary} onClick={()=>void(modal==='ADJUST'?commitAdjustment():commit())}>{modal==='ADJUST'?'Post correction':'Review and confirm'}</button>
    </div>
   </Modal>}
   {countIncomplete&&<p className="rounded-lg border border-amber-800 bg-amber-950/30 p-3 text-sm text-amber-100">Enter a physical quantity for every active stock item before reviewing this location count. Zero is a valid counted quantity.</p>}
 </section>;
}

function WebBatchPreparationForm({products,stocks,locations,disabled,onClose,onSubmit}:{products:BusinessRecord[];stocks:BusinessRecord[];locations:BusinessRecord[];disabled:boolean;onClose:()=>void;onSubmit:(payload:Record<string,unknown>)=>Promise<CommandOutcome>}){
 const recipes=products.filter(product=>data(product)?.inventoryType==='BATCH'&&typeof data(product)?.stockItemId==='string'&&data(product)?.stockItemId&&Array.isArray(data(product)?.recipeIngredients)&&data(product)!.recipeIngredients.length>0);
 const [recipeProductId,setRecipeProductId]=useState(recipes[0]?.id||'');const [locationId,setLocationId]=useState(locations[0]?.id||'');const [batchCount,setBatchCount]=useState(1);const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const recipe=recipes.find(product=>product.id===recipeProductId);const recipeData=data(recipe);const ingredients=Array.isArray(recipeData?.recipeIngredients)?recipeData.recipeIngredients:[];const linkedOutputId=String(recipeData?.stockItemId||'');const eligible=stocks.filter(stock=>stock.id===linkedOutputId&&['piece','portion'].includes(String(data(stock)?.baseUnit||'piece').toLowerCase()));const output=eligible.find(stock=>stock.id===linkedOutputId);const yieldPerBatch=Number(recipeData?.recipeYield||0);const outputCount=yieldPerBatch*batchCount;
 const submit=async(event:React.FormEvent)=>{event.preventDefault();setError('');if(!recipe||!output||!locationId||!Number.isInteger(batchCount)||batchCount<1||batchCount>1000||reason.trim().length<3)return;setBusy(true);try{const outcome=await onSubmit({recipeProductId,outputStockItemId:linkedOutputId,locationId,batchCount,reason:reason.trim()});if(!isCommandConfirmed(outcome))setError(`${outcomeMessage(outcome,'Batch preparation')} Keep this form open and review Activity before retrying.`)}catch(cause){setError(String(cause))}finally{setBusy(false)}};
 return <form className="max-h-[70vh] space-y-3 overflow-y-auto" onSubmit={event=>void submit(event)}>{!recipes.length?<p className="rounded-lg border border-amber-600/30 bg-amber-500/5 p-3 text-sm">No saved Batch recipe is available. Create a Batch recipe in Catalog first.</p>:<>
  <label className="block text-sm">Batch recipe<select className={field+' mt-1'} value={recipeProductId} onChange={event=>setRecipeProductId(event.target.value)}>{recipes.map(item=><option key={item.id} value={item.id}>{String(data(item)?.name||item.id)}</option>)}</select></label>
  <div className="rounded-lg border border-slate-800 bg-slate-950 p-3 text-sm"><b>Finished portions stock</b><p className="mt-1">{output?`${String(data(output)?.name)} · ${String(data(output)?.baseUnit)}`:'Linked output stock must use piece or portion units.'}</p><p className="mt-1 text-xs text-slate-500">POS deducts prepared portions from this linked stock. The saved recipe ingredients are consumed here during preparation.</p></div>
  <label className="block text-sm">Storage place<select className={field+' mt-1'} value={locationId} onChange={event=>setLocationId(event.target.value)}><option value="">Choose storage place</option>{locations.map(item=><option key={item.id} value={item.id}>{String(data(item)?.name||item.id)}</option>)}</select></label>
  <label className="block text-sm">Number of batches<input className={field+' mt-1'} type="number" min="1" max="1000" step="1" value={batchCount} onChange={event=>setBatchCount(Number(event.target.value))}/></label>
  <div className="rounded-lg border border-slate-800 bg-slate-950 p-3 text-sm"><b>Preparation preview</b><p className="mt-1">{String(recipeData?.name||'Recipe')} yields {yieldPerBatch||'—'} portions per batch; this makes {outputCount||'—'} {String(data(output)?.baseUnit||'portions')}.</p><div className="mt-2 space-y-1 text-xs text-slate-400">{ingredients.map((line:any)=><p key={line.stockItemId}>{String(data(stocks.find(item=>item.id===line.stockItemId))?.name||line.stockItemId)}: {(Number(line.quantity)*yieldPerBatch*batchCount).toLocaleString()} {String(data(stocks.find(item=>item.id===line.stockItemId))?.baseUnit||'units')}</p>)}</div><p className="mt-2 text-xs text-slate-500">Ingredient consumption and finished stock commit together on the server. This action is online-only; offline work remains a draft.</p></div>
  <label className="block text-sm">Preparation note<input required minLength={3} maxLength={180} className={field+' mt-1'} value={reason} onChange={event=>setReason(event.target.value)}/></label>
 </>}{error&&<p role="alert" className="text-sm text-rose-200">{error}</p>}<div className="flex justify-end gap-2"><button type="button" className={button} onClick={onClose}>Close</button><button type="submit" disabled={disabled||busy||!recipe||!output||!locationId||reason.trim().length<3} className={primary}>{busy?'Preparing…':'Prepare batch'}</button></div></form>;
}

 const Panel=({title,children}:{title:string;children:React.ReactNode})=><section className="rounded-xl border border-slate-800 bg-slate-900/40 p-4"><h3 className="mb-3 font-bold">{title}</h3><div className="space-y-2">{children}</div></section>;
const Metric=({icon,label,value}:{icon:React.ReactNode;label:string;value:string})=><div className="rounded-xl border border-slate-800 bg-slate-900 p-4"><div className="flex items-center gap-2 text-xs uppercase text-slate-500">{icon}{label}</div><div className="mt-2 text-2xl font-black">{value}</div></div>;
const Fact=({label,value}:{label:string;value:string})=><div className="rounded-lg bg-slate-950 p-3"><div className="text-[10px] uppercase text-slate-600">{label}</div><div className="font-semibold">{value}</div></div>;
const Restore=({label,disabled,onRestore}:{record:BusinessRecord;label:string;disabled:boolean;onRestore:()=>Promise<void>})=><div className="flex items-center justify-between rounded-lg bg-slate-950 p-2 text-sm"><span>{label}</span><button disabled={disabled} className={button} onClick={()=>void onRestore()}>Reactivate</button></div>;
const Modal=({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode})=><Dialog title={title} onClose={onClose}>{children}</Dialog>;
