import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {LayoutGrid,Plus,RefreshCw,Save,Trash2} from 'lucide-react';
import {allowed,type BusinessRecord,type WebSession} from './session';
import {BlockerCard,BusyButton} from '../../design-system/controls';

type CommandFn=(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<boolean>;
type LayoutTable={id:string;propertyId:string;outletId:string;label:string;capacity:number;section:string;state:string;currentOrderId?:string|null;shape:'SQUARE'|'RECTANGLE'|'ROUND'|'BAR_TOP';posX:number;posY:number;minimumSpend:number;isJoinable:boolean;assignedServerId?:string|null;assignedServerName?:string};
type Baseline={id:string;version:number};
const data=(record?:BusinessRecord)=>record?.data as Record<string,unknown>|undefined;
const active=(records:BusinessRecord[],collection:string)=>records.filter(record=>record.collection===collection&&!record.archived);
const label=(record:BusinessRecord)=>String(data(record)?.name||data(record)?.label||record.id);
const row=(record:BusinessRecord,index:number):LayoutTable=>({
 id:record.id,propertyId:String(data(record)?.propertyId||'property'),outletId:String(data(record)?.outletId||''),label:String(data(record)?.label||String(index+1)),capacity:Number(data(record)?.capacity||4),section:String(data(record)?.section||'Main'),state:String(data(record)?.state||'AVAILABLE'),currentOrderId:typeof data(record)?.currentOrderId==='string'?String(data(record)?.currentOrderId):null,shape:(['SQUARE','RECTANGLE','ROUND','BAR_TOP'].includes(String(data(record)?.shape))?String(data(record)?.shape):'SQUARE') as LayoutTable['shape'],posX:Number(data(record)?.posX??10+(index%4)*20),posY:Number(data(record)?.posY??10+Math.floor(index/4)*20),minimumSpend:Number(data(record)?.minimumSpend??data(record)?.minimumSpendKes??0),isJoinable:Boolean(data(record)?.isJoinable??true),assignedServerId:typeof data(record)?.assignedServerId==='string'?String(data(record)?.assignedServerId):null,assignedServerName:String(data(record)?.assignedServerName||'Unassigned')
});

export function WebFloorplanView({records,session,disabled,command}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:CommandFn}){
 const outlets=active(records,'outlets');const employees=active(records,'employees').filter(person=>data(person)?.status==='ACTIVE');const canManage=allowed(session,'floorplan.manage');
 const [outletId,setOutletId]=useState(()=>outlets[0]?.id||'');const [tables,setTables]=useState<LayoutTable[]>([]);const [baseline,setBaseline]=useState<Baseline[]>([]);const [dirty,setDirty]=useState(false);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState('');
 const load=useCallback((selected:string)=>{const current=active(records,'tables').filter(record=>String(data(record)?.outletId||'')===selected).sort((a,b)=>String(data(a)?.label||'').localeCompare(String(data(b)?.label||'')));setTables(current.map(row));setBaseline(current.map(record=>({id:record.id,version:record.version})));setDirty(false);setNotice('')},[records]);
 useEffect(()=>{if(!dirty)load(outletId)},[load,outletId,dirty]);
 const current=useMemo(()=>active(records,'tables').filter(record=>String(data(record)?.outletId||'')===outletId),[records,outletId]);
 const stale=current.length!==baseline.length||baseline.some(item=>current.find(record=>record.id===item.id)?.version!==item.version);
 const labels=tables.map(table=>table.label.trim().toLocaleLowerCase());const duplicateLabel=labels.some((value,index)=>!value||labels.indexOf(value)!==index);
 const invalid=tables.some(table=>!Number.isInteger(table.capacity)||table.capacity<1||table.capacity>1000||!Number.isFinite(table.posX)||!Number.isFinite(table.posY)||table.posX<0||table.posX>100||table.posY<0||table.posY>100||!Number.isFinite(table.minimumSpend)||table.minimumSpend<0||!table.section.trim());
 const update=(id:string,patch:Partial<LayoutTable>)=>{setTables(items=>items.map(item=>item.id===id?{...item,...patch}:item));setDirty(true);setNotice('')};
 const add=()=>{const outlet=outlets.find(item=>item.id===outletId);const next:LayoutTable={id:crypto.randomUUID(),propertyId:String(data(outlet)?.propertyId||'property'),outletId,label:String(tables.length+1),capacity:4,section:'Main',state:'AVAILABLE',currentOrderId:null,shape:'SQUARE',posX:10+(tables.length%4)*20,posY:10+Math.floor(tables.length/4)*20,minimumSpend:0,isJoinable:true,assignedServerId:null,assignedServerName:'Unassigned'};setTables(items=>[...items,next]);setDirty(true);setNotice('')};
 const save=async()=>{if(!canManage||disabled||saving||!outletId||!dirty||stale||invalid||duplicateLabel)return;setSaving(true);setNotice('');try{if(await command('floorplan.save','tables',outletId,{outletId,baseline,tables})){setDirty(false);setNotice('Floorplan saved and synchronized.')}}catch{setNotice('The layout could not be saved. Reopen the latest layout and resolve any server or version conflict before retrying.')}finally{setSaving(false)}};
 return <section className="space-y-5" data-guide-anchor="web.floorplan">
  <header className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-2xl font-bold"><LayoutGrid className="h-6 w-6 text-amber-300"/>Floorplan</h2><p className="mt-1 text-sm text-slate-400">Edit table placement and service settings. Each outlet layout saves atomically; occupied table ownership is preserved.</p></div><label className="text-sm">Service outlet<select aria-label="Service outlet" className="mt-1 block min-w-52 rounded-lg border border-slate-700 bg-slate-950 p-2" value={outletId} onChange={event=>{setDirty(false);setOutletId(event.target.value)}}>{outlets.map(outlet=><option key={outlet.id} value={outlet.id}>{label(outlet)}</option>)}</select></label></header>
  {notice&&<p role="status" className="rounded-xl border border-slate-700 bg-slate-900 p-3 text-sm">{notice}</p>}
  {!canManage&&<BlockerCard title="Floorplan editing permission required">You can view the saved floorplan. Ask an Admin for floorplan.manage to make and save layout changes.</BlockerCard>}
  {stale&&dirty&&<><BlockerCard title="This layout is out of date">Another change reached the server after you opened this layout. Reload the latest outlet layout before editing or saving.</BlockerCard><button type="button" className="rounded-lg border border-slate-600 px-3 py-2 text-sm" onClick={()=>load(outletId)}><RefreshCw className="mr-2 inline h-4 w-4"/>Discard draft and reload</button></>}
  <div className="grid gap-4 xl:grid-cols-[minmax(0,2fr)_minmax(18rem,1fr)]">
   <div className="relative min-h-[360px] overflow-hidden rounded-2xl border border-slate-800 bg-slate-950" aria-label="Floorplan preview" role="img" style={{backgroundImage:'linear-gradient(rgba(148,163,184,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(148,163,184,.08) 1px,transparent 1px)',backgroundSize:'10% 10%'}}>
    {tables.map(table=><div key={table.id} className={`absolute flex min-h-10 min-w-14 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-xl border px-2 text-center text-xs font-bold shadow ${table.currentOrderId?'border-amber-400 bg-amber-400/20 text-amber-100':'border-emerald-500/60 bg-emerald-500/10 text-emerald-100'}`} style={{left:`${table.posX}%`,top:`${table.posY}%`,borderRadius:table.shape==='ROUND'?'999px':undefined}} title={`${table.label} · ${table.capacity} seats · ${table.section}`}>{table.label}<span className="ml-1 text-[10px] opacity-80">{table.currentOrderId?'BUSY':table.capacity}</span></div>)}
    {tables.length===0&&<p className="absolute inset-0 grid place-items-center text-sm text-slate-500">No tables in this outlet yet. Add a table to begin.</p>}
   </div>
   <aside className="space-y-3"><div className="flex items-center justify-between"><h3 className="font-bold">Tables ({tables.length})</h3><button type="button" disabled={!canManage||disabled||stale} onClick={add} className="rounded-lg border border-slate-700 px-3 py-2 text-sm disabled:opacity-40"><Plus className="mr-1 inline h-4 w-4"/>Add table</button></div>
    <div className="max-h-[520px] space-y-3 overflow-auto pr-1">{tables.map(table=><article key={table.id} className="space-y-2 rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="flex items-center justify-between"><strong>{table.label||'Unnamed table'}</strong><button type="button" title={table.currentOrderId?'Close or transfer the active order before removing this table':'Remove table'} disabled={!canManage||disabled||stale||Boolean(table.currentOrderId)} onClick={()=>{setTables(items=>items.filter(item=>item.id!==table.id));setDirty(true)}} className="rounded-lg p-2 text-rose-200 disabled:opacity-30"><Trash2 className="h-4 w-4"/><span className="sr-only">Remove {table.label}</span></button></div>
     <div className="grid grid-cols-2 gap-2 text-xs"><label>Label<input disabled={!canManage||disabled||stale} value={table.label} onChange={event=>update(table.id,{label:event.target.value})} className="mt-1 w-full rounded border border-slate-700 bg-slate-900 p-2"/></label><label>Capacity<input disabled={!canManage||disabled||stale} type="number" min="1" max="1000" value={table.capacity} onChange={event=>update(table.id,{capacity:Number(event.target.value)})} className="mt-1 w-full rounded border border-slate-700 bg-slate-900 p-2"/></label><label>Section<input disabled={!canManage||disabled||stale} value={table.section} onChange={event=>update(table.id,{section:event.target.value})} className="mt-1 w-full rounded border border-slate-700 bg-slate-900 p-2"/></label><label>Shape<select disabled={!canManage||disabled||stale} value={table.shape} onChange={event=>update(table.id,{shape:event.target.value as LayoutTable['shape']})} className="mt-1 w-full rounded border border-slate-700 bg-slate-900 p-2">{['SQUARE','RECTANGLE','ROUND','BAR_TOP'].map(shape=><option key={shape}>{shape}</option>)}</select></label><label>Position X<input disabled={!canManage||disabled||stale} type="number" min="0" max="100" value={table.posX} onChange={event=>update(table.id,{posX:Number(event.target.value)})} className="mt-1 w-full rounded border border-slate-700 bg-slate-900 p-2"/></label><label>Position Y<input disabled={!canManage||disabled||stale} type="number" min="0" max="100" value={table.posY} onChange={event=>update(table.id,{posY:Number(event.target.value)})} className="mt-1 w-full rounded border border-slate-700 bg-slate-900 p-2"/></label><label>Minimum spend (KES)<input disabled={!canManage||disabled||stale} type="number" min="0" step="0.01" value={table.minimumSpend} onChange={event=>update(table.id,{minimumSpend:Number(event.target.value)})} className="mt-1 w-full rounded border border-slate-700 bg-slate-900 p-2"/></label><label>Assigned server<select disabled={!canManage||disabled||stale} value={table.assignedServerId||''} onChange={event=>{const employee=employees.find(person=>person.id===event.target.value);update(table.id,{assignedServerId:employee?.id||null,assignedServerName:employee?label(employee):'Unassigned'})}} className="mt-1 w-full rounded border border-slate-700 bg-slate-900 p-2"><option value="">Unassigned</option>{employees.map(employee=><option key={employee.id} value={employee.id}>{label(employee)}</option>)}</select></label>
     </div>{table.currentOrderId&&<p className="text-xs text-amber-200">Occupied; layout settings are locked until the active order is transferred or settled.</p>}
    </article>)}</div>
   </aside>
  </div>
  {(duplicateLabel||invalid)&&<BlockerCard title="Review the layout before saving" description={duplicateLabel?'Every table needs a unique, non-empty label.': 'Use positive capacities, coordinates from 0 to 100, a section, and a non-negative minimum spend.'}/>}
  <footer className="sticky bottom-0 flex flex-wrap items-center justify-between gap-3 border-t border-slate-800 bg-slate-950/95 py-3"><span className="text-xs text-slate-500">{dirty?'Unsaved layout changes':'No unsaved changes'} · Baseline version checks protect against stale editors.</span><BusyButton type="button" busy={saving} disabled={!canManage||disabled||!dirty||stale||invalid||duplicateLabel||!outletId} onClick={()=>void save()} className="inline-flex items-center gap-2 rounded-xl bg-amber-400 px-4 py-2.5 font-bold text-slate-950 disabled:opacity-40"><Save className="h-4 w-4"/>Save layout</BusyButton></footer>
 </section>
}
