import React,{useState} from 'react';
import type {BusinessRecord,WebSession} from './session';
import {allowed} from './session';
import {operatorError} from './operatorError';
import {isCommandConfirmed,type CommandOutcome} from '../../types/transactions';

type CommandFn=(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<CommandOutcome>;
const field='w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm text-white';
const button='rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm font-semibold disabled:opacity-40';
const primary='rounded-lg bg-amber-400 px-3 py-2 text-sm font-bold text-slate-950 disabled:opacity-40';
const data=(record?:BusinessRecord)=>record?.data as Record<string,any>|undefined;
const active=(records:BusinessRecord[],collection:string)=>records.filter(r=>r.collection===collection&&!r.archived);
const money=(minor:unknown)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES'}).format(Number(minor||0)/100);
const minor=(value:string)=>{const amount=Number(value);if(!Number.isFinite(amount)||amount<0)throw new Error('Enter a valid nonnegative amount.');return Math.round(amount*100)};
const outcomeText=(outcome:CommandOutcome)=>{switch(outcome.kind){case'CONFIRMED':return 'Financial action confirmed and synchronized.';case'DRAFT_SAVED':return 'Financial action saved as a draft; it has not taken effect.';case'PENDING':return 'Financial action is waiting to synchronize. Do not submit it again.';case'OUTCOME_UNKNOWN':case'REJECTED':case'CONFLICT':case'BLOCKED':return outcome.message}};

export function WebFinanceView({records,session,disabled,command}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:CommandFn}){
 const tills=active(records,'tillSessions').slice().sort((a,b)=>String(data(b)?.openedAt||'').localeCompare(String(data(a)?.openedAt||'')));
 const reports=active(records,'closeDayReports').slice().sort((a,b)=>String(data(b)?.generatedAt||'').localeCompare(String(data(a)?.generatedAt||'')));
 const openTill=tills.find(till=>data(till)?.status==='OPEN');
 const [direction,setDirection]=useState<'PAID_IN'|'PAID_OUT'>('PAID_IN');
 const [movementAmount,setMovementAmount]=useState('');const [movementReason,setMovementReason]=useState('');
 const [countedCashDraft,setCountedCashDraft]=useState({tillId:'',actorId:'',value:''});const [varianceReasonDraft,setVarianceReasonDraft]=useState({tillId:'',actorId:'',value:''});const [outcome,setOutcome]=useState<CommandOutcome|null>(null);const [busy,setBusy]=useState(false);
 const countedCash=openTill&&countedCashDraft.tillId===openTill.id&&countedCashDraft.actorId===session.actorId?countedCashDraft.value:'';const varianceReason=openTill&&varianceReasonDraft.tillId===openTill.id&&varianceReasonDraft.actorId===session.actorId?varianceReasonDraft.value:'';
 const expectedCashMinor=Number(data(openTill)?.expectedCashMinor||0);const countedCashValue=countedCash;let countedCashMinor:number|null=null;if(countedCash!==''){try{countedCashMinor=minor(countedCashValue)}catch{}}const cashVarianceMinor=countedCashMinor===null?null:countedCashMinor-expectedCashMinor;const hasVariance=cashVarianceMinor!==null&&cashVarianceMinor!==0;const variancePolicy=active(records,'tillPolicy')[0];const varianceThresholdMinor=Math.max(0,Number(data(variancePolicy)?.varianceThresholdMinor??Number(data(variancePolicy)?.varianceThreshold||0)*100));const varianceNeedsAuthority=hasVariance&&Math.abs(cashVarianceMinor||0)>varianceThresholdMinor;const canOverrideVariance=allowed(session,'till.override_variance');
 const run=async(operation:string,collection:string,id:string,payload:Record<string,unknown>):Promise<CommandOutcome>=>{if(disabled||busy){const blocked:CommandOutcome={kind:'BLOCKED',message:'Wait for the current financial action to finish before submitting another.'};setOutcome(blocked);return blocked}setBusy(true);setOutcome(null);try{const result=await command(operation,collection,id,payload);setOutcome(result);return result}catch(error){const blocked:CommandOutcome={kind:'BLOCKED',message:`The financial action could not be confirmed. ${operatorError(error)} Review Activity before retrying.`};setOutcome(blocked);return blocked}finally{setBusy(false)}};
 const cashMovement=async()=>{if(!openTill)return;const result=await run('till.cashMovement','cashMovements',crypto.randomUUID(),{tillSessionId:openTill.id,direction,amountMinor:minor(movementAmount),reason:movementReason.trim()});if(isCommandConfirmed(result)){setMovementAmount('');setMovementReason('')}};
 const closeTill=async()=>{if(!openTill||countedCashMinor===null||hasVariance&&varianceReason.trim().length<3||varianceNeedsAuthority&&!canOverrideVariance)return;await run('till.close','tillSessions',openTill.id,{id:openTill.id,countedCashMinor,varianceReason:varianceReason.trim()});};
 const generate=async(till:BusinessRecord)=>run('closeDay.generate','closeDayReports',`close-day-${till.id}`,{tillId:till.id});
 return <section className="space-y-5">
  <header><h2 className="text-xl font-bold">Finance and close day</h2><p className="mt-1 text-sm text-slate-400">Cash movements and close reports are committed through versioned commands. External payments remain manually confirmed.</p></header>
  {outcome&&<p role={['OUTCOME_UNKNOWN','REJECTED','CONFLICT','BLOCKED'].includes(outcome.kind)?'alert':'status'} className={`rounded-lg border p-3 text-sm ${outcome.kind==='CONFIRMED'?'border-emerald-800 bg-emerald-950':'border-amber-800 bg-amber-950'}`}>{outcomeText(outcome)}</p>}
  {openTill?<article className="space-y-4 rounded-xl border border-slate-700 bg-slate-900/50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">Open till session</h3><p className="text-xs text-slate-500">Opened {new Date(String(data(openTill)?.openedAt)).toLocaleString()} · expected cash {money(data(openTill)?.expectedCashMinor)}</p></div><span className="rounded-full border border-amber-700 px-2 py-1 text-xs">OPEN</span></div>
   {allowed(session,'till.cashMovement')&&<div className="grid gap-2 sm:grid-cols-2"><label className="text-sm">Movement<select disabled={busy} className={field} value={direction} onChange={e=>setDirection(e.target.value as 'PAID_IN'|'PAID_OUT')}><option value="PAID_IN">Cash in</option><option value="PAID_OUT">Cash out</option></select></label><label className="text-sm">Amount (KES)<input disabled={busy} className={field} type="number" min="0.01" step="0.01" value={movementAmount} onChange={e=>setMovementAmount(e.target.value)}/></label><label className="text-sm sm:col-span-2">Reason<input disabled={busy} className={field} value={movementReason} onChange={e=>setMovementReason(e.target.value)}/></label><button disabled={disabled||busy||!movementAmount||movementAmount==='0'||movementReason.trim().length<3} className={button} onClick={()=>void cashMovement()}>{busy?'Recording…':'Record cash movement'}</button></div>}
   {allowed(session,'till.close')&&<div className="space-y-3 border-t border-slate-800 pt-4"><div className="grid gap-2 sm:grid-cols-3"><div className="rounded-lg bg-slate-950 p-3"><div className="text-xs text-slate-500">Expected cash</div><b>{money(expectedCashMinor)}</b></div><label className="text-sm">Counted cash (KES)<input disabled={busy} aria-label="Counted cash in KES" className={field} type="number" min="0" step="0.01" placeholder="Count the drawer" value={countedCashValue} onChange={e=>setCountedCashDraft({tillId:openTill?.id||'',actorId:session.actorId,value:e.target.value})}/></label><div className={`rounded-lg p-3 ${cashVarianceMinor===0?'bg-emerald-950/40 text-emerald-200':cashVarianceMinor===null?'bg-slate-950 text-slate-400':'bg-amber-950/40 text-amber-100'}`}><div className="text-xs opacity-70">Cash variance</div><b>{cashVarianceMinor===null?'Enter the physical count':`${cashVarianceMinor>0?'+':''}${money(cashVarianceMinor)}`}</b></div></div>{hasVariance&&<div className="grid gap-2 sm:grid-cols-[1fr_auto] sm:items-end"><label className="text-sm">Reason for variance<input disabled={busy} className={field} value={varianceReason} onChange={e=>setVarianceReasonDraft({tillId:openTill?.id||'',actorId:session.actorId,value:e.target.value})} placeholder="Explain the cash difference"/></label>{varianceNeedsAuthority&&!canOverrideVariance&&<p role="status" className="text-xs text-amber-200">This variance exceeds the configured tolerance of {money(varianceThresholdMinor)} and requires manager authority.</p>}{!varianceNeedsAuthority&&<p className="self-center text-xs text-slate-400">Within configured tolerance ({money(varianceThresholdMinor)}); record the reason for the cash difference.</p>}</div>}<button disabled={disabled||busy||countedCashMinor===null||hasVariance&&varianceReason.trim().length<3||varianceNeedsAuthority&&!canOverrideVariance} className={primary} onClick={()=>void closeTill()}>{busy?'Closing…':'Close till'}</button><p className="text-xs text-slate-500">Expected cash includes the opening float, cash payments, and recorded paid-in/paid-out movements. Open orders block close; the server remains authoritative.</p></div>}
  </article>:<p className="rounded-lg border border-slate-800 p-4 text-sm text-slate-400">No open till. Open the next till from POS before accepting cash or starting a shift.</p>}
  <section className="space-y-3"><h3 className="font-bold">Close-day reports</h3>{tills.filter(till=>data(till)?.status==='CLOSED').map(till=>{const report=reports.find(row=>data(row)?.tillSessionId===till.id);return <article key={till.id} className="rounded-xl border border-slate-800 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><b>Till {till.id.slice(0,12)}</b><p className="text-xs text-slate-500">{new Date(String(data(till)?.closedAt)).toLocaleString()} · variance {money(data(till)?.cashVarianceMinor)}</p></div>{!report&&allowed(session,'reports.view')&&<button disabled={disabled||busy} className={button} onClick={()=>void generate(till)}>{busy?'Generating…':'Generate close-day snapshot'}</button>}</div>{report&&<dl className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><div>Gross {money(data(report)?.sales?.grossMinor)}</div><div>Net {money(data(report)?.sales?.netMinor)}</div><div>Refunds {money(data(report)?.sales?.refundsMinor)}</div><div>Cash {money(data(report)?.tenders?.cashMinor)}</div><div>M-Pesa {money(data(report)?.tenders?.mpesaMinor)}</div><div>Card {money(data(report)?.tenders?.cardMinor)}</div><div>Counted {money(data(report)?.cash?.countedMinor)}</div><div>Variance {money(data(report)?.cash?.varianceMinor)}</div><div>M-Pesa review {String(data(report)?.reconciliation?.mpesaStatus||'')}</div></dl>}</article>})}{!tills.some(till=>data(till)?.status==='CLOSED')&&<p className="text-sm text-slate-500">Closed till sessions and immutable snapshots will appear here.</p>}</section>
 </section>;
}
