import React,{useMemo,useState} from 'react';
import {AlertTriangle,CheckCircle2,CreditCard,FileCheck2,Receipt,ShieldCheck,WalletCards} from 'lucide-react';
import {allowed,type BusinessRecord,type WebSession} from './session';
import {businessDateTimeInput,businessDateTimeToUtc} from '../../utils/businessTime';
import {Dialog} from '../../design-system/controls';
import {isCommandConfirmed,type CommandOutcome} from '../../types/transactions';
import {operatorError} from './operatorError';

type CommandFn=(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<CommandOutcome>;
const field='w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2.5 text-sm text-white outline-none focus:border-amber-400';
const button='rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-sm font-semibold text-slate-200 hover:bg-slate-800 disabled:opacity-40';
const primary='rounded-xl bg-amber-400 px-4 py-2.5 text-sm font-bold text-slate-950 hover:bg-amber-300 disabled:opacity-40';
const data=(record?:BusinessRecord)=>record?.data as Record<string,any>|undefined;
const active=(records:BusinessRecord[],collection:string)=>records.filter(record=>record.collection===collection&&!record.archived);
const money=(minor:unknown)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES'}).format(Number(minor||0)/100);
const minor=(value:string)=>{const amount=Number(value);if(!Number.isFinite(amount)||amount<0)throw new Error('Enter a valid nonnegative amount.');return Math.round(amount*100)};
const label=(record?:BusinessRecord)=>String(data(record)?.name||data(record)?.phone||record?.id||'Unknown');
const outcomeText=(outcome:CommandOutcome)=>{switch(outcome.kind){case'CONFIRMED':return 'Financial action confirmed and synchronized.';case'DRAFT_SAVED':return 'Financial action saved as a draft; it has not taken effect.';case'PENDING':return 'Financial action is waiting to synchronize. Do not submit it again.';case'OUTCOME_UNKNOWN':case'REJECTED':case'CONFLICT':case'BLOCKED':return outcome.message}};

export function WebFinancialControlsView({records,session,disabled,command}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:CommandFn}){
 const timeZone=String(active(records,'property')[0]?.data.timezone||'Africa/Nairobi');
 const customers=active(records,'customers');const accounts=active(records,'customerCreditAccounts');const entries=active(records,'customerCreditEntries');
 const reconciliations=active(records,'customerCreditReconciliations').slice().reverse();const discrepancies=active(records,'customerCreditDiscrepancies').slice().reverse();
 const receipts=active(records,'mpesaReceipts').slice().reverse();const mpesaDiscrepancies=active(records,'mpesaDiscrepancies').slice().reverse();
 const [customerId,setCustomerId]=useState('');const customer=customers.find(record=>record.id===customerId)||customers[0];
 const [outcome,setOutcome]=useState<CommandOutcome|null>(null);const [busy,setBusy]=useState(false);const [receiptOpen,setReceiptOpen]=useState(false);const [settleOpen,setSettleOpen]=useState(false);const [reconcileOpen,setReconcileOpen]=useState(false);const [writeOffOpen,setWriteOffOpen]=useState(false);const [resolveId,setResolveId]=useState('');const [creditLimit,setCreditLimit]=useState('');const [mpesaReview,setMpesaReview]=useState<{record:BusinessRecord;mode:'reconcile'|'resolve'}|null>(null);const [mpesaReviewForm,setMpesaReviewForm]=useState({amount:'',reference:'',notes:'',outcome:'STATEMENT_ERROR'});
 const [receipt,setReceipt]=useState({code:'',account:'',amount:'',receivedAt:businessDateTimeInput(new Date(),timeZone)});
 const [settlement,setSettlement]=useState({amount:'',method:'CASH',reference:'',notes:'',confirmed:false});
 const [reconcile,setReconcile]=useState({balance:'',reference:'',notes:''});const [writeOff,setWriteOff]=useState({amount:'',reason:'',approvalToken:''});const [resolution,setResolution]=useState({outcome:'STATEMENT_ERROR',note:''});
 const balance=(id:string)=>entries.filter(entry=>data(entry)?.customerId===id).reduce((sum,entry)=>sum+Number(data(entry)?.balanceDeltaMinor||0),0);
 const account=customer&&accounts.find(record=>data(record)?.customerId===customer.id);const currentBalance=customer?balance(customer.id):0;const accountLimit=Number((account?.data.creditLimitMinor??account?.data.limitMinor)||0);
 const customerDiscrepancies=useMemo(()=>customer?discrepancies.filter(record=>data(record)?.customerId===customer.id):[],[customer,discrepancies]);
 const run=async(operation:string,collection:string,id:string,payload:Record<string,unknown>):Promise<CommandOutcome>=>{if(disabled||busy){const blocked:CommandOutcome={kind:'BLOCKED',message:'Wait for the current financial action to finish before submitting another.'};setOutcome(blocked);return blocked}setBusy(true);setOutcome(null);try{const result=await command(operation,collection,id,payload);setOutcome(result);return result}catch(error){const blocked:CommandOutcome={kind:'BLOCKED',message:`The financial action could not be confirmed. ${operatorError(error)} Review Activity before retrying.`};setOutcome(blocked);return blocked}finally{setBusy(false)}};
 const saveAccount=()=>{if(!customer)return;const id=account?.id||crypto.randomUUID();void run('credit.account.save','customerCreditAccounts',id,{id,customerId:customer.id,creditLimitMinor:minor(creditLimit||'0'),status:String(account?.data.status||'ACTIVE'),notes:String(account?.data.notes||'')})};
 const submitReceipt=async()=>{if(!receipt.code.trim()||!receipt.account.trim()||!receipt.amount)return;const id=crypto.randomUUID();if(isCommandConfirmed(await run('mpesa.receipt','mpesaReceipts',id,{id,code:receipt.code.trim().toUpperCase(),account:receipt.account.trim(),receivedAmountMinor:minor(receipt.amount),receivedAt:businessDateTimeToUtc(receipt.receivedAt,timeZone)})))setReceiptOpen(false)};
 const openMpesaReview=(record:BusinessRecord,mode:'reconcile'|'resolve')=>{setMpesaReview({record,mode});setMpesaReviewForm({amount:String(Number(data(record)?.receivedAmountMinor||0)/100),reference:'',notes:'',outcome:'STATEMENT_ERROR'})};
 const submitMpesaReview=async(event:React.FormEvent)=>{event.preventDefault();if(!mpesaReview)return;const {record,mode}=mpesaReview;let result:CommandOutcome;if(mode==='reconcile'){const statementMinor=minor(mpesaReviewForm.amount);result=await run(statementMinor===Number(data(record)?.receivedAmountMinor||0)?'mpesa.reconcile':'mpesa.discrepancy','mpesaReceipts',record.id,{receiptId:record.id,statementAmountMinor:statementMinor,statementReference:mpesaReviewForm.reference.trim(),...(statementMinor===Number(data(record)?.receivedAmountMinor||0)?{notes:mpesaReviewForm.notes.trim()}:{reason:mpesaReviewForm.notes.trim()})})}else result=await run('mpesa.discrepancy.resolve','mpesaDiscrepancies',record.id,{discrepancyId:record.id,outcome:mpesaReviewForm.outcome,resolution:mpesaReviewForm.notes.trim()});if(isCommandConfirmed(result))setMpesaReview(null)};
 const submitSettlement=async()=>{if(!customer)return;if(isCommandConfirmed(await run('credit.settle','customerCreditEntries',crypto.randomUUID(),{customerId:customer.id,amountMinor:minor(settlement.amount),paymentMethod:settlement.method,reference:settlement.reference.trim(),notes:settlement.notes.trim(),manuallyConfirmed:settlement.confirmed})))setSettleOpen(false)};
 const submitReconcile=async()=>{if(!customer)return;if(isCommandConfirmed(await run('credit.reconcile','customerCreditReconciliations',crypto.randomUUID(),{customerId:customer.id,statementBalanceMinor:minor(reconcile.balance),statementReference:reconcile.reference.trim(),notes:reconcile.notes.trim()})))setReconcileOpen(false)};
 const submitWriteOff=async()=>{if(!customer)return;if(isCommandConfirmed(await run('credit.write_off','customerCreditEntries',crypto.randomUUID(),{customerId:customer.id,amountMinor:minor(writeOff.amount),reason:writeOff.reason.trim(),approvalToken:writeOff.approvalToken.trim()||undefined})))setWriteOffOpen(false)};
 const resolve=async()=>{if(!resolveId)return;if(isCommandConfirmed(await run('credit.discrepancy.resolve','customerCreditDiscrepancies',resolveId,{discrepancyId:resolveId,outcome:resolution.outcome,resolution:resolution.note.trim()})))setResolveId('')};
 return <section className="space-y-6" data-guide-anchor="web.financial-controls">
  <header><h2 className="flex items-center gap-2 text-2xl font-bold"><WalletCards className="h-6 w-6 text-amber-300"/>Financial controls</h2><p className="mt-1 text-sm text-slate-400">Customer receivables and M-Pesa review stay append-only. External payments are manually confirmed; ServOS never initiates provider payouts.</p></header>
  {outcome&&<p role={['OUTCOME_UNKNOWN','REJECTED','CONFLICT','BLOCKED'].includes(outcome.kind)?'alert':'status'} className={`rounded-xl border p-3 text-sm ${outcome.kind==='CONFIRMED'?'border-emerald-800 bg-emerald-950/30 text-emerald-200':'border-amber-800 bg-amber-950/30 text-amber-100'}`}>{outcomeText(outcome)}</p>}
  <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_360px]">
   <section className="space-y-4 rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="flex items-center gap-2 font-bold"><CreditCard className="h-5 w-5 text-amber-300"/>Customer credit and accounts</h3><p className="mt-1 text-xs text-slate-500">A charge increases Accounts Receivable. It is not a cash payment.</p></div>{allowed(session,'credit.settle')&&<button className={button} onClick={()=>setSettleOpen(true)} disabled={!customer||currentBalance<=0}>Receive payment</button>}</div>
    <select className={field} aria-label="Select customer account" value={customer?.id||''} onChange={event=>setCustomerId(event.target.value)}><option value="">Select customer</option>{customers.map(record=><option key={record.id} value={record.id}>{label(record)}</option>)}</select>
    {customer?<><div className="grid gap-3 sm:grid-cols-3"><Metric label="Outstanding" value={money(currentBalance)} tone={currentBalance>0?'text-amber-300':'text-emerald-300'}/><Metric label="Credit limit" value={money(accountLimit)} /><Metric label="Available" value={money(Math.max(0,accountLimit-currentBalance))}/></div>{allowed(session,'credit.manage')&&<div className="flex flex-wrap items-end gap-2"><label className="min-w-44 flex-1 text-xs text-slate-400">Credit limit (KES)<input className={field} type="number" min="0" step="0.01" value={creditLimit||String(accountLimit/100)} onChange={event=>setCreditLimit(event.target.value)}/></label><button className={button} onClick={saveAccount}>Save credit policy</button></div>}<div className="flex flex-wrap gap-2">{allowed(session,'credit.reconcile')&&<button className={button} onClick={()=>{setReconcile({balance:(currentBalance/100).toFixed(2),reference:'',notes:''});setReconcileOpen(true)}}>Reconcile</button>}{allowed(session,'credit.write_off')&&<button className={button} onClick={()=>{setWriteOff({amount:(currentBalance/100).toFixed(2),reason:'',approvalToken:''});setWriteOffOpen(true)}} disabled={currentBalance<=0}>Write off</button>}</div><div className="space-y-2"><h4 className="font-semibold">Ledger</h4>{entries.filter(record=>data(record)?.customerId===customer.id).slice().reverse().map(record=><article key={record.id} className="flex flex-wrap justify-between gap-2 rounded-xl border border-slate-800 bg-slate-950 p-3 text-sm"><span><b>{String(data(record)?.kind)}</b><span className="ml-2 text-xs text-slate-500">{String(data(record)?.sourceType)} · {String(data(record)?.paymentMethod||'')}</span></span><span className={Number(data(record)?.balanceDeltaMinor||0)>0?'text-amber-300':'text-emerald-300'}>{Number(data(record)?.balanceDeltaMinor||0)>0?'+':'−'}{money(Math.abs(Number(data(record)?.balanceDeltaMinor||0)))}</span></article>)}{!entries.some(record=>data(record)?.customerId===customer.id)&&<Empty text="No credit ledger entries."/>}</div></>:<Empty text="Choose a customer to review their account."/>}
   </section>
   <section className="space-y-4 rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="flex items-center gap-2 font-bold"><Receipt className="h-5 w-5 text-amber-300"/>M-Pesa reconciliation</h3><p className="mt-1 text-xs text-slate-500">Record a statement entry only after manually confirming it.</p></div>{allowed(session,'mpesa.record')&&<button className={primary} onClick={()=>setReceiptOpen(true)}>Record receipt</button>}</div><div className="space-y-2">{receipts.map(record=><article key={record.id} className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="flex justify-between gap-2"><b>{String(data(record)?.code)}</b><span className="text-xs text-amber-300">{String(data(record)?.reconciliationStatus)}</span></div><p className="mt-1 text-sm">{money(data(record)?.receivedAmountMinor)} · {String(data(record)?.account)}</p><p className="text-xs text-slate-500">ServOS does not initiate or confirm provider payouts.</p>{allowed(session,'mpesa.reconcile')&&!String(data(record)?.reconciliationStatus).startsWith('RECONCILED')&&<button className={`${button} mt-2`} onClick={()=>openMpesaReview(record,'reconcile')}>Review statement</button>}</article>)}{!receipts.length&&<Empty text="No manually confirmed M-Pesa receipts."/>}</div></section>
  </div>
  <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><h3 className="flex items-center gap-2 font-bold"><AlertTriangle className="h-5 w-5 text-amber-300"/>Open control exceptions</h3><div className="mt-3 grid gap-3 lg:grid-cols-2">{mpesaDiscrepancies.filter(record=>data(record)?.status==='OPEN').map(record=><ExceptionCard key={record.id} title={`M-Pesa ${String(data(record)?.receiptCode||data(record)?.receiptId)}`} detail={`Variance ${money(data(record)?.varianceMinor)} · ${String(data(record)?.reason)}`} action={allowed(session,'mpesa.reconcile')?<button className={button} onClick={()=>openMpesaReview(record,'resolve')}>Resolve</button>:null}/>)}{customerDiscrepancies.filter(record=>data(record)?.status==='OPEN').map(record=><ExceptionCard key={record.id} title={`Credit account ${String(data(record)?.customerId)}`} detail={`Variance ${money(data(record)?.varianceMinor)}`} action={allowed(session,'credit.reconcile')?<button className={button} onClick={()=>setResolveId(record.id)}>Resolve</button>:null}/>)}{!mpesaDiscrepancies.some(record=>data(record)?.status==='OPEN')&&!customerDiscrepancies.some(record=>data(record)?.status==='OPEN')&&<Empty text="No open financial discrepancies."/>}</div></section>
  {receiptOpen&&<Modal title="Record manually confirmed M-Pesa receipt" onClose={()=>setReceiptOpen(false)}><div className="space-y-3"><p className="text-xs text-slate-400">This records evidence for reconciliation. It does not call M-Pesa, move funds, or create a provider payout.</p><input className={field} placeholder="M-Pesa transaction code" value={receipt.code} onChange={event=>setReceipt({...receipt,code:event.target.value})}/><input className={field} placeholder="Business M-Pesa account" value={receipt.account} onChange={event=>setReceipt({...receipt,account:event.target.value})}/><input className={field} type="number" min="0.01" step="0.01" placeholder="Received amount (KES)" value={receipt.amount} onChange={event=>setReceipt({...receipt,amount:event.target.value})}/><label className="block text-sm">Receipt time ({timeZone})<input className={field} type="datetime-local" data-business-timezone={timeZone} value={receipt.receivedAt} onChange={event=>setReceipt({...receipt,receivedAt:event.target.value})}/></label><button className={primary} disabled={disabled||!receipt.code||!receipt.account||!receipt.amount||!receipt.receivedAt} onClick={()=>void submitReceipt()}>Save receipt evidence</button></div></Modal>}
  {mpesaReview&&<Modal title={mpesaReview.mode==='reconcile'?'Review M-Pesa statement':'Resolve M-Pesa discrepancy'} onClose={()=>setMpesaReview(null)}><form className="space-y-3" onSubmit={event=>void submitMpesaReview(event)}>{mpesaReview.mode==='reconcile'?<><label className="block text-sm">Statement amount (KES)<input required type="number" min="0" step="0.01" className={field} value={mpesaReviewForm.amount} onChange={event=>setMpesaReviewForm({...mpesaReviewForm,amount:event.target.value})}/></label><label className="block text-sm">Statement reference<input required className={field} value={mpesaReviewForm.reference} onChange={event=>setMpesaReviewForm({...mpesaReviewForm,reference:event.target.value})}/></label></>:<label className="block text-sm">Outcome<select className={field} value={mpesaReviewForm.outcome} onChange={event=>setMpesaReviewForm({...mpesaReviewForm,outcome:event.target.value})}>{['STATEMENT_ERROR','MISSING_PAYMENT','MISSING_CHARGE','ACCEPTED_VARIANCE','WRITE_OFF_REQUIRED'].map(value=><option key={value}>{value}</option>)}</select></label>}<label className="block text-sm">{mpesaReview.mode==='reconcile'?'Review notes or discrepancy reason':'Resolution note'}<textarea required className={field} value={mpesaReviewForm.notes} onChange={event=>setMpesaReviewForm({...mpesaReviewForm,notes:event.target.value})}/></label><div className="flex justify-end gap-2"><button type="button" className={button} onClick={()=>setMpesaReview(null)}>Cancel</button><button disabled={disabled||!mpesaReviewForm.notes.trim()||mpesaReview.mode==='reconcile'&&!mpesaReviewForm.reference.trim()} className={primary}>Save review</button></div></form></Modal>}
  {settleOpen&&customer&&<Modal title={`Receive payment for ${label(customer)}`} onClose={()=>setSettleOpen(false)}><div className="space-y-3"><p className="text-sm text-slate-400">Outstanding balance: {money(currentBalance)}. This reduces the receivable; it does not erase the charge.</p><input className={field} type="number" min="0.01" max={currentBalance/100} step="0.01" placeholder="Amount (KES)" value={settlement.amount} onChange={event=>setSettlement({...settlement,amount:event.target.value})}/><select className={field} value={settlement.method} onChange={event=>setSettlement({...settlement,method:event.target.value})}><option>CASH</option><option>MPESA</option><option>CARD</option></select>{settlement.method!=='CASH'&&<><input className={field} placeholder="External payment reference" value={settlement.reference} onChange={event=>setSettlement({...settlement,reference:event.target.value})}/><label className="flex gap-2 text-xs"><input type="checkbox" checked={settlement.confirmed} onChange={event=>setSettlement({...settlement,confirmed:event.target.checked})}/><span>I manually verified this external payment.</span></label></>}<textarea className={field} placeholder="Notes" value={settlement.notes} onChange={event=>setSettlement({...settlement,notes:event.target.value})}/><button className={primary} disabled={disabled||!settlement.amount||settlement.method!=='CASH'&&(!settlement.reference||!settlement.confirmed)} onClick={()=>void submitSettlement()}>Confirm settlement</button></div></Modal>}
  {reconcileOpen&&customer&&<Modal title={`Reconcile ${label(customer)}`} onClose={()=>setReconcileOpen(false)}><div className="space-y-3"><p className="text-sm text-slate-400">Expected ledger balance: {money(currentBalance)}. A difference creates an exception and does not alter the ledger.</p><input className={field} type="number" min="0" step="0.01" placeholder="Statement balance (KES)" value={reconcile.balance} onChange={event=>setReconcile({...reconcile,balance:event.target.value})}/><input className={field} placeholder="Statement / review reference" value={reconcile.reference} onChange={event=>setReconcile({...reconcile,reference:event.target.value})}/><textarea className={field} placeholder="Review notes" value={reconcile.notes} onChange={event=>setReconcile({...reconcile,notes:event.target.value})}/><button className={primary} disabled={disabled||!reconcile.balance||!reconcile.reference||!reconcile.notes} onClick={()=>void submitReconcile()}>Record reconciliation</button></div></Modal>}
  {writeOffOpen&&customer&&<Modal title="Write off customer debt" onClose={()=>setWriteOffOpen(false)}><div className="space-y-3"><p className="text-sm text-rose-300">This posts a bad-debt adjustment. It never invents a payment. A manager approval token is required unless your session is an Admin.</p><input className={field} type="number" min="0.01" max={currentBalance/100} step="0.01" value={writeOff.amount} onChange={event=>setWriteOff({...writeOff,amount:event.target.value})}/><textarea className={field} placeholder="Reason" value={writeOff.reason} onChange={event=>setWriteOff({...writeOff,reason:event.target.value})}/>{!session.permissions.includes('*')&&<input className={field} placeholder="Manager approval token" value={writeOff.approvalToken} onChange={event=>setWriteOff({...writeOff,approvalToken:event.target.value})}/>}<button className={primary} disabled={disabled||!writeOff.amount||!writeOff.reason.trim()||!session.permissions.includes('*')&&!writeOff.approvalToken.trim()} onClick={()=>void submitWriteOff()}>Write off</button></div></Modal>}
  {resolveId&&<Modal title="Resolve credit discrepancy" onClose={()=>setResolveId('')}><div className="space-y-3"><select className={field} value={resolution.outcome} onChange={event=>setResolution({...resolution,outcome:event.target.value})}><option>STATEMENT_ERROR</option><option>MISSING_PAYMENT</option><option>MISSING_CHARGE</option><option>ACCEPTED_VARIANCE</option><option>WRITE_OFF_REQUIRED</option></select><textarea className={field} placeholder="Resolution note" value={resolution.note} onChange={event=>setResolution({...resolution,note:event.target.value})}/><button className={primary} disabled={disabled||!resolution.note.trim()} onClick={()=>void resolve()}>Save resolution</button></div></Modal>}
 </section>;
}

function Metric({label,value,tone='text-white'}:{label:string;value:string;tone?:string}){return <div className="rounded-xl border border-slate-800 bg-slate-950 p-3"><div className="text-xs text-slate-500">{label}</div><div className={`mt-1 font-bold ${tone}`}>{value}</div></div>}
function Empty({text}:{text:string}){return <p className="rounded-xl border border-dashed border-slate-700 p-5 text-center text-sm text-slate-500">{text}</p>}
function ExceptionCard({title,detail,action}:{title:string;detail:string;action:React.ReactNode}){return <article className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-amber-800/50 bg-amber-950/20 p-3"><div><b>{title}</b><p className="text-xs text-slate-400">{detail}</p></div>{action}</article>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <Dialog title={title} onClose={onClose}>{children}</Dialog>}
