import React,{useState} from 'react';
import {Wrench} from 'lucide-react';
import {allowed,type BusinessRecord,type WebSession} from './session';
import {BlockerCard,BusyButton,FormField} from '../../design-system/controls';

type CommandFn=(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<unknown>;
const active=(records:BusinessRecord[],collection:string)=>records.filter(record=>record.collection===collection&&!record.archived);
const value=(record:BusinessRecord|undefined,key:string)=>String(record?.data[key]||'');
const label=(record:BusinessRecord)=>String(record.data.name||record.data.tag||record.data.number||record.id);

export function WebMaintenanceView({records,session,disabled,command}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:CommandFn}){
 const orders=active(records,'maintenanceOrders').filter(order=>Boolean(value(order,'assetId'))).sort((a,b)=>String(b.data.reportedAt||'').localeCompare(String(a.data.reportedAt||'')));
 const assets=active(records,'assets');const employees=active(records,'employees').filter(employee=>value(employee,'status')==='ACTIVE');const suppliers=active(records,'suppliers');
 const [assetId,setAssetId]=useState('');const [description,setDescription]=useState('');const [priority,setPriority]=useState('MEDIUM');const [orderId,setOrderId]=useState('');const [assigneeId,setAssigneeId]=useState('');const [resolution,setResolution]=useState('');const [cost,setCost]=useState('');const [supplierId,setSupplierId]=useState('');const [invoiceReference,setInvoiceReference]=useState('');const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 const mayManage=allowed(session,'maintenance.manage');
 const run=async(operation:string,id:string,payload:Record<string,unknown>)=>{if(disabled||busy||!mayManage)return false;setBusy(true);setNotice('');try{await command(operation,'maintenanceOrders',id,payload);setNotice('Maintenance action queued. It takes effect only after the business server accepts it.');return true}catch{setNotice('The action could not be queued. Check connectivity and permissions, then refresh before retrying.');return false}finally{setBusy(false)}};
 const report=async(event:React.FormEvent)=>{event.preventDefault();if(!assetId||!description.trim())return;const id=crypto.randomUUID();if(await run('maintenance.report',id,{id,assetId,priority,description:description.trim()})){setDescription('');setAssetId('')}};
 const selected=orders.find(order=>order.id===orderId);const costAmount=cost.trim()?Number(cost):0;const validCost=Number.isFinite(costAmount)&&costAmount>=0;const serviceMinor=validCost?Math.round(costAmount*100):-1;
 const act=async(operation:string,payload:Record<string,unknown>)=>{if(!selected)return;if(await run(operation,selected.id,{id:selected.id,...payload})){setOrderId('');setResolution('');setCost('');setSupplierId('');setInvoiceReference('');setAssigneeId('');setReason('')}};
 return <section className="space-y-5" data-guide-anchor="web.maintenance">
  <header><h2 className="flex items-center gap-2 text-2xl font-bold"><Wrench className="h-6 w-6 text-amber-300"/>Asset maintenance</h2><p className="mt-1 text-sm text-slate-400">Report faults, assign work, track repairs, and record completion. Commands are server-authoritative.</p></header>
  {notice&&<p role="status" className="rounded-xl border border-slate-700 bg-slate-900 p-3 text-sm">{notice}</p>}
  {mayManage&&<form onSubmit={report} className="grid gap-3 rounded-2xl border border-slate-800 bg-slate-950 p-4 sm:grid-cols-2">
   <h3 className="font-bold sm:col-span-2">Report an asset issue</h3>
   <label className="text-sm">Asset<select required value={assetId} onChange={event=>setAssetId(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-600 bg-slate-950 p-2"><option value="">Choose asset</option>{assets.filter(asset=>value(asset,'status')==='ACTIVE').map(asset=><option key={asset.id} value={asset.id}>{label(asset)}</option>)}</select></label>
   <label className="text-sm">Priority<select value={priority} onChange={event=>setPriority(event.target.value)} className="mt-1 w-full rounded-lg border border-slate-600 bg-slate-950 p-2">{['LOW','MEDIUM','HIGH','CRITICAL'].map(item=><option key={item}>{item}</option>)}</select></label>
   <div className="sm:col-span-2"><FormField label="Describe the fault"><textarea value={description} onChange={event=>setDescription(event.target.value)} required maxLength={4000} rows={3} className="mt-1 w-full rounded-lg border border-slate-600 bg-slate-950 p-2 text-white"/></FormField></div>
   <BusyButton type="submit" busy={busy} disabled={disabled||!assetId||!description.trim()} className="rounded-xl bg-amber-400 px-4 py-2 font-bold text-slate-950 sm:col-span-2">Report issue</BusyButton>
  </form>}
  {!mayManage&&<BlockerCard title="Maintenance permission required">Ask an Admin for the maintenance.manage permission to report or update asset repairs.</BlockerCard>}
  <div className="grid gap-3 xl:grid-cols-2">{orders.map(order=>{const status=value(order,'status');const asset=assets.find(item=>item.id===value(order,'assetId'));return <article key={order.id} className="rounded-2xl border border-slate-800 bg-slate-950 p-4"><div className="flex flex-wrap justify-between gap-2"><div><h3 className="font-bold">{label(asset||order)} · {status.replace('_',' ')}</h3><p className="mt-1 text-sm text-slate-400">{value(order,'priority')} priority · {value(order,'description')}</p>{value(order,'assigneeId')&&<p className="mt-1 text-xs text-slate-500">Assigned to {label(employees.find(person=>person.id===value(order,'assigneeId'))||({id:value(order,'assigneeId'),collection:'employees',version:0,data:{}} as BusinessRecord))}</p>}</div></div>
   {mayManage&&status!=='COMPLETED'&&status!=='CANCELLED'&&<div className="mt-3 flex flex-wrap items-end gap-2">
    {['REPORTED','ASSIGNED'].includes(status)&&<><label className="text-xs">Assign to<select value={selected?.id===order.id?assigneeId:value(order,'assigneeId')} onChange={event=>{setOrderId(order.id);setAssigneeId(event.target.value)}} className="mt-1 block rounded-lg border border-slate-700 bg-slate-900 p-2"> <option value="">Choose staff</option>{employees.map(employee=><option key={employee.id} value={employee.id}>{label(employee)}</option>)}</select></label><button disabled={disabled||busy||!(selected?.id===order.id?assigneeId:value(order,'assigneeId'))} className="rounded-lg border border-slate-700 px-3 py-2 text-sm disabled:opacity-40" onClick={()=>{setOrderId(order.id);void run('maintenance.assign',order.id,{id:order.id,assigneeId:selected?.id===order.id?assigneeId:value(order,'assigneeId')})}}>Assign</button></>}
    {status==='ASSIGNED'&&<button disabled={disabled||busy} className="rounded-lg border border-slate-700 px-3 py-2 text-sm" onClick={()=>void run('maintenance.start',order.id,{id:order.id})}>Start work</button>}
    {status==='IN_PROGRESS'&&<><label className="text-xs">Resolution<input value={selected?.id===order.id?resolution:''} onChange={event=>{setOrderId(order.id);setResolution(event.target.value)}} className="mt-1 block rounded-lg border border-slate-700 bg-slate-900 p-2"/></label><label className="text-xs">External service cost (KES)<input type="number" min="0" step="0.01" value={selected?.id===order.id?cost:''} onChange={event=>{setOrderId(order.id);setCost(event.target.value)}} className="mt-1 block rounded-lg border border-slate-700 bg-slate-900 p-2"/></label>{serviceMinor>0&&<><label className="text-xs">Supplier<select value={supplierId} onChange={event=>setSupplierId(event.target.value)} className="mt-1 block rounded-lg border border-slate-700 bg-slate-900 p-2"><option value="">Choose supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{label(s)}</option>)}</select></label><label className="text-xs">Invoice reference<input value={invoiceReference} onChange={event=>setInvoiceReference(event.target.value)} className="mt-1 block rounded-lg border border-slate-700 bg-slate-900 p-2"/></label></>}<button disabled={disabled||busy||!validCost||!resolution.trim()||(serviceMinor>0&&(!supplierId||!invoiceReference.trim()))} className="rounded-lg bg-emerald-400 px-3 py-2 text-sm font-bold text-slate-950 disabled:opacity-40" onClick={()=>void act('maintenance.complete',{resolution:resolution.trim(),parts:[],serviceCostMinor:serviceMinor,...(serviceMinor?{supplierId,invoiceReference:invoiceReference.trim()}:{})})}>Complete repair</button></>}
    <label className="text-xs">Cancellation reason<input value={selected?.id===order.id?reason:''} onChange={event=>{setOrderId(order.id);setReason(event.target.value)}} className="mt-1 block rounded-lg border border-slate-700 bg-slate-900 p-2"/></label><button disabled={disabled||busy||!(selected?.id===order.id&&reason.trim())} className="rounded-lg border border-rose-900 px-3 py-2 text-sm text-rose-200 disabled:opacity-40" onClick={()=>void act('maintenance.cancel',{reason:reason.trim()})}>Cancel</button>
   </div>}
  </article>})}{orders.length===0&&<p className="rounded-xl border border-slate-800 p-4 text-sm text-slate-400">No asset maintenance orders have been reported.</p>}</div>
 </section>
}
