import React,{useEffect,useState} from 'react';
import {allowed,type BusinessRecord,type Rpc,type WebSession} from './session';
import {SearchCombobox} from '../../design-system/controls';
import {isCommandConfirmed,type CommandOutcome} from '../../types/transactions';
import {operatorError} from './operatorError';
type CommandFn=(operation:string,collection:string,id:string,payload:Record<string,unknown>)=>Promise<CommandOutcome>;
type Device={id:string;name:string;class:string;ownerId:string;active:boolean;lastSequence:number;lastSeenAt:string|null;protocolVersion:number;createdAt:string};
const input='w-full rounded-lg border border-slate-600 bg-slate-950 p-2 text-white';
const button='rounded-lg border border-slate-600 px-3 py-2 disabled:opacity-40';
const roles=['Admin','Manager','Cashier','Server','Chef','Housekeeper','Accountant','Custom'];
const roleGuidance:Record<string,string>={Admin:'Business setup, staff/device administration and broad operational access.',Manager:'Shift oversight and approvals; sensitive actions remain permission- and approval-gated.',Cashier:'Till, payment and sales tasks assigned to the cashier workflow.',Server:'Guest service and order entry without administration tools.',Chef:'Kitchen display and preparation workflows.',Housekeeper:'Room readiness and housekeeping tasks.',Accountant:'Finance, reconciliation and reporting tasks.',Custom:'Use only when the business has explicitly configured a custom permission profile.'};
const permissions=['procurement.over_receive','order.discount','order.comp','order.void','payment.reverse','till.override_variance','folio.reverse','credit.write_off','credit.override_limit','mpesa.reconcile'];
const outcomeText=(outcome:CommandOutcome)=>{switch(outcome.kind){case'CONFIRMED':return 'Staff or device action confirmed and synchronized.';case'DRAFT_SAVED':return 'Action saved as a draft; it has not taken effect.';case'PENDING':return 'Action is waiting to synchronize. Do not submit it again.';case'OUTCOME_UNKNOWN':case'REJECTED':case'CONFLICT':case'BLOCKED':return outcome.message}};

export function WebStaffAdminView({records,session,disabled,command,rpc,currentDeviceId}:{records:BusinessRecord[];session:WebSession;disabled:boolean;command:CommandFn;rpc:Rpc;currentDeviceId:string}){
 const [devices,setDevices]=useState<Device[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [outcome,setOutcome]=useState<CommandOutcome|null>(null);const [busy,setBusy]=useState(false);
 const [authUserId,setAuthUserId]=useState<string>('');const [staffId,setStaffId]=useState<string>(()=>crypto.randomUUID());const [name,setName]=useState<string>('');const [role,setRole]=useState<string>('Server');
 const [initiatorId,setInitiatorId]=useState('');const [approvalPermission,setApprovalPermission]=useState(permissions[0]);const [approvalTarget,setApprovalTarget]=useState('');
 const staff=records.filter(r=>r.collection==='employees');
 const loadDevices=async()=>{if(!allowed(session,'devices.manage'))return;try{const list=await rpc('rpc/servos_v2_list_devices',{}) as Device[];setDevices(list)}catch(e){setError(operatorError(e))}};
 useEffect(()=>{void loadDevices()},[session.actorId,session.policyVersion]);
 const run=async(op:string,id:string,payload:Record<string,unknown>,collection='employees'):Promise<CommandOutcome>=>{if(disabled||busy){const blocked:CommandOutcome={kind:'BLOCKED',message:'Wait for the current staff or device action before submitting another.'};setOutcome(blocked);return blocked}setBusy(true);setError('');setNotice('');setOutcome(null);try{const result=await command(op,collection,id,payload);setOutcome(result);if(isCommandConfirmed(result))await loadDevices();return result}catch(error){const blocked:CommandOutcome={kind:'BLOCKED',message:`The action could not be confirmed. ${operatorError(error)} Review Activity before retrying.`};setOutcome(blocked);return blocked}finally{setBusy(false)}};
 const create=async()=>{const authId=authUserId.trim();const stableStaffId=staffId.trim();const staffName=name.trim();if(!authId||!stableStaffId||!staffName){setError('Enter the invited Auth user ID, stable staff ID, and staff name.');return}if(!/^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(authId)){setError('Auth user ID must be the UUID from the completed Supabase Auth invitation.');return}if(isCommandConfirmed(await run('staff.create',stableStaffId,{authUserId:authId,staffId:stableStaffId,name:staffName,role}))){setAuthUserId('');setStaffId(crypto.randomUUID());setName('')}};
 const approve=async()=>{if(!initiatorId.trim()||!approvalTarget.trim())return;const token=crypto.randomUUID();if(isCommandConfirmed(await run('managerApproval.issue',token,{initiatorId:initiatorId.trim(),permission:approvalPermission,target:approvalTarget.trim(),approvalToken:token}))){setNotice(`Approval token (expires in 5 minutes): ${token}. Share it directly with the named operator; it is single-use and action/target bound.`);await navigator.clipboard?.writeText(token).catch(()=>undefined)}};
 const revoke=async(device:Device)=>{if(device.id===currentDeviceId){setError('This browser cannot revoke its own active device. Use a different trusted device.');return}const result=await run('device.revoke',device.id,{deviceId:device.id},'deviceEvents');if(isCommandConfirmed(result))setNotice('Device revoked; its later commands are rejected by the server.')};
 return <section className="space-y-6" aria-label="Staff and device administration">
  <header><h2 className="text-xl font-bold">Staff, approvals and devices</h2><p className="mt-1 text-sm text-slate-400">Server permissions are authoritative. Invitations and passwords are managed through Supabase Auth; this workspace only binds an existing Auth user to a staff profile.</p></header>
  {outcome&&<p role={['OUTCOME_UNKNOWN','REJECTED','CONFLICT','BLOCKED'].includes(outcome.kind)?'alert':'status'} className={`rounded-lg border p-3 text-sm ${outcome.kind==='CONFIRMED'?'border-emerald-800 bg-emerald-950':'border-amber-800 bg-amber-950'}`}>{outcomeText(outcome)}</p>}{error&&<p role="alert" className="rounded-lg border border-rose-800 bg-rose-950 p-3 text-sm">{error}</p>}{notice&&<p role="status" className="break-all rounded-lg border border-emerald-800 p-3 text-sm">{notice}</p>}
  {allowed(session,'staff.create')&&<form className="grid gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void create()}}><h3 className="font-semibold sm:col-span-2">Bind invited Auth user</h3><label className="text-sm">Existing Auth user ID<input required className={input} value={authUserId} onChange={e=>setAuthUserId(e.target.value)}/></label><div className="text-sm"><label htmlFor="generated-staff-id">Stable staff ID (match the terminal record)</label><input id="generated-staff-id" required className={`${input} font-mono text-xs`} value={staffId} onChange={e=>setStaffId(e.target.value)}/><button type="button" className={`${button} mt-2`} onClick={()=>setStaffId(crypto.randomUUID())}>Generate ID for new staff</button><p className="mt-1 text-xs text-slate-500">For an existing terminal operator, enter their exact Staff ID. Generate a new UUID only when creating a genuinely new staff record. This ID is not a password or device credential.</p></div><label className="text-sm">Name<input required className={input} value={name} onChange={e=>setName(e.target.value)}/></label><div className="text-sm"><label>Role template<SearchCombobox options={roles.map(value=>({id:value,label:value}))} value={role} onValueChange={setRole}/></label><p className="mt-1 text-xs text-slate-400">{roleGuidance[role]}</p></div><button disabled={disabled} className={`${button} sm:col-span-2`}>Create staff profile</button></form>}
  <div className="space-y-2"><h3 className="font-semibold">Staff profiles</h3>{staff.map(person=><article key={person.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-800 p-3"><div><b>{String(person.data.name||person.id)}</b><p className="text-xs text-slate-400">{String(person.data.role)} · {person.archived?'Inactive':'Active'} · {String(person.data.authUserId||'Auth user not linked')}</p><p className="text-xs text-slate-500">Outlets: {Array.isArray(person.data.outletIds)?person.data.outletIds.join(', '):'all'} · Areas: {Array.isArray(person.data.serviceAreas)?person.data.serviceAreas.join(', '):'all'}</p></div><div className="flex flex-wrap gap-2">{allowed(session,'staff.update')&&!person.archived&&<SearchCombobox aria-label={`Change ${String(person.data.name)} role`} className="min-w-36" options={roles.map(value=>({id:value,label:value}))} value={String(person.data.role)} disabled={disabled} onValueChange={role=>void run('staff.update',person.id,{authUserId:person.data.authUserId,staffId:person.id,name:person.data.name,role})}/>} {allowed(session,'staff.deactivate')&&!person.archived&&<button disabled={disabled||String(person.data.authUserId)===session.actorId} className={button} onClick={()=>void run('staff.deactivate',person.id,{authUserId:person.data.authUserId,staffId:person.id})}>Deactivate</button>}</div></article>)}{!staff.length&&<p className="text-sm text-slate-500">No staff profiles are visible to this role.</p>}</div>
  {allowed(session,'staff.update')&&<form className="grid gap-3 rounded-xl border border-slate-800 bg-slate-900 p-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void approve()}}><h3 className="font-semibold sm:col-span-2">Issue manager approval</h3><label className="text-sm">Initiating operator Auth user ID<input required className={input} value={initiatorId} onChange={e=>setInitiatorId(e.target.value)}/></label><label className="text-sm">Action<select className={input} value={approvalPermission} onChange={e=>setApprovalPermission(e.target.value)}>{permissions.map(p=><option key={p}>{p}</option>)}</select></label><label className="text-sm sm:col-span-2">Exact target ID (for over-receipt, purchase order ID)<input required className={input} value={approvalTarget} onChange={e=>setApprovalTarget(e.target.value)}/></label><button disabled={disabled} className={`${button} sm:col-span-2`}>Issue five-minute one-time approval</button></form>}
  {allowed(session,'devices.manage')&&<div className="space-y-2"><div className="flex items-center justify-between"><h3 className="font-semibold">Trusted devices</h3><button className={button} onClick={()=>void loadDevices()}>Refresh</button></div>{devices.map(device=><article key={device.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-800 p-3"><div className="min-w-0"><b>{device.name}</b><p className="break-all font-mono text-xs text-slate-400">{device.id} · {device.class} · protocol {device.protocolVersion}</p><p className="text-xs text-slate-500">Owner {device.ownerId} · sequence {device.lastSequence} · last seen {device.lastSeenAt?new Date(device.lastSeenAt).toLocaleString():'not yet'}</p></div><div className="flex items-center gap-2"><span>{device.active?'Active':'Revoked'}</span>{device.active&&<button disabled={disabled||device.id===currentDeviceId} className={button} onClick={()=>void revoke(device)}>Revoke</button>}</div></article>)}</div>}
  {staff.some(p=>p.data.role==='Admin'&&p.data.active!==false)&&!staff.some(p=>p.data.role==='Admin'&&!p.archived)&&<p className="text-sm text-amber-300">An Admin profile is marked inactive; verify that another active Admin remains before continuing.</p>}
 </section>;
}
