//! Till-session settlement report, not a calendar-day accrual report.
use crate::{actions::{BridgeAction,PrinterRole,ValidatedAction},rendering::PreparedDocument};
use chrono::{DateTime,FixedOffset};
use serde_json::Value;
use uuid::Uuid;
fn text(value:&Value,key:&str,required:bool)->Result<String,String>{match value.get(key){None|Some(Value::Null) if !required=>Ok(String::new()),Some(Value::String(raw)) if raw.len()<=2000&&!raw.chars().any(|c|c.is_control())&&(!required||!raw.trim().is_empty())=>Ok(raw.clone()),_=>Err(format!("Invalid report {key}"))}}
fn amount(value:&Value,key:&str)->Result<i64,String>{value.get(key).and_then(Value::as_i64).filter(|n|n.unsigned_abs()<=9007199254740991).ok_or_else(||format!("Missing or invalid report amount {key}"))}
fn money(value:i64)->String{let absolute=value.unsigned_abs();format!("{}{}.{:02}",if value<0{"-"}else{""},absolute/100,absolute%100)}
fn timestamp(value:&Value,key:&str)->Result<String,String>{let raw=text(value,key,true)?;let time=DateTime::parse_from_rfc3339(&raw).map_err(|_|"Invalid report timestamp")?;Ok(time.with_timezone(&FixedOffset::east_opt(10800).ok_or("Invalid report time zone")?).format("%Y-%m-%d %H:%M:%S EAT").to_string())}
fn identity(value:&Value,key:&str)->Result<String,String>{let raw=text(value,key,true)?;if Uuid::parse_str(&raw).map(|id|id.to_string()!=raw).unwrap_or(true){return Err("Invalid report identity".into());}Ok(raw)}
fn amounts(lines:&mut Vec<String>,value:&Value,fields:&[(&str,&str)])->Result<(),String>{for (key,label) in fields{lines.push(format!("{label}: {}",money(amount(value,key)?)));}Ok(())}
pub fn prepare_close_day(input:&ValidatedAction)->Result<PreparedDocument,String>{
 let document=match input.action(){BridgeAction::Submit{document,printer_role:PrinterRole::Office,..} if document.document_type=="CLOSE_DAY_REPORT"=>document,_=>return Err("Close-day report requires office role".into())};
 let snapshot:Value=serde_json::from_str(&document.canonical_snapshot).map_err(|_|"Invalid issued report snapshot")?;
 if snapshot["schemaVersion"]!=1||text(&snapshot,"salesBasis",true)?!="SETTLEMENT_RECEIPTS_IN_TILL_SESSION"||text(&snapshot,"paymentBasis",true)?!="PAYMENT_POSTINGS_IN_TILL_SESSION"||text(&snapshot,"currency",true)?!="KES"{return Err("Unsupported report basis or currency".into());}
 let business=&snapshot["business"];let mut lines=Vec::new();
 for key in ["businessName","address","contact","taxPin"]{if key=="address"{lines.extend(crate::document_text::multiline(business,key,2000)?);continue;}let raw=text(business,key,false)?;if !raw.is_empty(){lines.push(raw);}}
 lines.push("CLOSE-DAY REPORT (KES)".into());lines.push(document.document_number.clone());
 lines.push(format!("Generated: {}",timestamp(&snapshot,"generatedAt")?));lines.push(format!("Till: {}",identity(&snapshot,"tillSessionId")?));
 lines.push(format!("Opened: {}",timestamp(&snapshot,"openedAt")?));lines.push(format!("Closed: {}",timestamp(&snapshot,"closedAt")?));lines.push(format!("Generated by: {}",identity(&snapshot,"generatedBy")?));
 lines.push("Sales: receipts settled in this till.".into());lines.push("Collections: payment postings, including partial payments.".into());lines.push("Totals can differ. Not a calendar-day accrual report.".into());
 let settled=&snapshot["settledSales"];lines.push("SETTLED SALES".into());let count=amount(settled,"receiptCount")?;if count<0{return Err("Invalid settled receipt count".into());}lines.push(format!("Receipts: {count}"));
 amounts(&mut lines,settled,&[("grossMinor","Gross"),("netMinor","Net"),("vatMinor","VAT"),("levyMinor","Levy")])?;
 let gross=amount(settled,"grossMinor")?;if i128::from(amount(settled,"netMinor")?)+i128::from(amount(settled,"vatMinor")?)+i128::from(amount(settled,"levyMinor")?)!=i128::from(gross){return Err("Issued settled taxes do not reconcile".into());}
 lines.push("COLLECTIONS".into());amounts(&mut lines,&snapshot["sales"],&[("receivedMinor","Received"),("returnedMinor","Returned"),("netReceivedMinor","Net received")])?;
 let tenders=snapshot.get("paymentsByTender").and_then(Value::as_array).ok_or("Missing issued report tenders")?;if tenders.len()>500{return Err("Report tenders exceed bounds".into());}
 for tender in tenders{lines.push(format!("{} - {}",text(tender,"method",true)?,text(tender,"name",true)?));amounts(&mut lines,tender,&[("receivedMinor","Received"),("returnedMinor","Returned"),("netMinor","Net")])?;}
 lines.push("REVENUE AND TAX ALLOCATIONS".into());for kind in ["collected","reversed","net"]{lines.push(kind.to_uppercase());amounts(&mut lines,&snapshot["taxes"][kind],&[("netMinor","Net"),("vatMinor","VAT"),("levyMinor","Levy")])?;}
 lines.push("DRAWER CLOSE".into());let cash=&snapshot["cash"];
 amounts(&mut lines,cash,&[("openingFloatMinor","Opening float"),("paidInMinor","Paid in"),("paidOutMinor","Paid out"),("salesMinor","Cash sales"),("refundsMinor","Cash refunds"),("expectedMinor","Expected"),("countedMinor","Counted"),("varianceMinor","Variance")])?;
 if i128::from(amount(cash,"countedMinor")?)-i128::from(amount(cash,"expectedMinor")?)!=i128::from(amount(cash,"varianceMinor")?){return Err("Issued drawer variance does not reconcile".into());}
 for (key,label) in [("varianceReason","Variance reason"),("reviewReason","Manager review")]{let raw=text(cash,key,false)?;if !raw.is_empty(){lines.push(format!("{label}: {raw}"));}}
 let diagnostics=&snapshot["operationalDiagnostics"];lines.push("BUSINESS DIAGNOSTICS AT GENERATION".into());lines.push(format!("Observed: {}",timestamp(diagnostics,"observedAt")?));
 for (key,label) in [("openOrderCount","Open orders"),("unassignedZeroReceiptCount","Zero-value receipts without till attribution"),("unresolvedMoneyCommandCount","Unresolved money commands")]{let value=amount(diagnostics,key)?;if value<0{return Err("Invalid report diagnostic count".into());}lines.push(format!("{label}: {value}"));}
 amounts(&mut lines,diagnostics,&[("openOrderOutstandingMinor","Outstanding")])?;
 lines.push("Credit and room/folio exposure unavailable until API migration.".into());
 let footer_start=lines.len();lines.extend(crate::document_text::multiline(business,"footer",2000)?);
 let logo=match business.get("logoPngDataUrl"){None|Some(Value::Null)=>None,Some(Value::String(raw)) if raw.is_empty()=>None,Some(Value::String(raw))=>Some(raw.clone()),_=>return Err("Invalid report logo snapshot".into())};
 Ok(PreparedDocument{lines,logo,qr:None,footer_start:Some(footer_start)})
}
