//! Physical supplier return note; never implies supplier acceptance or a credit note.
use crate::{actions::{BridgeAction,PrinterRole,ValidatedAction},rendering::PreparedDocument,purchase_order_rendering::{text,identity,amount,money,time}};
use serde_json::Value;
fn quantity(value:&Value,key:&str)->Result<(i128,String),String>{let n=value.get(key).and_then(Value::as_f64).filter(|n|n.is_finite()&&*n>0.0&&*n<=1e9).ok_or("Invalid supplier return quantity")?;let scaled=n*1e6;if (scaled-scaled.round()).abs()>0.0001{return Err("Unsupported supplier return precision".into());}let raw=format!("{n:.6}");Ok((scaled.round() as i128,raw.trim_end_matches('0').trim_end_matches('.').to_string()))}
pub fn prepare_supplier_return(input:&ValidatedAction)->Result<PreparedDocument,String>{
 let doc=match input.action(){BridgeAction::Submit{document,printer_role:PrinterRole::Office,..} if document.document_type=="SUPPLIER_RETURN_NOTE"=>document,_=>return Err("Supplier return note requires office printer role".into())};
 let s:Value=serde_json::from_str(&doc.canonical_snapshot).map_err(|_|"Invalid supplier return snapshot")?;let return_id=identity(&s,"supplierReturnId")?;
 if s["schemaVersion"]!=1||doc.document_number!=format!("SR-{return_id}")||text(&s,"returnNumber",true)?!=doc.document_number{return Err("Invalid supplier return document identity/schema".into());}
 let business=&s["business"];let supplier=&s["supplier"];identity(supplier,"id")?;if identity(&s,"supplierId")?!=text(supplier,"id",true)?{return Err("Supplier return supplier identity mismatch".into());}
 let mut lines=vec![text(business,"businessName",true)?];lines.extend(crate::document_text::multiline(business,"address",2000)?);for key in ["contact","taxPin"]{let raw=text(business,key,false)?;if !raw.is_empty(){lines.push(raw);}}
 lines.push("SUPPLIER RETURN NOTE".into());lines.push(doc.document_number.clone());lines.push(format!("Dispatched: {}",time(&s,"dispatchedAt")?));identity(&s,"goodsReceiptId")?;lines.push(format!("Supplier: {}",text(supplier,"name",true)?));lines.push(format!("Original GRN: {}",identity(&s,"goodsReceiptId")?));lines.push(format!("Dispatch reference: {}",text(&s,"dispatchReference",true)?));lines.push(format!("Supplier/driver acknowledgement: {}",text(&s,"supplierAcknowledgmentName",true)?));
 let items=s.get("items").and_then(Value::as_array).filter(|rows|!rows.is_empty()&&rows.len()<=100).ok_or("Invalid supplier return lines")?;let mut ids=std::collections::HashSet::new();let mut total=0i128;
 for (index,item) in items.iter().enumerate(){if !ids.insert(identity(item,"id")?){return Err("Duplicate supplier return line".into());}identity(item,"goodsReceiptLineId")?;let stock=&item["stockSnapshot"];if identity(stock,"id")?!=identity(item,"stockItemId")?{return Err("Supplier return stock identity mismatch".into());}
  let (qty,qty_text)=quantity(item,"quantity")?;let (base,base_text)=quantity(item,"baseQuantity")?;let pack=item.get("purchasePackageSnapshot").filter(|v|!v.is_null());let unit=if let Some(pack)=pack{identity(pack,"id")?;let (per,_)=quantity(pack,"baseQuantity")?;if qty*per/1000000!=base||qty*per%1000000!=0{return Err("Supplier return package conversion does not reconcile".into());}text(pack,"name",true)?}else{if qty!=base{return Err("Supplier return base quantity mismatch".into());}text(stock,"baseUnit",true)?};
  let condition=text(item,"condition",true)?;if !["SEALED","OPENED","DAMAGED","OTHER"].contains(&condition.as_str()){return Err("Invalid supplier return condition".into());}let unit_cost=amount(item,"unitCostMinor")?;let value=amount(item,"estimatedCreditMinor")?;if (base*i128::from(unit_cost)+500000)/1000000!=i128::from(value){return Err("Supplier return estimated line value does not reconcile".into());}total+=i128::from(value);
  lines.push("--------------------------------".into());lines.push(format!("{}. {}",index+1,text(stock,"name",true)?));lines.push(format!("Returned: {qty_text} {unit} (base {base_text} {})",text(stock,"baseUnit",true)?));lines.push(format!("Condition: {condition}"));lines.push(format!("Estimated credit: {}",money(value)));lines.extend(crate::document_text::multiline(item,"reason",500)?);
 }
 let estimate=amount(&s,"estimatedCreditMinor")?;if total!=i128::from(estimate){return Err("Supplier return estimated total does not reconcile".into());}lines.push(format!("ESTIMATED CREDIT (KES): {}",money(estimate)));lines.push(format!("Reason: {}",text(&s,"reason",true)?));lines.push(format!("Dispatched by: {}",identity(&s,"dispatchedBy")?));identity(&s,"deviceId")?;if let Some(reference)=s.get("expectedCreditNote").and_then(Value::as_str).filter(|value|!value.trim().is_empty()){lines.push(format!("Expected credit note: {reference}"));}
 lines.push("Physical return evidence only. Supplier acceptance and credit-note issuance are not confirmed.".into());let footer_start=lines.len();lines.extend(crate::document_text::multiline(business,"footer",2000)?);let logo=match business.get("logoPngDataUrl"){None|Some(Value::Null)=>None,Some(Value::String(raw)) if raw.is_empty()=>None,Some(Value::String(raw))=>Some(raw.clone()),_=>return Err("Invalid supplier return logo".into())};Ok(PreparedDocument{lines,logo,qr:None,footer_start:Some(footer_start)})
}
