import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

test('inventory expansion is staged and never self-activates v2',()=>{
  const sql=readFileSync('supabase/expansion/011_inventory_catalog.sql','utf8');
  assert.match(sql,/STAGED V2 ONLY/);
  assert.doesNotMatch(sql,/update\s+servos_v2\.control\s+set\s+enabled\s*=\s*true/i);
  assert.match(sql,/inventory\.count/);
  assert.match(sql,/inventory\.transfer/);
  assert.match(sql,/inventory\.waste/);
  assert.match(sql,/product\.save/);
  assert.match(sql,/stockItem\.save/);
  assert.match(sql,/stockLocation\.save/);
  assert.match(sql,/DUPLICATE_REFERENCE/);
  assert.match(sql,/VERSION_CONFLICT|assert_version/);
});

test('web v2 catalog and inventory use command queue rather than direct Supabase table writes',()=>{
  const ui=readFileSync('src/runtime/web/WebCatalogInventory.tsx','utf8');
  const smart=readFileSync('src/runtime/web/SmartItemDialog.tsx','utf8');
  const deps=readFileSync('src/runtime/web/dependencies.ts','utf8');
  const manifest=readFileSync('src/runtime/operationManifest.ts','utf8');
  const smartSql=readFileSync('supabase/expansion/031_smart_item_atomic_setup.sql','utf8');
  const recipeSql=readFileSync('supabase/expansion/032_recipe_product_dependencies.sql','utf8');
  const sealedTransferSql=readFileSync('supabase/expansion/033_inventory_sealed_transfers.sql','utf8');
  const sealedCountSql=readFileSync('supabase/expansion/034_sealed_location_counts.sql','utf8');
  const harness=readFileSync('scripts/test-supabase.mjs','utf8');
  const cloudAcceptance=readFileSync('tests/supabase/smart-items.sql','utf8');
  const inventoryAcceptance=readFileSync('tests/supabase/inventory.sql','utf8');
  assert.match(ui,/const counts:Record<string,number\|null>=\{\}/);
  assert.match(ui,/typeof quantity==='number'&&Number\.isFinite\(quantity\)&&quantity>=0/);
  assert.match(ui,/product\.save/);
  assert.match(ui,/SmartItemDialog/);
  assert.match(smart,/catalog\.createWithOpeningStock/);
  assert.match(smart,/purchasePackages/);
  assert.match(smart,/openingPackages/);
  assert.match(smart,/product\.save/);
  assert.match(smart,/recipeIngredients/);
  assert.match(smart,/sealedContainerSize/);
  assert.match(smart,/whole-container/);
  assert.match(smart,/Save recipe item/);
  assert.match(smart,/pendingReview/);
  assert.match(smart,/avoid a duplicate item/);
  assert.match(deps,/catalog\.createWithOpeningStock/);
  assert.match(deps,/operation === 'product\.save'/);
  assert.match(deps,/productData\.recipeIngredients/);
  assert.match(deps,/stockMovements/);
  assert.match(smartSql,/apply_smart_item_setup/);
  assert.match(smartSql,/OPENING_BALANCE/);
  assert.match(recipeSql,/assert_version\(command,'stockItems'/);
  assert.match(recipeSql,/dispatch_before_recipe_product_dependencies/);
  assert.match(recipeSql,/require_permission\('inventory\.view'\)/);
  assert.match(recipeSql,/revoke all on function [^;]*servos_v2\.dispatch/);
  assert.match(sealedTransferSql,/apply_sealed_inventory_transfer/);
  assert.match(sealedTransferSql,/sealedOpenEffect/);
  assert.match(sealedTransferSql,/destination already has open liquid/);
  assert.match(sealedCountSql,/countedSealedContainers/);
  assert.match(sealedCountSql,/countedOpenQuantity/);
  assert.match(sealedCountSql,/sealedOpenEffect/);
  assert.match(harness,/smart-items\.sql/);
  assert.match(cloudAcceptance,/Smart Item command replay changed its acknowledgement/);
  assert.match(cloudAcceptance,/left partial stock or movement rows/);
  assert.match(cloudAcceptance,/Smart Item permission was not enforced/);
  assert.match(cloudAcceptance,/Recipe product lost its validated ingredients/);
  assert.match(cloudAcceptance,/result->>'status'<>'CONFLICT'.*VERSION_CONFLICT/);
  assert.match(cloudAcceptance,/Stale recipe stock baseline did not conflict as expected/);
  assert.match(cloudAcceptance,/Recipe without inventory\.view was not denied/);
  assert.match(cloudAcceptance,/Opening stock did not initialize sealed bottles/);
  assert.match(inventoryAcceptance,/Sealed transfer destination bottle state mismatch/);
  assert.match(inventoryAcceptance,/Whole-location count did not reconcile sealed\/open bottle state/);
  assert.match(manifest,/catalog\.createWithOpeningStock[^\n]*backend: 'implemented'[^\n]*web: 'partial'/);
  assert.match(ui,/stockItem\.save/);
  assert.match(ui,/inventory\.count/);
  assert.match(ui,/inventory\.transfer/);
  assert.match(ui,/inventory\.waste/);
  assert.match(ui,/bottleCounts/);
  assert.match(ui,/countedSealedContainers/);
  assert.match(ui,/countedOpenQuantity/);
  assert.match(ui,/useBarcodeScanner/);
  assert.doesNotMatch(ui,/business_records/);
  assert.doesNotMatch(ui,/from\(['"]business_records/);
});

test('transactional web workspace exposes catalog and inventory tabs',()=>{
  const app=readFileSync('src/runtime/web/WebBusinessApp.tsx','utf8');
  assert.match(app,/WebCatalogView/);
  assert.match(app,/WebInventoryView/);
  assert.match(app,/'Catalog'/);
  assert.match(app,/'Inventory'/);
});

test('disposable Supabase harness runs inventory acceptance after expansion SQL',()=>{
  const harness=readFileSync('scripts/test-supabase.mjs','utf8');
  assert.match(harness,/tests\/supabase\/inventory\.sql/);
  const acceptance=readFileSync('tests/supabase/inventory.sql','utf8');
  assert.match(acceptance,/stale baseline must conflict/i);
  assert.match(acceptance,/Immutable history/i);
  assert.match(acceptance,/quantity":99/);
  assert.match(acceptance,/REJECTED','VALIDATION_FAILED/);
  const domain=readFileSync('supabase/expansion/011_inventory_catalog.sql','utf8');
  assert.match(domain,/insufficient stock/i);
});

test('inventory, Smart Item, and procurement retain workflows until commands are confirmed',()=>{
  const app=readFileSync('src/runtime/web/WebBusinessApp.tsx','utf8');
  const inventory=readFileSync('src/runtime/web/WebCatalogInventory.tsx','utf8');
  const smartItem=readFileSync('src/runtime/web/SmartItemDialog.tsx','utf8');
  const procurement=readFileSync('src/runtime/web/WebProcurementView.tsx','utf8');
  assert.match(app,/WebCatalogView[\s\S]*command=\{submit\}/);
  assert.match(app,/WebInventoryView[\s\S]*command=\{submit\}/);
  assert.match(inventory,/Promise<CommandOutcome>/);
  assert.match(inventory,/if\(!outcome\|\|!isCommandConfirmed\(outcome\)\)/);
  assert.match(inventory,/if\(!isCommandConfirmed\(outcome\)\)return/);
  assert.match(inventory,/if\(isCommandConfirmed\(outcome\)\)setBatchOpen\(false\);return outcome/);
  assert.match(inventory,/commandNotice&&!kind&&!smartItemOpen/);
  assert.match(inventory,/commandNotice&&<p role="status"/);
  assert.match(inventory,/if\(!isCommandConfirmed\(outcome\)\)return;[\s\S]*if\(modal==='COUNT'\)\{localStorage\.removeItem\(sessionKey\)/);
  assert.match(inventory,/modal&&<Modal[\s\S]*commandNotice&&<p role="status"/);
  assert.match(smartItem,/Promise<CommandOutcome>/);
  assert.match(smartItem,/if\s*\(!isCommandConfirmed\(result\)\)/);
  assert.match(procurement,/Promise<CommandOutcome>/);
  for(const marker of ['setPoOpen(false);setPoLines([])','setReceiving(null)','setMatching(null)','setPaying(null)','setCommissioning(null)'])assert.ok(procurement.includes(marker),marker);
  for(const marker of ['if(isCommandConfirmed(outcome)){setPoOpen(false);setPoLines([])}','if(isCommandConfirmed(outcome)){setCommandNotice(outcomeMessage(outcome,\'Goods receipt\'));setReceiving(null)}','if(isCommandConfirmed(outcome))setMatching(null)','if(isCommandConfirmed(outcome))setPaying(null)','if(isCommandConfirmed(outcome))setCommissioning(null)'])assert.ok(procurement.includes(marker),marker);
  assert.match(procurement,/commandNotice&&supplierEdit===undefined/);
  assert.match(procurement,/supplierEdit!==undefined&&<Modal[\s\S]*commandNotice&&<p role="status"/);
  assert.match(procurement,/matching&&<Modal[\s\S]*commandNotice&&<p role="status"/);
});
