import React, { useEffect, useRef, useState } from 'react';
import { useRuntime, type InventoryCountDraft } from '../runtime/RuntimeProvider';
import { guardLocalWork, flushLocalWork } from '../runtime/localWork';
import { useBarcodeScanner, barcodeEquals } from '../hooks/useBarcodeScanner';
import { bottleSize, countRow, emptyCountEntry, frozenDependencies, classifyBottleStock, scannedEntry, physicalStock, type CountEntry } from '../utils/bottleInventory';
import { ActionDialog } from './ActionDialog';
import { buttonClass, fieldClass, primaryButtonClass } from './records';

export function BottleInputs({ stock, value, onChange, sealedOnly = false }: { stock: any; value: CountEntry; onChange: (value: CountEntry) => void; sealedOnly?: boolean }) {
  const size = bottleSize(stock);
  if (!size) return <label className="block text-sm">Counted ({stock.baseUnit})<input aria-label={`Counted quantity for ${stock.name}`} className={fieldClass} type="number" min="0" step="0.000001" value={value.quantity} onChange={event => onChange({ ...value, quantity: event.target.value })}/></label>;
  return <div className="space-y-2"><label className="block text-sm">Sealed bottles counted<input aria-label={`Sealed bottles for ${stock.name}`} className={fieldClass} type="number" min="0" step="1" value={value.sealed} onChange={event => onChange({ ...value, sealed: event.target.value, ...(sealedOnly ? { open: '0' } : {}) })}/></label>{!sealedOnly && <><label className="block text-sm">Open liquid remaining (ml)<input aria-label={`Open ml for ${stock.name}`} className={fieldClass} type="number" min="0" max={size} step="0.000001" value={value.open} onChange={event => onChange({ ...value, open: event.target.value, measurement: 'EXACT' })}/></label><div className="flex flex-wrap gap-1">{[0.25, 0.5, 0.75].map(fraction => <button key={fraction} type="button" className={buttonClass} onClick={() => onChange({ ...value, open: String(Number((size * fraction).toFixed(6))), measurement: 'ESTIMATED' })}>{fraction * 100}% = {Number((size * fraction).toFixed(6))} ml</button>)}</div><p className="text-xs text-slate-400">One open bottle only. {value.measurement === 'ESTIMATED' ? 'Estimated measurement.' : 'Enter exact ml, or choose an estimate.'}</p></>}</div>;
}

export function BottleCountDialog({ stocks, products, locations, initialLocationId, initialScope = 'FULL', onClose, onCommit }: { stocks: any[]; products: any[]; locations: any[]; initialLocationId: string; initialScope?: 'FULL' | 'SELECTED'; onClose: () => void; onCommit: (operation: string, payload: Record<string, unknown>, commandId: string) => Promise<void> }) {
  const runtime = useRuntime(); const runtimeRef = useRef(runtime); runtimeRef.current = runtime;
  const [locationId, setLocationId] = useState(initialLocationId);
  const [scope, setScope] = useState<'FULL' | 'SELECTED'>(initialScope);
  const [selected, setSelected] = useState<string[]>([]);
  const [draft, setDraft] = useState<InventoryCountDraft | null>(null);
  const draftRef = useRef<InventoryCountDraft | null>(null);
  const queue = useRef<Promise<void>>(Promise.resolve()); const saveFailure = useRef<unknown>(null); const submitting = useRef(false); const committed = useRef(false);
  const [review, setReview] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(false); const [busy, setBusy] = useState(false); const [scanning, setScanning] = useState(false); const [search, setSearch] = useState(''); const [barcode, setBarcode] = useState(''); const [discard, setDiscard] = useState(false);
  const scopedStocks = scope === 'FULL' ? stocks : stocks.filter(stock => selected.includes(stock.id));
  const snapshotOf = (stock: any) => ({ name: String(stock.name), baseUnit: String(stock.baseUnit), scanUnitQuantity: Number(stock.scanUnitQuantity) > 0 ? Number(stock.scanUnitQuantity) : 1, expectedQuantity: Number(stock.currentStock?.[locationId] || 0), containerSize: bottleSize(stock), consumptionRoutes: JSON.stringify(frozenDependencies(runtimeRef.current.snapshot?.records || [], [stock.id], locationId).filter(record=>record.collection==='products')), version: runtimeRef.current.snapshot?.records.find(record => record.collection === 'stockItems' && record.id === stock.id)?.version || 0 });
  const newDraft = (ids: string[], selectedScope: 'FULL' | 'SELECTED'): InventoryCountDraft => ({ sessionId: crypto.randomUUID(), revision: 1, locationId, scope: selectedScope, selectedStockItemIds: ids, baseline: Object.fromEntries(stocks.filter(stock => ids.includes(stock.id)).map(stock => [stock.id, snapshotOf(stock)])), expectedVersions: frozenDependencies(runtimeRef.current.snapshot?.records || [], ids, locationId), entries: {}, counts: {}, scanCounts: {}, unknownScans: [], reason: '' });
  const persist = (next: InventoryCountDraft) => {
    draftRef.current = next; setDraft(next); setNotice('Saving draft…');
    const job = queue.current.then(async () => { if (committed.current) return; await runtimeRef.current.saveInventoryCountDraft(next.locationId, next); saveFailure.current = null; setNotice('Draft saved'); });
    queue.current = job.catch(cause => { saveFailure.current = cause; setError(String(cause)); setNotice('Draft save failed'); }); return job;
  };
  const flush = async () => { await queue.current; if (saveFailure.current) throw saveFailure.current; };
  useEffect(() => guardLocalWork(async () => { if (submitting.current) throw new Error('Wait for count confirmation'); await flush(); }), []);
  useEffect(() => { if (!locationId) return; let current = true; setLoading(true); setError(''); setDraft(null); draftRef.current = null;
    void runtimeRef.current.inventoryCountDraft(locationId).then(saved => { if (!current) return; if (saved?.scope === 'CORRECTION') throw new Error('A balance correction is saved here. Complete it from Correct balance first.');
      if (saved) { const restored = { ...saved, scope: saved.scope || 'FULL' as const }; draftRef.current = restored; setDraft(restored); setScope(restored.scope as 'FULL' | 'SELECTED'); setSelected(restored.selectedStockItemIds || Object.keys(restored.baseline)); setReview(!!restored.pendingCommand); }
      else if (initialScope === 'FULL') { setScope('FULL'); void persist(newDraft(stocks.map(stock => stock.id), 'FULL')).catch(() => {}); }
      else { setScope('SELECTED'); setSelected([]); } setLoading(false);
    }).catch(cause => { if (current) { setError(String(cause)); setLoading(false); } }); return () => { current = false; };
  }, [locationId]);
  const change = (patch: Partial<InventoryCountDraft>) => { const current = draftRef.current; if (!current || current.pendingCommand) return; void persist({ ...current, ...patch, revision: current.revision + 1 }).catch(() => {}); };
  const enter = (stock: any, entry: CountEntry) => { const counts = { ...draftRef.current?.counts }; try { counts[stock.id] = countRow(stock, 0, entry).countedQuantity; } catch { delete counts[stock.id]; } change({ entries: { ...draftRef.current?.entries, [stock.id]: entry }, counts }); };
  const changedIds = draft ? scopedStocks.filter(stock => { const saved = draft.baseline[stock.id]; return !saved || Object.entries(snapshotOf(stock)).some(([key, value]) => saved[key as keyof typeof saved] !== value); }).map(stock => stock.id) : [];
  const locationChanged = !!draft?.expectedVersions?.some(version => version.collection !== 'stockItems' && version.version !== runtime.snapshot?.records.find(record => record.collection === version.collection && record.id === version.id)?.version);
  const coverageChanged = !!draft && (scope === 'FULL' ? Object.keys(draft.baseline).length !== stocks.length : selected.length !== scopedStocks.length);
  const rows = scopedStocks.map(stock => { try { return { ...countRow(stock, draft?.baseline[stock.id]?.expectedQuantity || 0, draft?.entries?.[stock.id] || emptyCountEntry()), stock }; } catch { return { stock, countedQuantity: null, expectedQuantity: draft?.baseline[stock.id]?.expectedQuantity || 0, stockItemId: stock.id }; } });
  const complete = !!draft && rows.length > 0 && rows.every(row => row.countedQuantity !== null) && !changedIds.length && !locationChanged && !coverageChanged && !draft.unknownScans.length;
  const receiveScan = (code: string) => { if (!draft || draft.pendingCommand || changedIds.length || busy || review) return; const candidates: Array<{ stock: any; quantity: number }> = [];
    for (const stock of scopedStocks) { if (barcodeEquals(stock.barcode, code) || barcodeEquals(stock.code, code) || (stock.barcodeAliases || []).some((alias: string) => barcodeEquals(alias, code)) || products.some(product => product.active !== false && product.stockItemId === stock.id && (barcodeEquals(product.barcode, code) || barcodeEquals(product.code, code)))) candidates.push({ stock, quantity: Number(stock.scanUnitQuantity || 1) });
      for (const pkg of stock.purchasePackages || []) if (pkg.barcode && barcodeEquals(pkg.barcode, code)) candidates.push({ stock, quantity: Number(pkg.baseQuantity) }); }
    if (candidates.length !== 1) { const unknown = [...draft.unknownScans]; const entry = unknown.find(item => item.barcode === code); if (entry) entry.count++; else unknown.push({ barcode: code, count: 1 }); change({ unknownScans: unknown }); setError('Unknown or ambiguous barcode saved. Review it before confirming.'); return; }
    try { const { stock, quantity } = candidates[0]; const entry = scannedEntry(stock, draft.entries?.[stock.id] || emptyCountEntry(), quantity); const counts = { ...draft.counts, [stock.id]: countRow(stock, 0, entry).countedQuantity }; change({ entries: { ...draft.entries, [stock.id]: entry }, counts, scanCounts: { ...draft.scanCounts, [stock.id]: (draft.scanCounts[stock.id] || 0) + 1 } }); setError(''); setBarcode(''); } catch (cause) { setError(String(cause)); }
  };
  useBarcodeScanner({ enabled: scanning && !!draft && !review && !busy && !draft.pendingCommand, minLength: 3, onScan: receiveScan });
  const commit = async () => { if (submitting.current || (!draft?.pendingCommand && !complete)) return; submitting.current = true; setBusy(true); setError(''); try { await flush(); let current = draftRef.current!;
    if (!current.pendingCommand) { const operation = scope === 'FULL' ? 'inventory.countLocation' : 'inventory.countSelected'; const revision = current.revision + 1; const payload = { locationId, reason: current.reason?.trim() || 'Physical stock count', draftSessionId: current.sessionId, draftRevision: revision, scope, selectedStockItemIds: scopedStocks.map(stock => stock.id), expectedVersions: current.expectedVersions, rows: rows.map(({ stock, ...row }) => ({...row,consumptionProductIds: JSON.parse(current.baseline[stock.id].consumptionRoutes || '[]').map((record:{id:string})=>record.id).sort()})) }; current = { ...current, revision, pendingCommand: { id: crypto.randomUUID(), operation, payload } }; await persist(current); }
    const request = current.pendingCommand!; await onCommit(request.operation || 'inventory.countLocation', request.payload, request.id); committed.current = true;
    // Shared commands commit remotely; close their terminal-local draft only after confirmation.
    await runtimeRef.current.clearInventoryCountDraft(locationId).catch(() => {});
  } catch (cause) { setError(`${String(cause)}. Retry preserves the reviewed command.`); } finally { submitting.current = false; setBusy(false); } };
  return <ActionDialog title={scope === 'FULL' ? 'Full stocktake' : 'Quick count'} onClose={() => void flushLocalWork().then(onClose).catch(cause => setError(String(cause)))}><div className="max-h-[75vh] space-y-3 overflow-auto">
    {!locationId ? <><p>Where are you counting?</p>{locations.map(location => <button key={location.id} className={buttonClass} onClick={() => setLocationId(location.id)}>{location.name}</button>)}</> : <p className="text-sm text-slate-400">{locations.find(location => location.id === locationId)?.name} · {scope === 'FULL' ? 'Every active stock item is required.' : 'Only selected items change; all other stock stays unchanged.'} Pause affected sales and movements while counting.</p>}
    {loading && <p>Loading saved count…</p>}{error && <p role="alert" className="text-sm text-rose-200">{error}</p>}{notice && <p role="status" className="text-xs text-slate-400">{notice}</p>}
    {locationId && !draft && !loading && !error && scope === 'SELECTED' && <><p>Select the items to count.</p>{stocks.map(stock => <label key={stock.id} className="flex gap-2 p-2"><input type="checkbox" checked={selected.includes(stock.id)} onChange={event => setSelected(previous => event.target.checked ? [...previous, stock.id] : previous.filter(id => id !== stock.id))}/>{stock.name}</label>)}<button className={primaryButtonClass} disabled={!selected.length} onClick={() => void persist(newDraft(selected, 'SELECTED')).catch(() => {})}>Start selected count</button></>}
    {draft && <>{!draft.entries && !draft.pendingCommand && <p role="alert" className="text-amber-200">This is an older saved draft. Its totals are preserved; recount physical bottles before posting.</p>}
      {(changedIds.length > 0 || locationChanged || coverageChanged) && !draft.pendingCommand && <><p role="alert" className="text-amber-200">Stock or configuration changed. Recount affected items before confirming.</p><button className={buttonClass} onClick={() => { const ids = scopedStocks.map(stock => stock.id); const resetIds = locationChanged ? ids : changedIds; setSelected(ids); const next = newDraft(ids, scope); next.sessionId = draft.sessionId; next.revision = draft.revision + 1; next.entries = Object.fromEntries(Object.entries(draft.entries || {}).filter(([id]) => ids.includes(id) && !resetIds.includes(id))); next.counts = Object.fromEntries(Object.entries(draft.counts).filter(([id]) => ids.includes(id) && !resetIds.includes(id))); next.scanCounts = Object.fromEntries(Object.entries(draft.scanCounts).filter(([id]) => ids.includes(id) && !resetIds.includes(id))); next.reason = draft.reason; next.unknownScans = draft.unknownScans; void persist(next).catch(() => {}); }}>Recount changed items</button></>}
      {!review && !draft.pendingCommand && <><button className={buttonClass} onClick={() => setScanning(value => !value)}>{scanning ? 'Pause scanning' : 'Continuous scanner session'}</button>{scanning && <label className="block text-sm">Scan a barcode<input className={fieldClass} data-barcode-capture="true" value={barcode} onChange={event => setBarcode(event.target.value)} onKeyDown={event => { if (event.key === 'Enter' && !event.defaultPrevented) { event.preventDefault(); receiveScan(barcode.trim()); } }}/></label>}<input aria-label="Search count items" className={fieldClass} placeholder="Search within this count" value={search} onChange={event => setSearch(event.target.value)}/></>}
      {draft.unknownScans.map(entry => <div key={entry.barcode} className="rounded border border-rose-500 p-2 text-sm">{entry.barcode} × {entry.count} · Verify barcode conversion in Catalog, then rescan.<button className={buttonClass} disabled={!!draft.pendingCommand} onClick={() => change({ unknownScans: draft.unknownScans.filter(item => item.barcode !== entry.barcode) })}>Dismiss mistaken scan</button></div>)}
      {rows.filter(row => review || row.stock.name.toLowerCase().includes(search.toLowerCase())).map(row => <div key={row.stock.id} className="rounded-xl border border-slate-700 p-3"><b>{row.stock.name}</b><p className="text-xs text-slate-400">Expected {physicalStock(row.stock, locationId)} · {row.expectedQuantity.toLocaleString()} {row.stock.baseUnit}</p>{review || draft.pendingCommand ? <p>{row.countedQuantity === null ? 'Uncounted' : `${row.expectedQuantity.toLocaleString()} → ${row.countedQuantity.toLocaleString()} ${row.stock.baseUnit}`}</p> : <BottleInputs stock={row.stock} value={draft.entries?.[row.stock.id] || emptyCountEntry()} sealedOnly={classifyBottleStock(row.stock, products).sealedOnly} onChange={entry => enter(row.stock, entry)}/>}</div>)}
      {!review && !draft.pendingCommand && <label className="block text-sm">Count note<textarea className={fieldClass} maxLength={500} value={draft.reason || ''} onChange={event => change({ reason: event.target.value })}/></label>}
      <p className="text-xs text-slate-400">{rows.filter(row => row.countedQuantity !== null).length} / {rows.length} counted. Stock changes only after confirmation.</p>
      {review || draft.pendingCommand ? <div className="flex gap-2"><button className={buttonClass} disabled={busy || !!draft.pendingCommand} onClick={() => setReview(false)}>Back to count</button><button className={primaryButtonClass} disabled={busy || (!draft.pendingCommand && !complete)} onClick={() => void commit()}>{draft.pendingCommand ? 'Retry Confirm Count' : 'Confirm Count'}</button></div> : <button className={primaryButtonClass} disabled={!complete || busy} onClick={() => void flush().then(() => { setReview(true); setScanning(false); }).catch(cause => setError(String(cause)))}>Review count</button>}
      <button className={buttonClass} disabled={busy} onClick={() => setDiscard(true)}>Correct mistake · Discard draft</button>{saveFailure.current != null && <button className={buttonClass} onClick={() => void persist(draft).catch(() => {})}>Retry saving draft</button>}
    </>}
    {discard && <div className="rounded border border-amber-500 p-3"><p>Discard the unposted draft? Pending commands must be resolved first; committed counts remain in history.</p><button className={buttonClass} onClick={() => setDiscard(false)}>Keep draft</button><button className={buttonClass} disabled={busy} onClick={() => void flush().then(() => runtime.clearInventoryCountDraft(locationId)).then(onClose).catch(cause => setError(String(cause)))}>Discard draft</button></div>}
  </div></ActionDialog>;
}
